import type { SiteLocale } from "./site-locale";

export type HomepageCopy = {
  eyebrow: string;
  title: string;
  description: string;
  start: string;
  verify: string;
  productTabs: string;
  switchProduct: string;
  maxSpread: string;
  categoryEyebrow: string;
  categoryTitle: string;
  categories: {
    ai: [string, string];
    streaming: [string, string];
    converter: [string, string];
    guides: [string, string];
    spreadPrefix: string;
  };
  proofTitle: string;
  proof: {
    sources: [string, string, string];
    affordability: [string, string, string];
    exchange: [string, string, string];
  };
  disclaimer: string;
  pricesVerified: string;
  source: string;
  updated: string;
  unavailable: string;
  map: {
    mapLabel: string;
    noData: string;
    unknown: string;
    same: string;
    lower: string;
    higher: string;
    lowest: string;
    highest: string;
    reference: string;
    recorded: string;
    keyRegions: string;
    close: string;
    perMonth: string;
    localPrice: string;
    tax: string;
    currentComparison: string;
    convertedMonthly: string;
    verifiedRegions: string;
    regionsSuffix: string;
    viewDetails: string;
  };
};

const copy: Record<SiteLocale, HomepageCopy> = {
  zh: {
    eyebrow: "GeoSub · 数字订阅成本情报", title: "别只看标价，看清数字订阅的真实地区成本", description: "比较经过核验的地区价格、税费、汇率与本地购买力，快速判断哪里更便宜，数据是否仍然可信。", start: "开始比较价格", verify: "数据如何核验", productTabs: "热门订阅产品", switchProduct: "切换到", maxSpread: "最大价差", categoryEyebrow: "按需求浏览", categoryTitle: "先找到你需要的服务，再比较各地成本", categories: { ai: ["AI 订阅", "查看常用 AI 订阅的月费、地区价差与购买力负担。"], streaming: ["流媒体", "比较视频与音乐订阅在不同商店地区的真实月费。"], converter: ["订阅汇率工具", "用持续同步的汇率估算订阅支出，不依赖固定汇率。"], guides: ["订阅指南", "理解税费、账号地区、付款条件和跨区限制。"], spreadPrefix: "已核验地区价差最高" }, proofTitle: "每个价格结论，都应该有证据可追溯", proof: { sources: ["数据来源", "价格来自哪里、何时采集、是否复核，一页看清。", "查看详情"], affordability: ["本地购买力", "把月费放进当地收入水平，判断便宜是否真的便宜。", "查看详情"], exchange: ["汇率换算", "用最新同步汇率换算订阅金额，区分价格变化与汇率波动。", "查看详情"] }, disclaimer: "GeoSub 提供独立的价格与成本比较，最终结算金额以平台页面为准。", pricesVerified: "条已核验价格", source: "来源", updated: "更新", unavailable: "价格数据库暂时不可用，请稍后重试。", map: { mapLabel: "全球地区价格分级地图", noData: "暂无官方订阅数据", unknown: "未知地区", same: "与美国基准相同", lower: "较美国基准低", higher: "较美国基准高", lowest: "全球最低价", highest: "当前最高价", reference: "美国基准", recorded: "已收录地区", keyRegions: "关键价格地区", close: "关闭地图详情", perMonth: "/月", localPrice: "当地价格", tax: "税费", currentComparison: "当前比较", convertedMonthly: "美元折算月费", verifiedRegions: "已核验地区", regionsSuffix: "个", viewDetails: "地区详情" },
  },
  "zh-tw": {
    eyebrow: "GeoSub · 數位訂閱成本情報", title: "別只看標價，看清數位訂閱的真實地區成本", description: "比較經過核驗的地區價格、稅費、匯率與在地購買力，快速判斷哪裡更便宜、資料是否仍可信。", start: "開始比較價格", verify: "資料如何核驗", productTabs: "熱門訂閱產品", switchProduct: "切換至", maxSpread: "最大價差", categoryEyebrow: "依需求瀏覽", categoryTitle: "先找到需要的服務，再比較各地成本", categories: { ai: ["AI 訂閱", "查看常用 AI 訂閱的月費、地區價差與購買力負擔。"], streaming: ["串流媒體", "比較影音訂閱在不同商店地區的真實月費。"], converter: ["訂閱匯率工具", "用持續同步的匯率估算訂閱支出。"], guides: ["訂閱指南", "了解稅費、帳號地區、付款條件與跨區限制。"], spreadPrefix: "已核驗地區價差最高" }, proofTitle: "每個價格結論，都應該有可追溯的證據", proof: { sources: ["資料來源", "價格來自哪裡、何時採集、是否複核，一頁看清。", "查看詳情"], affordability: ["在地購買力", "把月費放進當地收入水準，判斷便宜是否真的便宜。", "查看詳情"], exchange: ["匯率換算", "用最新同步匯率區分價格變化與匯率波動。", "查看詳情"] }, disclaimer: "GeoSub 提供獨立的價格與成本比較，最終結算金額以平台頁面為準。", pricesVerified: "筆已核驗價格", source: "來源", updated: "更新", unavailable: "價格資料庫暫時無法使用，請稍後再試。", map: { mapLabel: "全球地區價格分級地圖", noData: "暫無官方訂閱資料", unknown: "未知地區", same: "與美國基準相同", lower: "較美國基準低", higher: "較美國基準高", lowest: "全球最低價", highest: "目前最高價", reference: "美國基準", recorded: "已收錄地區", keyRegions: "關鍵價格地區", close: "關閉地圖詳情", perMonth: "/月", localPrice: "當地價格", tax: "稅費", currentComparison: "目前比較", convertedMonthly: "美元換算月費", verifiedRegions: "已核驗地區", regionsSuffix: "個", viewDetails: "地區詳情" },
  },
  en: {
    eyebrow: "GeoSub · Subscription cost intelligence", title: "Look beyond the list price. See the real regional cost of digital subscriptions.", description: "Compare verified regional prices, taxes, exchange rates and local affordability to see where a subscription really costs less.", start: "Compare prices", verify: "How data is verified", productTabs: "Popular subscriptions", switchProduct: "Switch to", maxSpread: "Max spread", categoryEyebrow: "Browse by need", categoryTitle: "Find the service first, then compare regional costs", categories: { ai: ["AI subscriptions", "Compare monthly prices, regional spreads and affordability for popular AI services."], streaming: ["Streaming", "Compare the real monthly cost of video and music subscriptions by store region."], converter: ["Currency converter", "Estimate subscription costs with regularly synchronized exchange rates."], guides: ["Subscription guides", "Understand taxes, account regions, payment conditions and regional restrictions."], spreadPrefix: "Highest verified spread" }, proofTitle: "Every price conclusion should be traceable to evidence", proof: { sources: ["Data sources", "See where prices came from, when they were collected and how they were reviewed.", "View details"], affordability: ["Local affordability", "Put the monthly price in the context of local income.", "View details"], exchange: ["Exchange rates", "Separate actual price changes from currency movement.", "View details"] }, disclaimer: "GeoSub provides independent price and cost comparisons. The platform checkout price is final.", pricesVerified: "verified prices", source: "Source", updated: "Updated", unavailable: "Pricing data is temporarily unavailable. Please try again later.", map: { mapLabel: "global regional price map", noData: "No official subscription data", unknown: "Unknown region", same: "Same as the US benchmark", lower: "below the US benchmark", higher: "above the US benchmark", lowest: "Global lowest", highest: "Current highest", reference: "US benchmark", recorded: "Covered region", keyRegions: "Key pricing regions", close: "Close map details", perMonth: "/mo", localPrice: "Local price", tax: "Tax", currentComparison: "Current comparison", convertedMonthly: "USD-converted monthly price", verifiedRegions: "Verified regions", regionsSuffix: "", viewDetails: "regional details" },
  },
  ja: {
    eyebrow: "GeoSub · サブスクリプション価格情報", title: "表示価格だけでなく、デジタル購読の実質的な地域コストを確認", description: "確認済みの地域価格、税、為替、現地の購買力を比較し、本当に安い地域を判断できます。", start: "価格を比較", verify: "データの確認方法", productTabs: "人気のサブスクリプション", switchProduct: "切り替え：", maxSpread: "最大価格差", categoryEyebrow: "目的から探す", categoryTitle: "サービスを選び、地域ごとのコストを比較", categories: { ai: ["AI サブスクリプション", "主要AIサービスの月額、地域差、負担感を確認。"], streaming: ["ストリーミング", "動画・音楽サービスの実質月額を地域別に比較。"], converter: ["通貨換算ツール", "同期された為替レートで購読費を試算。"], guides: ["購読ガイド", "税、アカウント地域、支払い条件を理解。"], spreadPrefix: "確認済み最大価格差" }, proofTitle: "すべての価格判断に、追跡できる根拠を", proof: { sources: ["データソース", "価格の取得元、取得日、確認状況を確認。", "詳細を見る"], affordability: ["現地の負担感", "月額を現地所得と照らして評価。", "詳細を見る"], exchange: ["為替換算", "価格変更と為替変動を切り分けます。", "詳細を見る"] }, disclaimer: "GeoSubは独立した価格比較サービスです。最終金額は公式決済画面をご確認ください。", pricesVerified: "件の確認済み価格", source: "出典", updated: "更新", unavailable: "価格データを現在利用できません。しばらくしてからお試しください。", map: { mapLabel: "世界の地域別価格マップ", noData: "公式購読データなし", unknown: "不明な地域", same: "米国基準と同じ", lower: "米国基準より安い", higher: "米国基準より高い", lowest: "世界最安", highest: "現在の最高値", reference: "米国基準", recorded: "収録地域", keyRegions: "主要価格地域", close: "地図の詳細を閉じる", perMonth: "/月", localPrice: "現地価格", tax: "税", currentComparison: "現在の比較", convertedMonthly: "米ドル換算月額", verifiedRegions: "確認済み地域", regionsSuffix: "地域", viewDetails: "地域別詳細" },
  },
  ko: {
    eyebrow: "GeoSub · 구독 비용 인텔리전스", title: "표시 가격을 넘어 디지털 구독의 실제 지역별 비용을 확인하세요", description: "검증된 지역 가격, 세금, 환율과 현지 구매력을 비교해 실제로 더 저렴한 지역을 판단합니다.", start: "가격 비교 시작", verify: "데이터 검증 방식", productTabs: "인기 구독", switchProduct: "전환", maxSpread: "최대 가격 차이", categoryEyebrow: "필요에 따라 탐색", categoryTitle: "서비스를 먼저 찾고 지역별 비용을 비교하세요", categories: { ai: ["AI 구독", "주요 AI 서비스의 월 요금과 지역별 가격 차이를 확인합니다."], streaming: ["스트리밍", "영상·음악 구독의 실제 월 요금을 지역별로 비교합니다."], converter: ["환율 도구", "동기화된 환율로 구독 지출을 계산합니다."], guides: ["구독 가이드", "세금, 계정 지역과 결제 조건을 이해합니다."], spreadPrefix: "검증된 최대 가격 차이" }, proofTitle: "모든 가격 결론에는 추적 가능한 근거가 있어야 합니다", proof: { sources: ["데이터 출처", "가격 출처와 수집·검토 시점을 확인합니다.", "자세히 보기"], affordability: ["현지 구매력", "월 요금을 현지 소득 수준과 함께 봅니다.", "자세히 보기"], exchange: ["환율 환산", "가격 변화와 환율 변동을 구분합니다.", "자세히 보기"] }, disclaimer: "GeoSub는 독립적인 가격 비교를 제공합니다. 최종 결제 금액은 플랫폼에서 확인하세요.", pricesVerified: "개의 검증 가격", source: "출처", updated: "업데이트", unavailable: "가격 데이터를 일시적으로 사용할 수 없습니다.", map: { mapLabel: "글로벌 지역별 가격 지도", noData: "공식 구독 데이터 없음", unknown: "알 수 없는 지역", same: "미국 기준과 동일", lower: "미국 기준보다 저렴", higher: "미국 기준보다 비쌈", lowest: "전 세계 최저가", highest: "현재 최고가", reference: "미국 기준", recorded: "수록 지역", keyRegions: "주요 가격 지역", close: "지도 상세 닫기", perMonth: "/월", localPrice: "현지 가격", tax: "세금", currentComparison: "현재 비교", convertedMonthly: "미국 달러 환산 월 요금", verifiedRegions: "검증 지역", regionsSuffix: "개", viewDetails: "지역 상세" },
  },
  es: {
    eyebrow: "GeoSub · Inteligencia de costes", title: "Mira más allá del precio: descubre el coste regional real de tus suscripciones", description: "Compara precios regionales verificados, impuestos, tipos de cambio y poder adquisitivo local.", start: "Comparar precios", verify: "Cómo verificamos los datos", productTabs: "Suscripciones populares", switchProduct: "Cambiar a", maxSpread: "Diferencia máxima", categoryEyebrow: "Explorar por necesidad", categoryTitle: "Encuentra el servicio y compara sus costes regionales", categories: { ai: ["Suscripciones de IA", "Compara cuotas mensuales, diferencias regionales y asequibilidad."], streaming: ["Streaming", "Compara el coste mensual real de vídeo y música por región."], converter: ["Conversor de divisas", "Calcula el gasto con tipos de cambio sincronizados."], guides: ["Guías de suscripción", "Entiende impuestos, cuentas y condiciones de pago."], spreadPrefix: "Mayor diferencia verificada" }, proofTitle: "Cada conclusión de precio debe tener evidencia rastreable", proof: { sources: ["Fuentes de datos", "Consulta el origen, la fecha y la revisión de cada precio.", "Ver detalles"], affordability: ["Asequibilidad local", "Relaciona la cuota con los ingresos locales.", "Ver detalles"], exchange: ["Tipos de cambio", "Distingue cambios de precio y movimientos de divisa.", "Ver detalles"] }, disclaimer: "GeoSub ofrece comparaciones independientes. El importe final es el de la plataforma.", pricesVerified: "precios verificados", source: "Fuente", updated: "Actualizado", unavailable: "Los datos de precios no están disponibles temporalmente.", map: { mapLabel: "mapa mundial de precios regionales", noData: "Sin datos oficiales de suscripción", unknown: "Región desconocida", same: "Igual que la referencia de EE. UU.", lower: "menos que la referencia de EE. UU.", higher: "más que la referencia de EE. UU.", lowest: "Mínimo mundial", highest: "Máximo actual", reference: "Referencia EE. UU.", recorded: "Región incluida", keyRegions: "Regiones de precio clave", close: "Cerrar detalles del mapa", perMonth: "/mes", localPrice: "Precio local", tax: "Impuestos", currentComparison: "Comparación actual", convertedMonthly: "Mensualidad convertida a USD", verifiedRegions: "Regiones verificadas", regionsSuffix: "", viewDetails: "detalles regionales" },
  },
  tr: {
    eyebrow: "GeoSub · Abonelik maliyet zekâsı", title: "Etiket fiyatının ötesine geçin, dijital aboneliğin gerçek bölgesel maliyetini görün", description: "Doğrulanmış bölgesel fiyatları, vergileri, kurları ve yerel satın alma gücünü karşılaştırın.", start: "Fiyatları karşılaştır", verify: "Veriler nasıl doğrulanır", productTabs: "Popüler abonelikler", switchProduct: "Geçiş", maxSpread: "En yüksek fark", categoryEyebrow: "İhtiyaca göre keşfet", categoryTitle: "Önce hizmeti bulun, sonra bölgesel maliyetleri karşılaştırın", categories: { ai: ["Yapay zekâ abonelikleri", "Aylık ücretleri ve bölgesel farkları karşılaştırın."], streaming: ["Dijital yayın", "Video ve müzik aboneliklerinin gerçek aylık maliyetini karşılaştırın."], converter: ["Döviz aracı", "Güncel kurlarla abonelik giderini hesaplayın."], guides: ["Abonelik rehberleri", "Vergi, hesap bölgesi ve ödeme koşullarını anlayın."], spreadPrefix: "Doğrulanmış en yüksek fark" }, proofTitle: "Her fiyat sonucu izlenebilir kanıta dayanmalı", proof: { sources: ["Veri kaynakları", "Fiyatın kaynağını, tarihini ve inceleme durumunu görün.", "Ayrıntıları gör"], affordability: ["Yerel karşılanabilirlik", "Aylık ücreti yerel gelirle karşılaştırın.", "Ayrıntıları gör"], exchange: ["Döviz kurları", "Fiyat değişimiyle kur hareketini ayırın.", "Ayrıntıları gör"] }, disclaimer: "GeoSub bağımsız karşılaştırma sunar. Son ödeme tutarı platformda belirlenir.", pricesVerified: "doğrulanmış fiyat", source: "Kaynak", updated: "Güncelleme", unavailable: "Fiyat verileri geçici olarak kullanılamıyor.", map: { mapLabel: "küresel bölgesel fiyat haritası", noData: "Resmî abonelik verisi yok", unknown: "Bilinmeyen bölge", same: "ABD referansıyla aynı", lower: "ABD referansından düşük", higher: "ABD referansından yüksek", lowest: "Dünya genelinde en düşük", highest: "Mevcut en yüksek", reference: "ABD referansı", recorded: "Kapsanan bölge", keyRegions: "Önemli fiyat bölgeleri", close: "Harita ayrıntısını kapat", perMonth: "/ay", localPrice: "Yerel fiyat", tax: "Vergi", currentComparison: "Mevcut karşılaştırma", convertedMonthly: "USD çevrilmiş aylık ücret", verifiedRegions: "Doğrulanmış bölgeler", regionsSuffix: "", viewDetails: "bölge ayrıntıları" },
  },
  ar: {
    eyebrow: "GeoSub · معلومات تكلفة الاشتراكات", title: "تجاوز السعر المعلن واعرف التكلفة الإقليمية الحقيقية للاشتراك الرقمي", description: "قارن الأسعار الإقليمية الموثقة والضرائب وأسعار الصرف والقوة الشرائية المحلية.", start: "ابدأ مقارنة الأسعار", verify: "كيف نتحقق من البيانات", productTabs: "الاشتراكات الشائعة", switchProduct: "التبديل إلى", maxSpread: "أكبر فارق", categoryEyebrow: "تصفح حسب الحاجة", categoryTitle: "اختر الخدمة أولاً ثم قارن التكلفة بين المناطق", categories: { ai: ["اشتراكات الذكاء الاصطناعي", "قارن الرسوم الشهرية وفروق الأسعار الإقليمية."], streaming: ["خدمات البث", "قارن التكلفة الشهرية الحقيقية للفيديو والموسيقى."], converter: ["محول العملات", "قدّر تكلفة الاشتراك بأسعار صرف محدثة."], guides: ["أدلة الاشتراك", "افهم الضرائب ومنطقة الحساب وشروط الدفع."], spreadPrefix: "أكبر فارق موثق" }, proofTitle: "يجب أن يستند كل استنتاج سعري إلى دليل قابل للتتبع", proof: { sources: ["مصادر البيانات", "اعرف مصدر السعر وتاريخ جمعه ومراجعته.", "عرض التفاصيل"], affordability: ["القدرة الشرائية المحلية", "قارن الرسوم الشهرية بمستوى الدخل المحلي.", "عرض التفاصيل"], exchange: ["أسعار الصرف", "ميّز تغير السعر عن حركة العملة.", "عرض التفاصيل"] }, disclaimer: "يقدم GeoSub مقارنة مستقلة، والسعر النهائي هو الظاهر عند الدفع على المنصة.", pricesVerified: "سعراً موثقاً", source: "المصدر", updated: "التحديث", unavailable: "بيانات الأسعار غير متاحة مؤقتاً.", map: { mapLabel: "خريطة الأسعار الإقليمية العالمية", noData: "لا توجد بيانات اشتراك رسمية", unknown: "منطقة غير معروفة", same: "مماثل لمرجع الولايات المتحدة", lower: "أقل من مرجع الولايات المتحدة", higher: "أعلى من مرجع الولايات المتحدة", lowest: "الأدنى عالمياً", highest: "الأعلى حالياً", reference: "مرجع الولايات المتحدة", recorded: "منطقة مشمولة", keyRegions: "مناطق الأسعار الرئيسية", close: "إغلاق تفاصيل الخريطة", perMonth: "/شهر", localPrice: "السعر المحلي", tax: "الضريبة", currentComparison: "المقارنة الحالية", convertedMonthly: "السعر الشهري المحول إلى الدولار", verifiedRegions: "المناطق الموثقة", regionsSuffix: "", viewDetails: "تفاصيل المناطق" },
  },
  fr: {
    eyebrow: "GeoSub · Intelligence des coûts", title: "Au-delà du tarif affiché, découvrez le coût régional réel de vos abonnements", description: "Comparez les prix régionaux vérifiés, les taxes, les taux de change et le pouvoir d’achat local.", start: "Comparer les prix", verify: "Comment les données sont vérifiées", productTabs: "Abonnements populaires", switchProduct: "Passer à", maxSpread: "Écart maximal", categoryEyebrow: "Explorer par besoin", categoryTitle: "Choisissez le service, puis comparez les coûts régionaux", categories: { ai: ["Abonnements IA", "Comparez les mensualités, écarts régionaux et l’accessibilité."], streaming: ["Streaming", "Comparez le coût mensuel réel de la vidéo et de la musique."], converter: ["Convertisseur", "Estimez vos dépenses avec des taux de change synchronisés."], guides: ["Guides d’abonnement", "Comprenez taxes, région du compte et conditions de paiement."], spreadPrefix: "Écart vérifié maximal" }, proofTitle: "Chaque conclusion de prix doit reposer sur des preuves traçables", proof: { sources: ["Sources des données", "Consultez l’origine, la date et la vérification des prix.", "Voir les détails"], affordability: ["Pouvoir d’achat local", "Replacez la mensualité dans le contexte des revenus locaux.", "Voir les détails"], exchange: ["Taux de change", "Distinguez changement de prix et mouvement de devise.", "Voir les détails"] }, disclaimer: "GeoSub fournit une comparaison indépendante. Le montant final est celui de la plateforme.", pricesVerified: "prix vérifiés", source: "Source", updated: "Mis à jour", unavailable: "Les données de prix sont temporairement indisponibles.", map: { mapLabel: "carte mondiale des prix régionaux", noData: "Aucune donnée officielle d’abonnement", unknown: "Région inconnue", same: "Identique à la référence américaine", lower: "sous la référence américaine", higher: "au-dessus de la référence américaine", lowest: "Prix mondial le plus bas", highest: "Prix actuel le plus élevé", reference: "Référence États-Unis", recorded: "Région couverte", keyRegions: "Régions tarifaires clés", close: "Fermer les détails de la carte", perMonth: "/mois", localPrice: "Prix local", tax: "Taxes", currentComparison: "Comparaison actuelle", convertedMonthly: "Mensualité convertie en USD", verifiedRegions: "Régions vérifiées", regionsSuffix: "", viewDetails: "détails régionaux" },
  },
  it: {
    eyebrow: "GeoSub · Analisi dei costi", title: "Oltre il prezzo di listino: scopri il vero costo regionale degli abbonamenti", description: "Confronta prezzi regionali verificati, imposte, cambi e potere d’acquisto locale.", start: "Confronta i prezzi", verify: "Come verifichiamo i dati", productTabs: "Abbonamenti popolari", switchProduct: "Passa a", maxSpread: "Scarto massimo", categoryEyebrow: "Esplora per esigenza", categoryTitle: "Trova il servizio e confronta i costi regionali", categories: { ai: ["Abbonamenti IA", "Confronta canoni mensili e differenze regionali."], streaming: ["Streaming", "Confronta il costo mensile reale di video e musica."], converter: ["Convertitore valute", "Stima la spesa con tassi di cambio sincronizzati."], guides: ["Guide agli abbonamenti", "Comprendi imposte, paese dell’account e pagamenti."], spreadPrefix: "Scarto verificato massimo" }, proofTitle: "Ogni conclusione di prezzo deve avere prove tracciabili", proof: { sources: ["Fonti dei dati", "Controlla origine, data e revisione dei prezzi.", "Vedi dettagli"], affordability: ["Accessibilità locale", "Confronta il canone con il reddito locale.", "Vedi dettagli"], exchange: ["Tassi di cambio", "Distingui variazioni di prezzo e valuta.", "Vedi dettagli"] }, disclaimer: "GeoSub offre confronti indipendenti. Fa fede il prezzo finale della piattaforma.", pricesVerified: "prezzi verificati", source: "Fonte", updated: "Aggiornato", unavailable: "I dati sui prezzi non sono temporaneamente disponibili.", map: { mapLabel: "mappa mondiale dei prezzi regionali", noData: "Nessun dato ufficiale", unknown: "Regione sconosciuta", same: "Uguale al riferimento USA", lower: "sotto il riferimento USA", higher: "sopra il riferimento USA", lowest: "Minimo globale", highest: "Massimo attuale", reference: "Riferimento USA", recorded: "Regione coperta", keyRegions: "Regioni chiave", close: "Chiudi i dettagli", perMonth: "/mese", localPrice: "Prezzo locale", tax: "Imposte", currentComparison: "Confronto attuale", convertedMonthly: "Mensilità convertita in USD", verifiedRegions: "Regioni verificate", regionsSuffix: "", viewDetails: "dettagli regionali" },
  },
  de: {
    eyebrow: "GeoSub · Abonnementkosten im Vergleich", title: "Mehr als der Listenpreis: die tatsächlichen regionalen Kosten digitaler Abos", description: "Vergleichen Sie geprüfte Regionalpreise, Steuern, Wechselkurse und lokale Kaufkraft.", start: "Preise vergleichen", verify: "So prüfen wir Daten", productTabs: "Beliebte Abonnements", switchProduct: "Wechseln zu", maxSpread: "Maximale Spanne", categoryEyebrow: "Nach Bedarf suchen", categoryTitle: "Dienst auswählen und regionale Kosten vergleichen", categories: { ai: ["KI-Abonnements", "Vergleichen Sie Monatsgebühren und regionale Preisunterschiede."], streaming: ["Streaming", "Vergleichen Sie die tatsächlichen Monatskosten von Video und Musik."], converter: ["Währungsrechner", "Berechnen Sie Kosten mit synchronisierten Wechselkursen."], guides: ["Abo-Ratgeber", "Verstehen Sie Steuern, Kontoregionen und Zahlungsbedingungen."], spreadPrefix: "Höchste geprüfte Spanne" }, proofTitle: "Jede Preisaussage braucht nachvollziehbare Belege", proof: { sources: ["Datenquellen", "Sehen Sie Herkunft, Datum und Prüfung der Preise.", "Details ansehen"], affordability: ["Lokale Kaufkraft", "Ordnen Sie Monatsgebühren anhand lokaler Einkommen ein.", "Details ansehen"], exchange: ["Wechselkurse", "Trennen Sie Preisänderungen von Währungsschwankungen.", "Details ansehen"] }, disclaimer: "GeoSub bietet unabhängige Vergleiche. Maßgeblich ist der Endpreis der Plattform.", pricesVerified: "geprüfte Preise", source: "Quelle", updated: "Aktualisiert", unavailable: "Preisdaten sind vorübergehend nicht verfügbar.", map: { mapLabel: "Weltkarte regionaler Preise", noData: "Keine offiziellen Abodaten", unknown: "Unbekannte Region", same: "Wie US-Referenz", lower: "unter der US-Referenz", higher: "über der US-Referenz", lowest: "Global niedrigster Preis", highest: "Aktuell höchster Preis", reference: "US-Referenz", recorded: "Erfasste Region", keyRegions: "Wichtige Preisregionen", close: "Kartendetails schließen", perMonth: "/Monat", localPrice: "Lokaler Preis", tax: "Steuern", currentComparison: "Aktueller Vergleich", convertedMonthly: "Monatspreis in USD", verifiedRegions: "Geprüfte Regionen", regionsSuffix: "", viewDetails: "Regionsdetails" },
  },
  pt: {
    eyebrow: "GeoSub · Inteligência de custos", title: "Além do preço anunciado: veja o custo regional real das assinaturas", description: "Compare preços regionais verificados, impostos, câmbios e poder de compra local.", start: "Comparar preços", verify: "Como verificamos os dados", productTabs: "Assinaturas populares", switchProduct: "Mudar para", maxSpread: "Diferença máxima", categoryEyebrow: "Explorar por necessidade", categoryTitle: "Encontre o serviço e compare os custos regionais", categories: { ai: ["Assinaturas de IA", "Compare mensalidades e diferenças regionais."], streaming: ["Streaming", "Compare o custo mensal real de vídeo e música."], converter: ["Conversor de moedas", "Estime despesas com câmbios sincronizados."], guides: ["Guias de assinatura", "Entenda impostos, país da conta e pagamentos."], spreadPrefix: "Maior diferença verificada" }, proofTitle: "Cada conclusão de preço deve ter provas rastreáveis", proof: { sources: ["Fontes de dados", "Veja origem, data e revisão dos preços.", "Ver detalhes"], affordability: ["Poder de compra local", "Compare a mensalidade com o rendimento local.", "Ver detalhes"], exchange: ["Taxas de câmbio", "Distinga alteração de preço e movimento cambial.", "Ver detalhes"] }, disclaimer: "O GeoSub oferece comparações independentes. Prevalece o preço final da plataforma.", pricesVerified: "preços verificados", source: "Fonte", updated: "Atualizado", unavailable: "Os dados de preços estão temporariamente indisponíveis.", map: { mapLabel: "mapa mundial de preços regionais", noData: "Sem dados oficiais de assinatura", unknown: "Região desconhecida", same: "Igual à referência dos EUA", lower: "abaixo da referência dos EUA", higher: "acima da referência dos EUA", lowest: "Mínimo global", highest: "Máximo atual", reference: "Referência EUA", recorded: "Região coberta", keyRegions: "Regiões de preço principais", close: "Fechar detalhes do mapa", perMonth: "/mês", localPrice: "Preço local", tax: "Impostos", currentComparison: "Comparação atual", convertedMonthly: "Mensalidade convertida em USD", verifiedRegions: "Regiões verificadas", regionsSuffix: "", viewDetails: "detalhes regionais" },
  },
};

export function getHomepageCopy(locale: SiteLocale) {
  return copy[locale];
}
