import type { SiteLocale } from "./site-locale";

export type PricingPressureCopy = {
  title: (product: string) => string;
  description: string;
  tabs: { price: string; burden: string; matrix: string };
  pending: {
    generic: string;
    noRows: string;
    coverage: (covered: number, published: number) => string;
    noUs: string;
    stale: string;
  };
  position: {
    title: string;
    description: string;
    lowest: string;
    nearBase: string;
    highest: string;
    lowestHint: string;
    baseHint: (country: string) => string;
    highestHint: string;
    noBigMac: string;
    bigMac: (count: string, regional: boolean) => string;
    chartTitle: string;
    chartDescription: (country: string) => string;
    lowEnd: string;
    usBase: string;
    highEnd: string;
    region: string;
    cheaper: string;
    pricier: string;
    priceDiff: string;
    limited: (shown: number, total: number) => string;
    source: (date: string) => string;
  };
  matrix: {
    title: string;
    description: string;
    heavier: string;
    lowerPrice: string;
    higherPrice: string;
    quadrants: Array<{ title: string; helper: string }>;
    note: string;
    pointTitle: (country: string, diff: string, burden: string) => string;
    ariaLabel: string;
  };
};

const copies = {
  zh: {
    title: (p) => `${p} 价格与购买力`, description: "分开查看地区标价、当地收入负担，以及两者是否一致。", tabs: { price: "价格位置", burden: "收入负担", matrix: "双维判断" },
    pending: { generic: "收入负担数据未通过完整性检查，当前不会用价格差冒充购买力结论。", noRows: "收入数据尚未与当前 App Store 价格形成可发布结果，暂不展示购买力结论。", coverage: (c, p) => `当前收入数据覆盖 ${c}/${p} 个价格地区，未达到 80% 发布门槛。`, noUs: "缺少美国收入负担基准，暂时无法计算跨区相对负担。", stale: "收入数据已超过允许的更新时间范围，刷新后才会开放购买力判断。" },
    position: { title: "价格位置", description: "以美国价格为基准查看各地区标价差异；巨无霸数量只作生活化消费参照，不替代收入负担结论。", lowest: "最低公开价", nearBase: "接近基准", highest: "最高溢价", lowestHint: "可作为价格锚点，但仍需结合税费和账号风险。", baseHint: (c) => `${c} 作为当前基准地区。`, highestHint: "适合放入解释和风险提示，而不是推荐位。", noBigMac: "暂无当地巨无霸参照", bigMac: (n, r) => `约 ${n} 个巨无霸${r ? " · 欧元区参照" : ""}`, chartTitle: "相对价格位置", chartDescription: (c) => `中线为 ${c} 基准；点越靠左越便宜，越靠右价格越高。`, lowEnd: "低价端", usBase: "美国基准", highEnd: "高价端", region: "地区", cheaper: "较低", pricier: "较高", priceDiff: "价格 / 差异", limited: (s, t) => `为避免图表拥挤，这里展示 ${s} 个代表地区；完整 ${t} 个地区仍可在上方价格明细中查看。`, source: (d) => `巨无霸价格来自 The Economist Big Mac Index（CC BY 4.0，最新观察 ${d}）。欧元区国家使用数据集提供的欧元区统一参照。` },
    matrix: { title: "价格与负担双维矩阵", description: "横轴表示相对美国的价格差，纵轴表示当地收入负担，专门识别“价格便宜但并不容易承担”的地区。", heavier: "负担更重", lowerPrice: "价格更低", higherPrice: "价格更高", quadrants: [{ title: "便宜且负担较轻", helper: "价格更低，本地收入负担不高于美国。" }, { title: "便宜但负担较重", helper: "标价更低，但当地收入承担更困难。" }, { title: "较贵但负担较轻", helper: "标价较高，但当地收入减轻了实际压力。" }, { title: "较贵且负担较重", helper: "标价和当地收入负担都高于美国基准。" }], note: "双维视图不会把价格和收入合成为一个不透明分数；每个点仍保留两项原始指标。", pointTitle: (c, d, b) => `${c}：价格差 ${d}，收入负担为美国的 ${b} 倍`, ariaLabel: "各地区相对美国价格差与收入负担散点图" },
  },
  "zh-tw": {
    title: (p) => `${p} 價格與購買力`, description: "分開查看地區標價、當地收入負擔，以及兩者是否一致。", tabs: { price: "價格位置", burden: "收入負擔", matrix: "雙維判斷" },
    pending: { generic: "收入負擔資料未通過完整性檢查，目前不會用價格差冒充購買力結論。", noRows: "收入資料尚未與目前 App Store 價格形成可發布結果。", coverage: (c, p) => `目前收入資料覆蓋 ${c}/${p} 個價格地區，未達 80% 發布門檻。`, noUs: "缺少美國收入負擔基準，暫時無法計算跨區相對負擔。", stale: "收入資料已過期，更新後才會開放購買力判斷。" },
    position: { title: "價格位置", description: "以美國價格為基準查看各地區標價差異；大麥克數量僅作生活化參照。", lowest: "最低公開價", nearBase: "接近基準", highest: "最高溢價", lowestHint: "可作為價格錨點，但仍需考量稅費與帳號風險。", baseHint: (c) => `${c} 為目前基準地區。`, highestHint: "用於解釋與風險提示，而不是推薦。", noBigMac: "暫無當地大麥克參照", bigMac: (n, r) => `約 ${n} 個大麥克${r ? " · 歐元區參照" : ""}`, chartTitle: "相對價格位置", chartDescription: (c) => `中線為 ${c} 基準；左側較便宜，右側較昂貴。`, lowEnd: "低價端", usBase: "美國基準", highEnd: "高價端", region: "地區", cheaper: "較低", pricier: "較高", priceDiff: "價格 / 差異", limited: (s, t) => `為避免擁擠，顯示 ${s} 個代表地區；完整 ${t} 個地區請見上方明細。`, source: (d) => `大麥克價格來自 The Economist Big Mac Index（CC BY 4.0，最新觀察 ${d}）。` },
    matrix: { title: "價格與負擔雙維矩陣", description: "橫軸為相對美國的價格差，縱軸為當地收入負擔。", heavier: "負擔更重", lowerPrice: "價格更低", higherPrice: "價格更高", quadrants: [{ title: "便宜且負擔較輕", helper: "價格較低，收入負擔不高於美國。" }, { title: "便宜但負擔較重", helper: "標價較低，但當地收入負擔更重。" }, { title: "較貴但負擔較輕", helper: "標價較高，但收入減輕實際壓力。" }, { title: "較貴且負擔較重", helper: "價格與收入負擔都高於美國。" }], note: "不把價格與收入合成不透明分數；每個點保留兩項原始指標。", pointTitle: (c, d, b) => `${c}：價格差 ${d}，收入負擔為美國的 ${b} 倍`, ariaLabel: "各地區價格差與收入負擔散點圖" },
  },
  en: {
    title: (p) => `${p} price and affordability`, description: "View regional prices, local income burden, and whether the two signals agree.", tabs: { price: "Price position", burden: "Income burden", matrix: "Two-axis view" },
    pending: { generic: "Affordability data has not passed completeness checks; price differences are not presented as purchasing power.", noRows: "Income data has not yet produced a publishable result for current App Store prices.", coverage: (c, p) => `Income data covers ${c} of ${p} priced regions, below the 80% publication threshold.`, noUs: "The US income-burden baseline is missing, so relative burden cannot be calculated.", stale: "Income data is outside the accepted freshness window and must be refreshed." },
    position: { title: "Price position", description: "Compare listed prices against the US baseline. Big Mac equivalents are a familiar reference, not an income-burden measure.", lowest: "Lowest listed price", nearBase: "Near baseline", highest: "Highest premium", lowestHint: "A price anchor, subject to tax, account, and payment conditions.", baseHint: (c) => `${c} is the current baseline region.`, highestHint: "Useful for explanation and risk context, not as a recommendation.", noBigMac: "No local Big Mac reference", bigMac: (n, r) => `About ${n} Big Macs${r ? " · Euro-area reference" : ""}`, chartTitle: "Relative price position", chartDescription: (c) => `The center line is the ${c} baseline; farther left is cheaper and farther right is pricier.`, lowEnd: "Low-price end", usBase: "US baseline", highEnd: "High-price end", region: "Region", cheaper: "Lower", pricier: "Higher", priceDiff: "Price / difference", limited: (s, t) => `Showing ${s} representative regions to avoid crowding; all ${t} remain available in the price table above.`, source: (d) => `Big Mac prices: The Economist Big Mac Index (CC BY 4.0; latest observation ${d}).` },
    matrix: { title: "Price and burden matrix", description: "The horizontal axis shows price difference versus the US; the vertical axis shows local income burden.", heavier: "Heavier burden", lowerPrice: "Lower price", higherPrice: "Higher price", quadrants: [{ title: "Cheaper, lighter burden", helper: "Lower price and no heavier than the US income burden." }, { title: "Cheaper, heavier burden", helper: "Lower sticker price, but harder to afford locally." }, { title: "Pricier, lighter burden", helper: "Higher price, offset by stronger local income." }, { title: "Pricier, heavier burden", helper: "Both price and local burden exceed the US baseline." }], note: "The view does not combine price and income into an opaque score; both original measures remain visible.", pointTitle: (c, d, b) => `${c}: price difference ${d}, income burden ${b}× the US`, ariaLabel: "Scatter plot of regional price differences and income burden versus the US" },
  },
  ja: {
    title: (p) => `${p} の価格と購買力`, description: "地域価格、現地所得への負担、両者の一致を分けて確認します。", tabs: { price: "価格位置", burden: "所得負担", matrix: "2軸分析" }, pending: { generic: "所得データが完全性チェックを通過していないため、価格差を購買力として表示しません。", noRows: "現在のApp Store価格に対する公開可能な所得負担結果がありません。", coverage: (c, p) => `所得データは ${p} 地域中 ${c} 地域をカバーし、公開基準80%未満です。`, noUs: "米国の所得負担基準がありません。", stale: "所得データが古いため更新が必要です。" },
    position: { title: "価格位置", description: "米国価格を基準に比較します。ビッグマック換算は身近な参考値で、所得負担そのものではありません。", lowest: "最低公開価格", nearBase: "基準付近", highest: "最高プレミアム", lowestHint: "税、アカウント、支払条件も確認してください。", baseHint: (c) => `${c} を現在の基準地域とします。`, highestHint: "推奨ではなく、説明とリスク把握に使用します。", noBigMac: "現地のビッグマック参照なし", bigMac: (n, r) => `約 ${n} 個分${r ? "・ユーロ圏参照" : ""}`, chartTitle: "相対価格位置", chartDescription: (c) => `中央線は ${c} 基準。左ほど安く、右ほど高価です。`, lowEnd: "低価格側", usBase: "米国基準", highEnd: "高価格側", region: "地域", cheaper: "低い", pricier: "高い", priceDiff: "価格 / 差", limited: (s, t) => `混雑を避けるため代表 ${s} 地域を表示。全 ${t} 地域は上の表で確認できます。`, source: (d) => `ビッグマック価格：The Economist Big Mac Index（CC BY 4.0、最新 ${d}）。` },
    matrix: { title: "価格・負担2軸マトリクス", description: "横軸は米国比の価格差、縦軸は現地所得への負担です。", heavier: "負担が重い", lowerPrice: "価格が低い", higherPrice: "価格が高い", quadrants: [{ title: "安く負担も軽い", helper: "価格が低く、所得負担も米国以下。" }, { title: "安いが負担は重い", helper: "表示価格は低いものの現地では重い負担。" }, { title: "高いが負担は軽い", helper: "価格は高いが所得が負担を緩和。" }, { title: "高く負担も重い", helper: "価格と所得負担の両方が米国超。" }], note: "価格と所得を不透明な総合点にせず、2つの元指標を保持します。", pointTitle: (c, d, b) => `${c}：価格差 ${d}、所得負担は米国の ${b} 倍`, ariaLabel: "地域価格差と所得負担の散布図" },
  },
  ko: {
    title: (p) => `${p} 가격과 구매력`, description: "지역 가격, 현지 소득 부담, 두 신호의 일치 여부를 나누어 봅니다.", tabs: { price: "가격 위치", burden: "소득 부담", matrix: "이중 축" }, pending: { generic: "소득 데이터가 완전성 검사를 통과하지 않아 가격 차이를 구매력으로 표시하지 않습니다.", noRows: "현재 App Store 가격에 대한 공개 가능한 소득 부담 결과가 없습니다.", coverage: (c, p) => `소득 데이터가 ${p}개 가격 지역 중 ${c}개를 포함해 80% 기준 미만입니다.`, noUs: "미국 소득 부담 기준이 없습니다.", stale: "소득 데이터가 오래되어 갱신이 필요합니다." },
    position: { title: "가격 위치", description: "미국 가격을 기준으로 비교합니다. 빅맥 환산은 친숙한 참고값이며 소득 부담 지표가 아닙니다.", lowest: "최저 공개 가격", nearBase: "기준 근처", highest: "최고 프리미엄", lowestHint: "세금, 계정 및 결제 조건도 확인해야 합니다.", baseHint: (c) => `${c}을 현재 기준 지역으로 사용합니다.`, highestHint: "추천이 아닌 설명과 위험 문맥에 사용합니다.", noBigMac: "현지 빅맥 기준 없음", bigMac: (n, r) => `빅맥 약 ${n}개${r ? " · 유로존 기준" : ""}`, chartTitle: "상대 가격 위치", chartDescription: (c) => `중앙선은 ${c} 기준이며 왼쪽이 저렴하고 오른쪽이 비쌉니다.`, lowEnd: "저가 구간", usBase: "미국 기준", highEnd: "고가 구간", region: "지역", cheaper: "낮음", pricier: "높음", priceDiff: "가격 / 차이", limited: (s, t) => `혼잡을 줄이기 위해 대표 ${s}개 지역을 표시합니다. 전체 ${t}개는 위 표에서 확인할 수 있습니다.`, source: (d) => `빅맥 가격: The Economist Big Mac Index(CC BY 4.0, 최신 ${d}).` },
    matrix: { title: "가격·부담 이중 축 매트릭스", description: "가로축은 미국 대비 가격 차이, 세로축은 현지 소득 부담입니다.", heavier: "부담 증가", lowerPrice: "가격 낮음", higherPrice: "가격 높음", quadrants: [{ title: "저렴하고 부담도 낮음", helper: "가격이 낮고 소득 부담도 미국 이하입니다." }, { title: "저렴하지만 부담은 높음", helper: "표시 가격은 낮지만 현지에서 감당하기 어렵습니다." }, { title: "비싸지만 부담은 낮음", helper: "가격은 높지만 현지 소득이 부담을 줄입니다." }, { title: "비싸고 부담도 높음", helper: "가격과 소득 부담 모두 미국보다 높습니다." }], note: "가격과 소득을 불투명한 단일 점수로 합치지 않고 두 원지표를 유지합니다.", pointTitle: (c, d, b) => `${c}: 가격 차이 ${d}, 소득 부담 미국의 ${b}배`, ariaLabel: "지역 가격 차이와 소득 부담 산점도" },
  },
  es: {
    title: (p) => `Precio y asequibilidad de ${p}`, description: "Compara el precio regional, la carga sobre los ingresos y si ambas señales coinciden.", tabs: { price: "Posición de precio", burden: "Carga de ingresos", matrix: "Vista de dos ejes" }, pending: { generic: "Los datos de ingresos no superaron la comprobación de integridad; la diferencia de precio no se presenta como poder adquisitivo.", noRows: "Aún no hay un resultado publicable para los precios actuales de App Store.", coverage: (c, p) => `Los ingresos cubren ${c} de ${p} regiones, por debajo del umbral del 80 %.`, noUs: "Falta la referencia de carga de Estados Unidos.", stale: "Los datos de ingresos deben actualizarse." },
    position: { title: "Posición de precio", description: "Compara precios con EE. UU. Los Big Macs son una referencia cotidiana, no una medida de carga sobre ingresos.", lowest: "Precio mínimo", nearBase: "Cerca de la base", highest: "Mayor sobreprecio", lowestHint: "Referencia sujeta a impuestos, cuenta y condiciones de pago.", baseHint: (c) => `${c} es la región de referencia.`, highestHint: "Sirve para explicar riesgos, no como recomendación.", noBigMac: "Sin referencia local de Big Mac", bigMac: (n, r) => `Unos ${n} Big Macs${r ? " · referencia de la zona euro" : ""}`, chartTitle: "Posición relativa", chartDescription: (c) => `La línea central es ${c}; izquierda más barato, derecha más caro.`, lowEnd: "Extremo barato", usBase: "Base EE. UU.", highEnd: "Extremo caro", region: "Región", cheaper: "Menor", pricier: "Mayor", priceDiff: "Precio / diferencia", limited: (s, t) => `Se muestran ${s} regiones representativas; las ${t} están en la tabla superior.`, source: (d) => `Precios Big Mac: The Economist Big Mac Index (CC BY 4.0; última observación ${d}).` },
    matrix: { title: "Matriz de precio y carga", description: "El eje horizontal muestra la diferencia frente a EE. UU.; el vertical, la carga sobre ingresos locales.", heavier: "Mayor carga", lowerPrice: "Menor precio", higherPrice: "Mayor precio", quadrants: [{ title: "Más barato y menor carga", helper: "Precio menor y carga no superior a EE. UU." }, { title: "Más barato pero mayor carga", helper: "Precio menor, pero más difícil de asumir localmente." }, { title: "Más caro pero menor carga", helper: "Precio mayor compensado por ingresos locales." }, { title: "Más caro y mayor carga", helper: "Precio y carga superan la referencia estadounidense." }], note: "No combina precio e ingresos en una puntuación opaca; conserva ambas medidas.", pointTitle: (c, d, b) => `${c}: diferencia ${d}, carga ${b}× EE. UU.`, ariaLabel: "Diagrama de dispersión de precio y carga de ingresos" },
  },
  tr: {
    title: (p) => `${p} fiyatı ve satın alma gücü`, description: "Bölgesel fiyatı, yerel gelir yükünü ve iki sinyalin uyumunu ayrı ayrı görün.", tabs: { price: "Fiyat konumu", burden: "Gelir yükü", matrix: "İki eksen" }, pending: { generic: "Gelir verisi bütünlük kontrolünü geçmedi; fiyat farkı satın alma gücü olarak sunulmuyor.", noRows: "Mevcut App Store fiyatları için yayımlanabilir gelir yükü sonucu yok.", coverage: (c, p) => `Gelir verisi ${p} fiyat bölgesinin ${c} tanesini kapsıyor; %80 eşiğinin altında.`, noUs: "ABD gelir yükü temeli eksik.", stale: "Gelir verisinin yenilenmesi gerekiyor." },
    position: { title: "Fiyat konumu", description: "Fiyatları ABD temeline göre karşılaştırır. Big Mac eşdeğeri tanıdık bir referanstır, gelir yükü ölçüsü değildir.", lowest: "En düşük fiyat", nearBase: "Temele yakın", highest: "En yüksek prim", lowestHint: "Vergi, hesap ve ödeme koşulları ayrıca değerlendirilmelidir.", baseHint: (c) => `${c} mevcut temel bölgedir.`, highestHint: "Öneri değil, açıklama ve risk bağlamıdır.", noBigMac: "Yerel Big Mac referansı yok", bigMac: (n, r) => `Yaklaşık ${n} Big Mac${r ? " · Avro bölgesi referansı" : ""}`, chartTitle: "Göreli fiyat konumu", chartDescription: (c) => `Orta çizgi ${c} temelidir; sol daha ucuz, sağ daha pahalıdır.`, lowEnd: "Düşük fiyat", usBase: "ABD temeli", highEnd: "Yüksek fiyat", region: "Bölge", cheaper: "Düşük", pricier: "Yüksek", priceDiff: "Fiyat / fark", limited: (s, t) => `Kalabalığı önlemek için ${s} bölge gösteriliyor; ${t} bölgenin tamamı üst tablodadır.`, source: (d) => `Big Mac fiyatları: The Economist Big Mac Index (CC BY 4.0; son gözlem ${d}).` },
    matrix: { title: "Fiyat ve yük matrisi", description: "Yatay eksen ABD'ye göre fiyat farkını, dikey eksen yerel gelir yükünü gösterir.", heavier: "Daha ağır yük", lowerPrice: "Düşük fiyat", higherPrice: "Yüksek fiyat", quadrants: [{ title: "Ucuz ve yükü hafif", helper: "Fiyat düşük, gelir yükü ABD'den yüksek değil." }, { title: "Ucuz ama yükü ağır", helper: "Etiket düşük, yerelde karşılamak daha zor." }, { title: "Pahalı ama yükü hafif", helper: "Yüksek fiyat yerel gelirle dengeleniyor." }, { title: "Pahalı ve yükü ağır", helper: "Fiyat ve yük ABD temelini aşıyor." }], note: "Fiyat ve geliri kapalı bir puanda birleştirmez; iki ölçüyü korur.", pointTitle: (c, d, b) => `${c}: fiyat farkı ${d}, gelir yükü ABD'nin ${b} katı`, ariaLabel: "Bölgesel fiyat ve gelir yükü dağılımı" },
  },
  ar: {
    title: (p) => `سعر ${p} والقدرة الشرائية`, description: "اعرض السعر الإقليمي وعبء الدخل المحلي ومدى اتفاق المؤشرين.", tabs: { price: "موضع السعر", burden: "عبء الدخل", matrix: "عرض ثنائي المحور" }, pending: { generic: "لم تجتز بيانات الدخل فحص الاكتمال، لذلك لا يُعرض فرق السعر بوصفه قدرة شرائية.", noRows: "لا توجد نتيجة قابلة للنشر لأسعار App Store الحالية.", coverage: (c, p) => `تغطي بيانات الدخل ${c} من ${p} منطقة، دون حد النشر البالغ 80٪.`, noUs: "خط أساس عبء الدخل الأمريكي مفقود.", stale: "بيانات الدخل قديمة وتحتاج إلى تحديث." },
    position: { title: "موضع السعر", description: "مقارنة بالولايات المتحدة. مكافئ بيغ ماك مرجع مألوف وليس مقياسًا لعبء الدخل.", lowest: "أدنى سعر معلن", nearBase: "قريب من الأساس", highest: "أعلى علاوة", lowestHint: "مرجع سعري مع ضرورة مراعاة الضرائب والحساب والدفع.", baseHint: (c) => `${c} هي منطقة الأساس الحالية.`, highestHint: "للتفسير وسياق المخاطر وليس كتوصية.", noBigMac: "لا يوجد مرجع بيغ ماك محلي", bigMac: (n, r) => `نحو ${n} بيغ ماك${r ? " · مرجع منطقة اليورو" : ""}`, chartTitle: "الموضع السعري النسبي", chartDescription: (c) => `الخط الأوسط هو أساس ${c}؛ اليسار أرخص واليمين أغلى.`, lowEnd: "الطرف الأرخص", usBase: "أساس الولايات المتحدة", highEnd: "الطرف الأغلى", region: "المنطقة", cheaper: "أقل", pricier: "أعلى", priceDiff: "السعر / الفرق", limited: (s, t) => `نعرض ${s} مناطق لتجنب الازدحام؛ جميع المناطق وعددها ${t} في الجدول أعلاه.`, source: (d) => `أسعار بيغ ماك: The Economist Big Mac Index ‏(CC BY 4.0؛ أحدث رصد ${d}).` },
    matrix: { title: "مصفوفة السعر والعبء", description: "المحور الأفقي فرق السعر عن الولايات المتحدة، والرأسي عبء الدخل المحلي.", heavier: "عبء أكبر", lowerPrice: "سعر أقل", higherPrice: "سعر أعلى", quadrants: [{ title: "أرخص وعبء أخف", helper: "سعر أقل وعبء لا يتجاوز الولايات المتحدة." }, { title: "أرخص لكن العبء أكبر", helper: "السعر أقل لكن تحمله محليًا أصعب." }, { title: "أغلى لكن العبء أخف", helper: "السعر أعلى ويخففه الدخل المحلي." }, { title: "أغلى وعبء أكبر", helper: "السعر والعبء أعلى من الأساس الأمريكي." }], note: "لا يدمج السعر والدخل في درجة مبهمة؛ يبقي المؤشرين الأصليين.", pointTitle: (c, d, b) => `${c}: فرق السعر ${d}، عبء الدخل ${b}× الولايات المتحدة`, ariaLabel: "مخطط مبعثر لفرق السعر وعبء الدخل" },
  },
  fr: {
    title: (p) => `Prix et pouvoir d’achat de ${p}`, description: "Comparez le prix régional, la charge sur le revenu et la cohérence des deux signaux.", tabs: { price: "Position du prix", burden: "Charge sur le revenu", matrix: "Vue à deux axes" }, pending: { generic: "Les données de revenu n’ont pas passé les contrôles; l’écart de prix n’est pas présenté comme pouvoir d’achat.", noRows: "Aucun résultat publiable pour les prix App Store actuels.", coverage: (c, p) => `Les revenus couvrent ${c} régions sur ${p}, sous le seuil de 80 %.`, noUs: "La base de revenu américaine manque.", stale: "Les données de revenu doivent être actualisées." },
    position: { title: "Position du prix", description: "Comparaison avec les États-Unis. L’équivalent Big Mac est un repère courant, pas une mesure de revenu.", lowest: "Prix public le plus bas", nearBase: "Près de la base", highest: "Prime la plus élevée", lowestHint: "Repère soumis aux taxes et conditions de compte et paiement.", baseHint: (c) => `${c} est la région de référence.`, highestHint: "Contexte explicatif et de risque, pas une recommandation.", noBigMac: "Pas de repère Big Mac local", bigMac: (n, r) => `Environ ${n} Big Macs${r ? " · référence zone euro" : ""}`, chartTitle: "Position relative", chartDescription: (c) => `La ligne centrale représente ${c}; à gauche moins cher, à droite plus cher.`, lowEnd: "Prix bas", usBase: "Base États-Unis", highEnd: "Prix élevé", region: "Région", cheaper: "Moins", pricier: "Plus", priceDiff: "Prix / écart", limited: (s, t) => `${s} régions représentatives sont affichées; les ${t} figurent dans le tableau ci-dessus.`, source: (d) => `Prix Big Mac : The Economist Big Mac Index (CC BY 4.0 ; dernière observation ${d}).` },
    matrix: { title: "Matrice prix et charge", description: "L’axe horizontal montre l’écart de prix avec les États-Unis; le vertical, la charge sur le revenu local.", heavier: "Charge plus forte", lowerPrice: "Prix plus bas", higherPrice: "Prix plus haut", quadrants: [{ title: "Moins cher, charge plus légère", helper: "Prix plus bas et charge non supérieure aux États-Unis." }, { title: "Moins cher, charge plus forte", helper: "Prix facial inférieur, mais plus difficile à assumer localement." }, { title: "Plus cher, charge plus légère", helper: "Prix supérieur compensé par le revenu local." }, { title: "Plus cher, charge plus forte", helper: "Prix et charge dépassent la base américaine." }], note: "La vue ne fusionne pas prix et revenu en un score opaque; elle conserve les deux mesures.", pointTitle: (c, d, b) => `${c} : écart ${d}, charge ${b}× les États-Unis`, ariaLabel: "Nuage de points des prix et charges sur le revenu" },
  },
  it: {
    title: (p) => `Prezzo e potere d’acquisto di ${p}`, description: "Confronta prezzo regionale, peso sul reddito e coerenza dei due segnali.", tabs: { price: "Posizione prezzo", burden: "Peso sul reddito", matrix: "Vista a due assi" }, pending: { generic: "I dati sul reddito non hanno superato i controlli; la differenza di prezzo non viene presentata come potere d’acquisto.", noRows: "Nessun risultato pubblicabile per i prezzi App Store correnti.", coverage: (c, p) => `I redditi coprono ${c} regioni su ${p}, sotto la soglia dell’80%.`, noUs: "Manca la base statunitense.", stale: "I dati sul reddito devono essere aggiornati." },
    position: { title: "Posizione prezzo", description: "Confronto con gli Stati Uniti. L’equivalente Big Mac è un riferimento quotidiano, non una misura del reddito.", lowest: "Prezzo minimo", nearBase: "Vicino alla base", highest: "Sovrapprezzo massimo", lowestHint: "Riferimento soggetto a tasse e condizioni di account e pagamento.", baseHint: (c) => `${c} è la regione base.`, highestHint: "Contesto esplicativo e di rischio, non una raccomandazione.", noBigMac: "Nessun riferimento Big Mac locale", bigMac: (n, r) => `Circa ${n} Big Mac${r ? " · riferimento area euro" : ""}`, chartTitle: "Posizione relativa", chartDescription: (c) => `La linea centrale è ${c}; a sinistra più economico, a destra più costoso.`, lowEnd: "Fascia bassa", usBase: "Base USA", highEnd: "Fascia alta", region: "Regione", cheaper: "Meno", pricier: "Più", priceDiff: "Prezzo / differenza", limited: (s, t) => `Mostrate ${s} regioni rappresentative; tutte le ${t} sono nella tabella sopra.`, source: (d) => `Prezzi Big Mac: The Economist Big Mac Index (CC BY 4.0; ultima osservazione ${d}).` },
    matrix: { title: "Matrice prezzo e peso", description: "L’asse orizzontale mostra la differenza dagli USA; quello verticale il peso sul reddito locale.", heavier: "Peso maggiore", lowerPrice: "Prezzo minore", higherPrice: "Prezzo maggiore", quadrants: [{ title: "Più economico e leggero", helper: "Prezzo inferiore e peso non superiore agli USA." }, { title: "Più economico ma più pesante", helper: "Prezzo inferiore, ma più difficile da sostenere localmente." }, { title: "Più caro ma più leggero", helper: "Prezzo superiore compensato dal reddito locale." }, { title: "Più caro e più pesante", helper: "Prezzo e peso superano la base USA." }], note: "Non combina prezzo e reddito in un punteggio opaco; mantiene entrambe le misure.", pointTitle: (c, d, b) => `${c}: differenza ${d}, peso ${b}× USA`, ariaLabel: "Grafico a dispersione di prezzo e peso sul reddito" },
  },
  de: {
    title: (p) => `Preis und Kaufkraft von ${p}`, description: "Regionale Preise, lokale Einkommensbelastung und die Übereinstimmung beider Signale getrennt betrachten.", tabs: { price: "Preisposition", burden: "Einkommenslast", matrix: "Zwei-Achsen-Sicht" }, pending: { generic: "Die Einkommensdaten haben die Vollständigkeitsprüfung nicht bestanden; Preisunterschiede werden nicht als Kaufkraft ausgegeben.", noRows: "Für aktuelle App-Store-Preise liegt kein veröffentlichbares Ergebnis vor.", coverage: (c, p) => `Einkommensdaten decken ${c} von ${p} Regionen ab und liegen unter 80 %.`, noUs: "Die US-Einkommensbasis fehlt.", stale: "Die Einkommensdaten müssen aktualisiert werden." },
    position: { title: "Preisposition", description: "Vergleich mit den USA. Big-Mac-Äquivalente sind ein Alltagsvergleich, keine Einkommenskennzahl.", lowest: "Niedrigster Listenpreis", nearBase: "Nahe der Basis", highest: "Höchster Aufpreis", lowestHint: "Preisanker unter Vorbehalt von Steuern, Konto- und Zahlungsbedingungen.", baseHint: (c) => `${c} ist die aktuelle Basisregion.`, highestHint: "Zur Erklärung und Risikoeinordnung, nicht als Empfehlung.", noBigMac: "Keine lokale Big-Mac-Referenz", bigMac: (n, r) => `Etwa ${n} Big Macs${r ? " · Eurozonen-Referenz" : ""}`, chartTitle: "Relative Preisposition", chartDescription: (c) => `Die Mittellinie ist ${c}; links günstiger, rechts teurer.`, lowEnd: "Niedrigpreis", usBase: "US-Basis", highEnd: "Hochpreis", region: "Region", cheaper: "Niedriger", pricier: "Höher", priceDiff: "Preis / Differenz", limited: (s, t) => `${s} repräsentative Regionen werden gezeigt; alle ${t} stehen in der Tabelle oben.`, source: (d) => `Big-Mac-Preise: The Economist Big Mac Index (CC BY 4.0; letzte Beobachtung ${d}).` },
    matrix: { title: "Preis- und Belastungsmatrix", description: "Horizontal: Preisunterschied zu den USA. Vertikal: lokale Einkommensbelastung.", heavier: "Höhere Belastung", lowerPrice: "Niedriger Preis", higherPrice: "Höherer Preis", quadrants: [{ title: "Günstiger, leichtere Last", helper: "Niedrigerer Preis und keine höhere Last als in den USA." }, { title: "Günstiger, aber schwerere Last", helper: "Niedrigerer Preis, lokal dennoch schwerer tragbar." }, { title: "Teurer, aber leichtere Last", helper: "Höherer Preis wird durch lokales Einkommen abgefedert." }, { title: "Teurer und schwerere Last", helper: "Preis und Last liegen über der US-Basis." }], note: "Preis und Einkommen werden nicht zu einem undurchsichtigen Score vermischt; beide Messwerte bleiben erhalten.", pointTitle: (c, d, b) => `${c}: Preisdifferenz ${d}, Belastung ${b}× USA`, ariaLabel: "Streudiagramm für Preisunterschied und Einkommensbelastung" },
  },
  pt: {
    title: (p) => `Preço e poder de compra de ${p}`, description: "Compare o preço regional, o peso no rendimento e se os dois sinais coincidem.", tabs: { price: "Posição do preço", burden: "Peso no rendimento", matrix: "Vista de dois eixos" }, pending: { generic: "Os dados de rendimento não passaram a verificação; a diferença de preço não é apresentada como poder de compra.", noRows: "Ainda não há resultado publicável para os preços atuais da App Store.", coverage: (c, p) => `Os rendimentos cobrem ${c} de ${p} regiões, abaixo do limite de 80%.`, noUs: "Falta a base de rendimento dos EUA.", stale: "Os dados de rendimento precisam de atualização." },
    position: { title: "Posição do preço", description: "Comparação com os EUA. O equivalente Big Mac é uma referência quotidiana, não uma medida de rendimento.", lowest: "Preço mínimo", nearBase: "Perto da base", highest: "Maior prémio", lowestHint: "Referência sujeita a impostos e condições de conta e pagamento.", baseHint: (c) => `${c} é a região base.`, highestHint: "Contexto explicativo e de risco, não uma recomendação.", noBigMac: "Sem referência Big Mac local", bigMac: (n, r) => `Cerca de ${n} Big Macs${r ? " · referência da zona euro" : ""}`, chartTitle: "Posição relativa", chartDescription: (c) => `A linha central é ${c}; à esquerda mais barato, à direita mais caro.`, lowEnd: "Preço baixo", usBase: "Base EUA", highEnd: "Preço alto", region: "Região", cheaper: "Menor", pricier: "Maior", priceDiff: "Preço / diferença", limited: (s, t) => `São mostradas ${s} regiões representativas; as ${t} estão na tabela acima.`, source: (d) => `Preços Big Mac: The Economist Big Mac Index (CC BY 4.0; última observação ${d}).` },
    matrix: { title: "Matriz de preço e peso", description: "O eixo horizontal mostra a diferença face aos EUA; o vertical, o peso no rendimento local.", heavier: "Peso maior", lowerPrice: "Preço menor", higherPrice: "Preço maior", quadrants: [{ title: "Mais barato e mais leve", helper: "Preço menor e peso não superior aos EUA." }, { title: "Mais barato mas mais pesado", helper: "Preço menor, mas mais difícil de suportar localmente." }, { title: "Mais caro mas mais leve", helper: "Preço maior compensado pelo rendimento local." }, { title: "Mais caro e mais pesado", helper: "Preço e peso superam a base dos EUA." }], note: "Não combina preço e rendimento numa pontuação opaca; mantém as duas medidas.", pointTitle: (c, d, b) => `${c}: diferença ${d}, peso ${b}× EUA`, ariaLabel: "Gráfico de dispersão de preço e peso no rendimento" },
  },
} satisfies Record<SiteLocale, PricingPressureCopy>;

export function getPricingPressureCopy(locale: SiteLocale) {
  return copies[locale];
}
