import type { SiteLocale } from "./site-locale";

const publicPricingCopy = {
  zh: {
    listing: {
      pages: {
        ai: {
          eyebrow: "GeoSub AI 价格数据",
          title: "AI 订阅价格对比",
          description:
            "比较 ChatGPT、Claude、Gemini 等 AI 工具在不同地区的订阅价格，查看最低价地区、高价地区、税费说明和价格差距。",
          metaTitle: "AI 订阅价格对比 - ChatGPT、Claude、Gemini 全球价格",
          metaDescription:
            "比较 ChatGPT、Claude、Gemini 等 AI 订阅在不同国家和地区的 App Store 价格、美元折算、人民币估算、税费说明和价格差异。",
        },
        streaming: {
          eyebrow: "GeoSub 流媒体价格数据",
          title: "流媒体订阅价格对比",
          description:
            "比较 Netflix、YouTube Premium、Spotify、Disney+ 等流媒体服务在不同地区的订阅价格。数据覆盖完善后会逐步开放更多产品。",
          metaTitle:
            "流媒体订阅价格对比 - Netflix、YouTube Premium、Spotify 全球价格",
          metaDescription:
            "比较 Netflix、YouTube Premium、Spotify、Disney+ 等流媒体订阅在不同国家和地区的价格、税费和区域价格差异。",
        },
      },
      categoryAria: "数字服务分类",
      aiLabel: "AI 订阅",
      aiDescription:
        "比较 ChatGPT、Claude、Gemini、Grok 等 AI 产品在不同国家和地区的价格。",
      streamingLabel: "流媒体",
      streamingDescription:
        "比较 Netflix、YouTube Premium、Spotify、Disney+ 等流媒体和数字娱乐订阅价格。",
      productCount: (count: number) => `当前收录 ${count} 个产品`,
      empty: "当前分类暂无已发布价格数据。",
      defaultPlanHint: "默认展示主流月付套餐",
      card: {
        titleSuffix: "各地区定价",
        region: "地区",
        price: "价格",
        tax: "税费说明",
        base: "基准",
        updated: "更新时间",
        spread: "价差",
        regions: "个地区",
        detail: "查看详情",
        highest: "最高价",
        lowest: "最低价",
        monthlySuffix: "/月",
        yearlySuffix: "/年",
        weeklySuffix: "/周",
        taxInferred: "平台推断",
        taxVerified: "高可信",
        taxMedium: "中可信",
        taxNeedsReview: "待复核",
        taxUnverified: "待核验",
        checkoutApplies: "结算页为准",
      },
    },
    navigation: {
      products: "产品总览",
      currentProduct: "当前产品",
      ai: "AI 订阅",
      streaming: "流媒体",
      other: "其他",
    },
    pricing: {
      appStoreSource: "价格来源：App Store",
      conclusionTitle: (planName: string) => `${planName} 全球价格结论`,
      conclusion: (source: string, lowest: string, highest: string, spread: number) =>
        `当前以 ${source} 正式价格比较，${lowest} 最便宜；${highest} 最贵，价差约 ${spread}%。`,
      conclusionLead: (source: string, country: string) =>
        `当前以 ${source} 正式价格比较，${country} 最便宜，约`,
      conclusionMiddle: (country: string) => `；${country} 最贵，约`,
      conclusionSpread: (spread: number) => `，价差约 ${spread}%。`,
      pageUpdated: (date: string) => `页面更新：${date}`,
      regionCount: (count: number) => `${count} 个地区`,
      displayCurrency: "显示币种",
      officialWebPricing: "官网价格",
      allDiagnosticSources: "全部价格来源",
      allSources: "全部来源",
      webLead: "官网价格",
      googlePlayLead: "Google Play 价格",
      allDiagnostics: "其他来源",
      cnyLabel: "人民币 CNY",
      usdLabel: "美元 USD",
      monthlySuffix: "/月",
      cnyUnavailable: "人民币估算暂不可用：汇率待同步",
      cnyStale: "人民币估算暂停：汇率同步已过期",
      synced: (date: string) => `同步 ${date}`,
      rateBasis: (date: string) => `汇率基准 ${date}`,
      cnyRate: (rate: number) => `人民币按 ${rate.toFixed(4)} 汇率估算`,
      lowest: "最低价",
      highest: "最高价",
      usBase: "美国基准",
      regions: "覆盖地区",
      source: "数据来源",
      latestCollection: "最近采集",
      fxBasis: "汇率基准",
      planReview: "套餐复核",
      trustStatus: "可信状态",
      verified: "高可信",
      reviewed: "已复核",
      needsReview: "待复核",
      unavailable: "暂无",
      distributionEyebrow: "价格分布",
      distributionTitle: "全球价格分布与地区排行",
      distributionDescription: (productName: string) =>
        `地图用于快速理解 ${productName} 的全球价格差异；榜单用于辅助定位低价区和高价区。`,
      lowerRegions: "更便宜的地区",
      higherRegions: "更贵的地区",
      noPrices: (source: string) => `暂无 ${source} 价格数据`,
      noPricesDescription:
        "该来源暂无可用于比较的已复核价格，因此暂不显示价格分布、地区排行和明细表。",
    },
    table: {
      eyebrow: "地区价格",
      title: (planName: string) => `${planName} 地区价格明细`,
      description: (source: string, currency: string) =>
        `价格来源：${source}。按${currency}从低到高排序。`,
      regionCount: (count: number) => `${count} 个地区`,
      allSources: "全部来源",
      webLead: "官网价格",
      googlePlayLead: "Google Play 价格",
      allDiagnostics: "其他来源",
      usd: "美元 USD",
      usdEquivalent: "美元折算",
      usdSort: "美元折算价",
      cnyEstimate: "人民币折算",
      cnySort: "人民币折算价",
      perMonth: "/月",
      rank: "排名",
      region: "地区",
      localPrice: "本地价格",
      vsUs: "对比美国",
      taxNote: "税费说明",
      source: "来源",
      statusRisk: "状态/风险",
      sameAsUs: "与美国相同",
      aboveUs: (percent: number) => `比美国贵 ${percent}%`,
      belowUs: (percent: number) => `比美国便宜 ${percent}%`,
      statusLow: "低价",
      statusHigh: "高价",
      statusAbove: "偏高",
      statusBase: "基准",
      riskLow: "低",
      riskMedium: "中",
      riskHigh: "高",
      riskNeedsReview: "待核验",
      riskPrefix: (label: string) => `风险${label}`,
      riskFallback: "跨区订阅可能受账号地区、付款方式和平台风控影响。",
      taxInferred: "平台推断",
      taxVerified: "高可信",
      taxMedium: "中可信",
      taxNeedsReview: "待复核",
      taxUnverified: "待核验",
      checkoutApplies: "结算页为准",
      taxVerifiedHelp: "税务资料来自国家税务资料库，高可信。",
      taxInferredHelp:
        "系统根据 App Store 平台结算逻辑生成说明；具体税率仍以官方结算页为准。",
      taxMediumHelp: "税务资料来自国家或地区税务资料库，仍需定期复核。",
      taxUnverifiedHelp: "该地区税务资料尚未核验，最终以结算页为准。",
      taxRankingPolicy:
        "GeoSub 不把税率额外加入采集价格；价格排序使用 App Store 标价折算。",
      priceCollected: "价格采集",
      fxBasis: "采集汇率基准",
      convertedHelp: "把本地价格按汇率折算成统一货币，方便横向比较。",
      vsUsHelp: "以美国地区价格为基准，显示该地区便宜或贵多少。",
      taxHelp:
        "当地 VAT、GST、消费税或销售税说明，仅作背景参考；价格排序不额外加税，最终以 App Store 结算页为准。",
      riskHelp:
        "状态表示该地区价格相对美国是低价、基准、偏高或高价；风险表示跨区订阅时账号地区、付款方式、账单信息和平台风控的综合判断。",
      empty: (source: string) => `暂无 ${source} 价格数据。`,
      showMore: (count: number) => `显示更多 ${count} 个地区`,
      collapse: "收起地区列表",
      riskNote:
        "风险提示：GeoSub 展示公开价格差异，方便比较不同地区的订阅成本，不鼓励规避平台规则。跨地区订阅可能受到 Apple ID 地区、付款方式、账单信息、税费和平台风控影响，最终是否可订阅请以官方结算页面为准。",
      helpAria: (label: string, help: string) => `${label}说明：${help}`,
    },
  },
  en: {
    listing: {
      pages: {
        ai: {
          eyebrow: "GeoSub AI Pricing Data",
          title: "AI Subscription Pricing",
          description:
            "Compare ChatGPT, Claude, Gemini and other AI tools across countries and regions, including local prices, USD equivalents, tax notes and regional price differences.",
          metaTitle:
            "AI Subscription Pricing - ChatGPT, Claude, Gemini Global Prices",
          metaDescription:
            "Compare ChatGPT, Claude, Gemini and other AI subscription prices across countries and regions, including App Store prices, USD equivalents, tax notes and regional price differences.",
        },
        streaming: {
          eyebrow: "GeoSub Streaming Pricing Data",
          title: "Streaming Subscription Pricing",
          description:
            "Compare Netflix, YouTube Premium, Spotify, Disney+ and other streaming services across countries and regions. More products will be opened after data coverage improves.",
          metaTitle:
            "Streaming Subscription Pricing - Netflix, YouTube Premium, Spotify",
          metaDescription:
            "Compare Netflix, YouTube Premium, Spotify, Disney+ and other streaming subscription prices across countries and regions.",
        },
      },
      categoryAria: "Digital service category",
      aiLabel: "AI Subscriptions",
      aiDescription:
        "Compare ChatGPT, Claude, Gemini, Grok and other AI subscription prices across countries and regions.",
      streamingLabel: "Streaming",
      streamingDescription:
        "Compare Netflix, YouTube Premium, Spotify, Disney+ and other digital entertainment subscription prices.",
      productCount: (count: number) => `Currently tracking ${count} products`,
      empty: "No published pricing data is available for this category yet.",
      defaultPlanHint: "Popular monthly plan shown by default",
      card: {
        titleSuffix: "Regional Pricing",
        region: "Region",
        price: "Price",
        tax: "Tax note",
        base: "Base",
        updated: "Updated",
        spread: "price spread",
        regions: "regions",
        detail: "View details",
        highest: "Highest",
        lowest: "Lowest",
        monthlySuffix: "/mo",
        yearlySuffix: "/yr",
        weeklySuffix: "/wk",
        taxInferred: "Platform inferred",
        taxVerified: "Verified",
        taxMedium: "Medium",
        taxNeedsReview: "Needs review",
        taxUnverified: "Unverified",
        checkoutApplies: "Checkout applies",
      },
    },
    navigation: {
      products: "Products",
      currentProduct: "Current product",
      ai: "AI Subscriptions",
      streaming: "Streaming",
      other: "Other",
    },
    pricing: {
      appStoreSource: "Price source: App Store",
      conclusionTitle: (planName: string) => `${planName} global price conclusion`,
      conclusion: (source: string, lowest: string, highest: string, spread: number) =>
        `Based on official ${source} pricing, ${lowest} is currently the cheapest; ${highest} is the most expensive, with a spread of about ${spread}%.`,
      conclusionLead: (source: string, country: string) =>
        `Based on official ${source} pricing, ${country} is currently the cheapest at about`,
      conclusionMiddle: (country: string) =>
        `; ${country} is the most expensive at about`,
      conclusionSpread: (spread: number) =>
        `, with a spread of about ${spread}%.`,
      pageUpdated: (date: string) => `Page updated: ${date}`,
      regionCount: (count: number) => `${count} regions`,
      displayCurrency: "Display currency",
      officialWebPricing: "official web pricing",
      allDiagnosticSources: "all price sources",
      allSources: "all sources",
      cnyLabel: "CNY estimate",
      usdLabel: "USD",
      monthlySuffix: "/mo",
      cnyUnavailable: "CNY estimate unavailable: exchange-rate sync is pending",
      cnyStale: "CNY estimate paused: exchange-rate sync is stale",
      synced: (date: string) => `synced ${date}`,
      rateBasis: (date: string) => `rate basis ${date}`,
      cnyRate: (rate: number) => `CNY uses ${rate.toFixed(4)} USD/CNY`,
      lowest: "Lowest",
      highest: "Highest",
      usBase: "US base",
      regions: "Regions",
      source: "Source",
      latestCollection: "Latest collection",
      fxBasis: "FX basis",
      planReview: "Plan review",
      trustStatus: "Trust status",
      verified: "Verified",
      reviewed: "Reviewed",
      needsReview: "Needs review",
      unavailable: "Not available",
      distributionEyebrow: "Price distribution",
      distributionTitle: "Global price distribution and regional ranking",
      distributionDescription: (productName: string) =>
        `The map explains ${productName} regional price differences; the lists highlight lower-price and higher-price regions.`,
      lowerRegions: "Lower-price regions",
      higherRegions: "Higher-price regions",
      noPrices: (source: string) => `No ${source} pricing yet`,
      noPricesDescription:
        "This source does not currently have enough reviewed prices for comparison, so the distribution, ranking and detail table are not shown.",
    },
    table: {
      eyebrow: "Region prices",
      title: (planName: string) => `${planName} regional price details`,
      description: (source: string, currency: string) =>
        `Price source: ${source}. Sorted by ${currency} from low to high.`,
      regionCount: (count: number) => `${count} regions`,
      allSources: "All sources",
      webLead: "Official web price",
      googlePlayLead: "Google Play price",
      allDiagnostics: "Other sources",
      usd: "USD",
      usdEquivalent: "USD equivalent",
      usdSort: "USD equivalent",
      cnyEstimate: "CNY estimate",
      cnySort: "CNY estimate",
      perMonth: "/mo",
      rank: "Rank",
      region: "Region",
      localPrice: "Local price",
      vsUs: "vs US",
      taxNote: "Tax note",
      source: "Source",
      statusRisk: "Status / risk",
      sameAsUs: "Same as US",
      aboveUs: (percent: number) => `${percent}% above US`,
      belowUs: (percent: number) => `${percent}% below US`,
      statusLow: "Low",
      statusHigh: "High",
      statusAbove: "Above",
      statusBase: "Base",
      riskLow: "low",
      riskMedium: "medium",
      riskHigh: "high",
      riskNeedsReview: "needs review",
      riskPrefix: (label: string) => `Risk ${label}`,
      riskFallback:
        "Cross-region subscriptions may be affected by account region, payment method and platform risk controls.",
      taxInferred: "Platform inferred",
      taxVerified: "Verified",
      taxMedium: "Medium confidence",
      taxNeedsReview: "Needs review",
      taxUnverified: "Unverified",
      checkoutApplies: "Checkout applies",
      taxVerifiedHelp: "Tax profile comes from the country tax database and is verified.",
      taxInferredHelp:
        "Generated from App Store billing assumptions; final checkout remains authoritative.",
      taxMediumHelp:
        "Tax profile comes from country or regional tax data and needs periodic review.",
      taxUnverifiedHelp:
        "Tax profile is not verified yet; final checkout remains authoritative.",
      taxRankingPolicy:
        "GeoSub does not add tax again; rankings use the App Store list price converted to USD.",
      priceCollected: "Price collected",
      fxBasis: "FX basis",
      convertedHelp: "Converts local prices into a common currency for comparison.",
      vsUsHelp: "Uses the US price as the baseline and shows how much cheaper or more expensive each region is.",
      taxHelp:
        "VAT, GST, consumption tax or sales tax notes are contextual only. Rankings do not add tax again; final App Store checkout remains authoritative.",
      riskHelp:
        "Status compares each region against the US baseline. Risk reflects account region, payment method, billing information and platform controls.",
      empty: (source: string) => `No ${source} pricing is available yet.`,
      showMore: (count: number) => `Show ${count} more regions`,
      collapse: "Collapse regions",
      riskNote:
        "Risk note: GeoSub presents public price differences to compare regional subscription costs and does not encourage bypassing platform rules. Cross-region subscriptions may be affected by Apple ID region, payment method, billing information, taxes and platform risk controls. Final availability depends on the official checkout page.",
      helpAria: (label: string, help: string) => `${label}: ${help}`,
    },
  },
} satisfies Record<SiteLocale, object>;

export function getPublicPricingCopy(locale: SiteLocale) {
  return publicPricingCopy[locale];
}
