

type LegacyPublicPricingLocale = "zh" | "zh-tw" | "en";

const publicPricingCopy = {
  zh: {
    listing: {
      pages: {
        ai: {
          eyebrow: "GeoSub AI 价格数据",
          title: "AI 订阅价格对比",
          description:
            "比较 ChatGPT、Claude、Gemini 等 AI 工具在不同地区的订阅价格，查看最低价地区、高价地区、税费说明和价格差距。",
          metaTitle: "AI 订阅价格对比 - ChatGPT、Claude、Gemini 全球价格",
          metaDescription:
            "比较 ChatGPT、Claude、Gemini、Grok 等 AI 订阅在不同国家和地区的 App Store 价格、显示币种换算、税费、购买力与更新时间，查找已核验的低价地区。",
        },
        streaming: {
          eyebrow: "GeoSub 流媒体价格数据",
          title: "流媒体订阅价格对比",
          description:
            "比较 Netflix、Disney+ 等已收录流媒体服务在不同地区的订阅价格、税费、更新时间和购买力差异。",
          metaTitle:
            "流媒体订阅价格对比 - Netflix、Disney+ 全球价格",
          metaDescription:
            "比较 Netflix、Disney+、HBO Max 等流媒体订阅在不同国家和地区的公开价格、汇率换算、税费、购买力与更新时间，查看已核验的地区价差。",
        },
      },
      categoryAria: "数字服务分类",
      aiLabel: "AI 订阅",
      aiDescription:
        "比较 ChatGPT、Claude、Gemini、Grok 等 AI 产品在不同国家和地区的价格。",
      streamingLabel: "流媒体",
      streamingDescription:
        "比较 Netflix、Disney+ 等已收录流媒体和数字娱乐订阅价格。",
      productCount: (count: number) => `当前收录 ${count} 个产品`,
      empty: "当前分类暂无已发布价格数据。",
      defaultPlanHint: "默认展示主流月付套餐",
      card: {
        titleSuffix: "各地区定价",
        region: "地区",
        price: "价格",
        tax: "税费说明",
        base: "基准",
        updated: "更新时间",
        spread: "价差",
        regions: "个地区",
        detail: "查看详情",
        highest: "最高价",
        lowest: "最低价",
        monthlySuffix: "/月",
        yearlySuffix: "/年",
        weeklySuffix: "/周",
        taxInferred: "平台推断",
        taxVerified: "高可信",
        taxMedium: "中可信",
        taxNeedsReview: "待复核",
        taxUnverified: "待核验",
        checkoutApplies: "结算页为准",
      },
    },
    navigation: {
      products: "产品总览",
      currentProduct: "当前产品",
      ai: "AI 订阅",
      streaming: "流媒体",
      other: "其他",
    },
    pricing: {
      appStoreSource: "价格来源：App Store",
      conclusionTitle: (planName: string) => `${planName} 全球价格结论`,
      conclusion: (source: string, lowest: string, highest: string, spread: number) =>
        `当前以 ${source} 正式价格比较，${lowest} 最便宜；${highest} 最贵，价差约 ${spread}%。`,
      conclusionLead: (source: string, country: string) =>
        `当前以 ${source} 正式价格比较，${country} 最便宜，约`,
      conclusionMiddle: (country: string) => `；${country} 最贵，约`,
      conclusionSpread: (spread: number) => `，价差约 ${spread}%。`,
      pageUpdated: (date: string) => `页面更新：${date}`,
      regionCount: (count: number) => `${count} 个地区`,
      displayCurrency: "显示币种",
      officialWebPricing: "官网价格",
      allDiagnosticSources: "全部价格来源",
      allSources: "全部来源",
      webLead: "官网价格",
      googlePlayLead: "Google Play 价格",
      allDiagnostics: "其他来源",
      cnyLabel: "人民币 CNY",
      usdLabel: "美元 USD",
      monthlySuffix: "/月",
      cnyUnavailable: "人民币估算暂不可用：汇率待同步",
      cnyStale: "人民币估算暂停：汇率同步已过期",
      synced: (date: string) => `同步 ${date}`,
      rateBasis: (date: string) => `汇率基准 ${date}`,
      cnyRate: (rate: number) => `人民币按 ${rate.toFixed(4)} 汇率估算`,
      lowest: "最低价",
      highest: "最高价",
      usBase: "美国基准",
      regions: "覆盖地区",
      source: "数据来源",
      latestCollection: "最近采集",
      fxBasis: "汇率基准",
      planReview: "套餐复核",
      trustStatus: "可信状态",
      verified: "高可信",
      reviewed: "已复核",
      needsReview: "待复核",
      unavailable: "暂无",
      distributionEyebrow: "价格分布",
      distributionTitle: "全球价格分布与地区排行",
      distributionDescription: (productName: string) =>
        `地图用于快速理解 ${productName} 的全球价格差异；榜单用于辅助定位低价区和高价区。`,
      lowerRegions: "更便宜的地区",
      higherRegions: "更贵的地区",
      noPrices: (source: string) => `暂无 ${source} 价格数据`,
      noPricesDescription:
        "该来源暂无可用于比较的已复核价格，因此暂不显示价格分布、地区排行和明细表。",
    },
    table: {
      eyebrow: "地区价格",
      title: (planName: string) => `${planName} 地区价格明细`,
      description: (source: string, currency: string) =>
        `价格来源：${source}。按${currency}从低到高排序。`,
      regionCount: (count: number) => `${count} 个地区`,
      allSources: "全部来源",
      webLead: "官网价格",
      googlePlayLead: "Google Play 价格",
      allDiagnostics: "其他来源",
      usd: "美元 USD",
      usdEquivalent: "美元折算",
      usdSort: "美元折算价",
      cnyEstimate: "人民币折算",
      cnySort: "人民币折算价",
      perMonth: "/月",
      rank: "排名",
      region: "地区",
      localPrice: "本地价格",
      vsUs: "对比美国",
      taxNote: "税费说明",
      source: "来源",
      statusRisk: "价格位置 / 订阅条件",
      sameAsUs: "与美国相同",
      aboveUs: (percent: number) => `比美国贵 ${percent}%`,
      belowUs: (percent: number) => `比美国便宜 ${percent}%`,
      statusLow: "低价",
      statusHigh: "高价",
      statusAbove: "偏高",
      statusBase: "基准",
      riskLow: "低",
      riskMedium: "中",
      riskHigh: "高",
      riskNeedsReview: "待核验",
      riskPrefix: (label: string) => `风险${label}`,
      riskFallback: "跨区订阅可能受账号地区、付款方式和平台风控影响。",
      taxInferred: "平台推断",
      taxVerified: "高可信",
      taxMedium: "中可信",
      taxNeedsReview: "待复核",
      taxUnverified: "待核验",
      checkoutApplies: "结算页为准",
      taxVerifiedHelp: "税务资料来自国家税务资料库，高可信。",
      taxInferredHelp:
        "系统根据 App Store 平台结算逻辑生成说明；具体税率仍以官方结算页为准。",
      taxMediumHelp: "税务资料来自国家或地区税务资料库，仍需定期复核。",
      taxUnverifiedHelp: "该地区税务资料尚未核验，最终以结算页为准。",
      taxRankingPolicy:
        "GeoSub 不把税率额外加入采集价格；价格排序使用 App Store 标价折算。",
      priceCollected: "价格采集",
      fxBasis: "采集汇率基准",
      convertedHelp: "把本地价格按汇率折算成统一货币，方便横向比较。",
      vsUsHelp: "以美国地区价格为基准，显示该地区便宜或贵多少。",
      taxHelp:
        "当地 VAT、GST、消费税或销售税说明，仅作背景参考；价格排序不额外加税，最终以 App Store 结算页为准。",
      riskHelp:
        "价格位置用于对比美国基准；订阅条件逐项说明当地商店是否提供套餐、账号地区、付款方式、官方入口和核验日期。未核验的条件不会被推断为可用。",
      empty: (source: string) => `暂无 ${source} 价格数据。`,
      showMore: (count: number) => `显示更多 ${count} 个地区`,
      collapse: "收起地区列表",
      riskNote:
        "订阅条件说明：GeoSub 只展示可核验的公开事实。当地 App Store 出现价格不代表其他地区账号一定能够购买；账号地区、付款方式和礼品卡支持未确认时会明确标为未核验。",
      helpAria: (label: string, help: string) => `${label}说明：${help}`,
    },
  },
  "zh-tw": {
    listing: {
        pages: {
            ai: {
                eyebrow: "GeoSub AI 價格資料",
                title: "AI 訂閱價格對比",
                description: "比較 ChatGPT、Claude、Gemini 等 AI 工具在不同地區的訂閱價格，檢視最低價地區、高價地區、稅費說明和價格差距。",
                metaTitle: "AI 訂閱價格對比 - ChatGPT、Claude、Gemini 全球價格",
                metaDescription: "比較 ChatGPT、Claude、Gemini 等 AI 訂閱在不同國家和地區的 App Store 價格、顯示幣種換算、稅費說明和購買力差異。",
            },
            streaming: {
                eyebrow: "GeoSub 流媒體價格資料",
                title: "流媒體訂閱價格對比",
                description: "比較 Netflix、Disney+ 等已收錄流媒體服務在不同地區的訂閱價格、稅費、更新時間和購買力差異。",
                metaTitle: "流媒體訂閱價格對比 - Netflix、Disney+ 全球價格",
                metaDescription: "比較 Netflix、Disney+ 等已收錄流媒體訂閱在不同國家和地區的價格、稅費、更新時間和區域價格差異。",
            },
        },
        categoryAria: "數字服務分類",
        aiLabel: "AI 訂閱",
        aiDescription: "比較 ChatGPT、Claude、Gemini、Grok 等 AI 產品在不同國家和地區的價格。",
        streamingLabel: "流媒體",
        streamingDescription: "比較 Netflix、Disney+ 等已收錄流媒體和數字娛樂訂閱價格。",
        productCount: (count: number) => `當前收錄 ${count} 個產品`,
        empty: "當前分類暫無已釋出價格資料。",
        defaultPlanHint: "預設展示主流月付套餐",
        card: {
            titleSuffix: "各地區定價",
            region: "地區",
            price: "價格",
            tax: "稅費說明",
            base: "基準",
            updated: "更新時間",
            spread: "價差",
            regions: "個地區",
            detail: "檢視詳情",
            highest: "最高價",
            lowest: "最低價",
            monthlySuffix: "/月",
            yearlySuffix: "/年",
            weeklySuffix: "/周",
            taxInferred: "平台推斷",
            taxVerified: "高可信",
            taxMedium: "中可信",
            taxNeedsReview: "待複核",
            taxUnverified: "待核驗",
            checkoutApplies: "結算頁為準",
        },
    },
    navigation: {
        products: "產品總覽",
        currentProduct: "當前產品",
        ai: "AI 訂閱",
        streaming: "流媒體",
        other: "其他",
    },
    pricing: {
        appStoreSource: "價格來源：App Store",
        conclusionTitle: (planName: string) => `${planName} 全球價格結論`,
        conclusion: (source: string, lowest: string, highest: string, spread: number) => `當前以 ${source} 正式價格比較，${lowest} 最便宜；${highest} 最貴，價差約 ${spread}%。`,
        conclusionLead: (source: string, country: string) => `當前以 ${source} 正式價格比較，${country} 最便宜，約`,
        conclusionMiddle: (country: string) => `；${country} 最貴，約`,
        conclusionSpread: (spread: number) => `，價差約 ${spread}%。`,
        pageUpdated: (date: string) => `頁面更新：${date}`,
        regionCount: (count: number) => `${count} 個地區`,
        displayCurrency: "顯示幣種",
        officialWebPricing: "官網價格",
        allDiagnosticSources: "全部價格來源",
        allSources: "全部來源",
        webLead: "官網價格",
        googlePlayLead: "Google Play 價格",
        allDiagnostics: "其他來源",
        cnyLabel: "人民幣 CNY",
        usdLabel: "美元 USD",
        monthlySuffix: "/月",
        cnyUnavailable: "人民幣估算暫不可用：匯率待同步",
        cnyStale: "人民幣估算暫停：匯率同步已過期",
        synced: (date: string) => `同步 ${date}`,
        rateBasis: (date: string) => `匯率基準 ${date}`,
        cnyRate: (rate: number) => `人民幣按 ${rate.toFixed(4)} 匯率估算`,
        lowest: "最低價",
        highest: "最高價",
        usBase: "美國基準",
        regions: "覆蓋地區",
        source: "資料來源",
        latestCollection: "最近採集",
        fxBasis: "匯率基準",
        planReview: "套餐複核",
        trustStatus: "可信狀態",
        verified: "高可信",
        reviewed: "已複核",
        needsReview: "待複核",
        unavailable: "暫無",
        distributionEyebrow: "價格分佈",
        distributionTitle: "全球價格分佈與地區排行",
        distributionDescription: (productName: string) => `地圖用於快速理解 ${productName} 的全球價格差異；榜單用於輔助定位低價區和高價區。`,
        lowerRegions: "更便宜的地區",
        higherRegions: "更貴的地區",
        noPrices: (source: string) => `暫無 ${source} 價格資料`,
        noPricesDescription: "該來源暫無可用於比較的已複核價格，因此暫不顯示價格分佈、地區排行和明細表。",
    },
    table: {
        eyebrow: "地區價格",
        title: (planName: string) => `${planName} 地區價格明細`,
        description: (source: string, currency: string) => `價格來源：${source}。按${currency}從低到高排序。`,
        regionCount: (count: number) => `${count} 個地區`,
        allSources: "全部來源",
        webLead: "官網價格",
        googlePlayLead: "Google Play 價格",
        allDiagnostics: "其他來源",
        usd: "美元 USD",
        usdEquivalent: "美元折算",
        usdSort: "美元折算價",
        cnyEstimate: "人民幣折算",
        cnySort: "人民幣折算價",
        perMonth: "/月",
        rank: "排名",
        region: "地區",
        localPrice: "本地價格",
        vsUs: "對比美國",
        taxNote: "稅費說明",
        source: "來源",
        statusRisk: "價格位置 / 訂閱條件",
        sameAsUs: "與美國相同",
        aboveUs: (percent: number) => `比美國貴 ${percent}%`,
        belowUs: (percent: number) => `比美國便宜 ${percent}%`,
        statusLow: "低價",
        statusHigh: "高價",
        statusAbove: "偏高",
        statusBase: "基準",
        riskLow: "低",
        riskMedium: "中",
        riskHigh: "高",
        riskNeedsReview: "待核驗",
        riskPrefix: (label: string) => `風險${label}`,
        riskFallback: "跨區訂閱可能受帳號地區、付款方式和平台風控影響。",
        taxInferred: "平台推斷",
        taxVerified: "高可信",
        taxMedium: "中可信",
        taxNeedsReview: "待複核",
        taxUnverified: "待核驗",
        checkoutApplies: "結算頁為準",
        taxVerifiedHelp: "稅務資料來自國家稅務資料庫，高可信。",
        taxInferredHelp: "系統根據 App Store 平台結算邏輯生成說明；具體稅率仍以官方結算頁為準。",
        taxMediumHelp: "稅務資料來自國家或地區稅務資料庫，仍需定期複核。",
        taxUnverifiedHelp: "該地區稅務資料尚未核驗，最終以結算頁為準。",
        taxRankingPolicy: "GeoSub 不把稅率額外加入採集價格；價格排序使用 App Store 標價折算。",
        priceCollected: "價格採集",
        fxBasis: "採集匯率基準",
        convertedHelp: "把本地價格按匯率折算成統一貨幣，方便橫向比較。",
        vsUsHelp: "以美國地區價格為基準，顯示該地區便宜或貴多少。",
        taxHelp: "當地 VAT、GST、消費稅或銷售稅說明，僅作背景參考；價格排序不額外加稅，最終以 App Store 結算頁為準。",
        riskHelp: "價格位置用於對比美國基準；訂閱條件逐項說明當地商店是否提供套餐、帳號地區、付款方式、官方入口和核驗日期。未核驗的條件不會被推斷為可用。",
        empty: (source: string) => `暫無 ${source} 價格資料。`,
        showMore: (count: number) => `顯示更多 ${count} 個地區`,
        collapse: "收起地區列表",
        riskNote: "訂閱條件說明：GeoSub 只展示可核驗的公開事實。當地 App Store 出現價格不代表其他地區帳號一定能夠購買；帳號地區、付款方式和禮品卡支援未確認時會明確標為未核驗。",
        helpAria: (label: string, help: string) => `${label}說明：${help}`,
    },
},
  en: {
    listing: {
      pages: {
        ai: {
          eyebrow: "GeoSub AI Pricing Data",
          title: "AI Subscription Pricing",
          description:
            "Compare ChatGPT, Claude, Gemini and other AI tools across countries and regions, including local prices, USD equivalents, tax notes and regional price differences.",
          metaTitle:
            "AI Subscription Pricing - ChatGPT, Claude, Gemini Global Prices",
          metaDescription:
            "Compare ChatGPT, Claude, Gemini and other AI subscription prices across countries and regions, including App Store prices, USD equivalents, tax notes and regional price differences.",
        },
        streaming: {
          eyebrow: "GeoSub Streaming Pricing Data",
          title: "Streaming Subscription Pricing",
          description:
            "Compare published Netflix, Disney+ and other streaming subscription prices across regions, with tax, update and affordability context.",
          metaTitle:
            "Streaming Subscription Pricing - Netflix and Disney+ Global Prices",
          metaDescription:
            "Compare published Netflix, Disney+ and other streaming subscription prices across countries and regions, with tax and update context.",
        },
      },
      categoryAria: "Digital service category",
      aiLabel: "AI Subscriptions",
      aiDescription:
        "Compare ChatGPT, Claude, Gemini, Grok and other AI subscription prices across countries and regions.",
      streamingLabel: "Streaming",
      streamingDescription:
        "Compare published Netflix, Disney+ and other digital entertainment subscription prices.",
      productCount: (count: number) => `Currently tracking ${count} products`,
      empty: "No published pricing data is available for this category yet.",
      defaultPlanHint: "Popular monthly plan shown by default",
      card: {
        titleSuffix: "Regional Pricing",
        region: "Region",
        price: "Price",
        tax: "Tax note",
        base: "Base",
        updated: "Updated",
        spread: "price spread",
        regions: "regions",
        detail: "View details",
        highest: "Highest",
        lowest: "Lowest",
        monthlySuffix: "/mo",
        yearlySuffix: "/yr",
        weeklySuffix: "/wk",
        taxInferred: "Platform inferred",
        taxVerified: "Verified",
        taxMedium: "Medium",
        taxNeedsReview: "Needs review",
        taxUnverified: "Unverified",
        checkoutApplies: "Checkout applies",
      },
    },
    navigation: {
      products: "Products",
      currentProduct: "Current product",
      ai: "AI Subscriptions",
      streaming: "Streaming",
      other: "Other",
    },
    pricing: {
      appStoreSource: "Price source: App Store",
      conclusionTitle: (planName: string) => `${planName} global price conclusion`,
      conclusion: (source: string, lowest: string, highest: string, spread: number) =>
        `Based on official ${source} pricing, ${lowest} is currently the cheapest; ${highest} is the most expensive, with a spread of about ${spread}%.`,
      conclusionLead: (source: string, country: string) =>
        `Based on official ${source} pricing, ${country} is currently the cheapest at about`,
      conclusionMiddle: (country: string) =>
        `; ${country} is the most expensive at about`,
      conclusionSpread: (spread: number) =>
        `, with a spread of about ${spread}%.`,
      pageUpdated: (date: string) => `Page updated: ${date}`,
      regionCount: (count: number) => `${count} regions`,
      displayCurrency: "Display currency",
      officialWebPricing: "official web pricing",
      allDiagnosticSources: "all price sources",
      allSources: "all sources",
      cnyLabel: "CNY estimate",
      usdLabel: "USD",
      monthlySuffix: "/mo",
      cnyUnavailable: "CNY estimate unavailable: exchange-rate sync is pending",
      cnyStale: "CNY estimate paused: exchange-rate sync is stale",
      synced: (date: string) => `synced ${date}`,
      rateBasis: (date: string) => `rate basis ${date}`,
      cnyRate: (rate: number) => `CNY uses ${rate.toFixed(4)} USD/CNY`,
      lowest: "Lowest",
      highest: "Highest",
      usBase: "US base",
      regions: "Regions",
      source: "Source",
      latestCollection: "Latest collection",
      fxBasis: "FX basis",
      planReview: "Plan review",
      trustStatus: "Trust status",
      verified: "Verified",
      reviewed: "Reviewed",
      needsReview: "Needs review",
      unavailable: "Not available",
      distributionEyebrow: "Price distribution",
      distributionTitle: "Global price distribution and regional ranking",
      distributionDescription: (productName: string) =>
        `The map explains ${productName} regional price differences; the lists highlight lower-price and higher-price regions.`,
      lowerRegions: "Lower-price regions",
      higherRegions: "Higher-price regions",
      noPrices: (source: string) => `No ${source} pricing yet`,
      noPricesDescription:
        "This source does not currently have enough reviewed prices for comparison, so the distribution, ranking and detail table are not shown.",
    },
    table: {
      eyebrow: "Region prices",
      title: (planName: string) => `${planName} regional price details`,
      description: (source: string, currency: string) =>
        `Price source: ${source}. Sorted by ${currency} from low to high.`,
      regionCount: (count: number) => `${count} regions`,
      allSources: "All sources",
      webLead: "Official web price",
      googlePlayLead: "Google Play price",
      allDiagnostics: "Other sources",
      usd: "USD",
      usdEquivalent: "USD equivalent",
      usdSort: "USD equivalent",
      cnyEstimate: "CNY estimate",
      cnySort: "CNY estimate",
      perMonth: "/mo",
      rank: "Rank",
      region: "Region",
      localPrice: "Local price",
      vsUs: "vs US",
      taxNote: "Tax note",
      source: "Source",
      statusRisk: "Price position / access",
      sameAsUs: "Same as US",
      aboveUs: (percent: number) => `${percent}% above US`,
      belowUs: (percent: number) => `${percent}% below US`,
      statusLow: "Low",
      statusHigh: "High",
      statusAbove: "Above",
      statusBase: "Base",
      riskLow: "low",
      riskMedium: "medium",
      riskHigh: "high",
      riskNeedsReview: "needs review",
      riskPrefix: (label: string) => `Risk ${label}`,
      riskFallback:
        "Cross-region subscriptions may be affected by account region, payment method and platform risk controls.",
      taxInferred: "Platform inferred",
      taxVerified: "Verified",
      taxMedium: "Medium confidence",
      taxNeedsReview: "Needs review",
      taxUnverified: "Unverified",
      checkoutApplies: "Checkout applies",
      taxVerifiedHelp: "Tax profile comes from the country tax database and is verified.",
      taxInferredHelp:
        "Generated from App Store billing assumptions; final checkout remains authoritative.",
      taxMediumHelp:
        "Tax profile comes from country or regional tax data and needs periodic review.",
      taxUnverifiedHelp:
        "Tax profile is not verified yet; final checkout remains authoritative.",
      taxRankingPolicy:
        "GeoSub does not add tax again; rankings use the App Store list price converted to USD.",
      priceCollected: "Price collected",
      fxBasis: "FX basis",
      convertedHelp: "Converts local prices into a common currency for comparison.",
      vsUsHelp: "Uses the US price as the baseline and shows how much cheaper or more expensive each region is.",
      taxHelp:
        "VAT, GST, consumption tax or sales tax notes are contextual only. Rankings do not add tax again; final App Store checkout remains authoritative.",
      riskHelp:
        "Price position compares the region with the US baseline. Access lists verifiable store availability, account-region and payment conditions, the official source and the verification date. Unknown conditions are not inferred as available.",
      empty: (source: string) => `No ${source} pricing is available yet.`,
      showMore: (count: number) => `Show ${count} more regions`,
      collapse: "Collapse regions",
      riskNote:
        "Access note: GeoSub shows only verifiable public facts. A listed local App Store price does not prove that an account from another region can purchase it; unverified account, payment and gift-card conditions are labeled accordingly.",
      helpAria: (label: string, help: string) => `${label}: ${help}`,
    },
  },
} satisfies Record<LegacyPublicPricingLocale, object>;

export function getPublicPricingCopy(locale: LegacyPublicPricingLocale) {
  return publicPricingCopy[locale];
}
