import { getPublicPricingCopy } from "./public-pricing-copy";
import {
  type PreparedSiteLocale,
} from "./site-locale";
import { toTraditionalChinese } from "./traditional-chinese";

type WidenCopy<T> =
  T extends string
    ? string
    : T extends (...args: infer Args) => string
      ? (...args: Args) => string
      : T extends object
        ? { [Key in keyof T]: WidenCopy<T[Key]> }
        : T;

export type RegionPriceTableCopy = WidenCopy<
  ReturnType<typeof getPublicPricingCopy>["table"]
>;

const preparedRegionPriceTableCopy = {
  ja: {
    eyebrow: "地域別料金",
    title: (planName) => `${planName} の地域別料金詳細`,
    description: (source, currency) =>
      `料金ソース：${source}。${currency}の安い順に表示しています。`,
    regionCount: (count) => `${count} 地域`,
    allSources: "すべてのソース",
    webLead: "公式サイト料金",
    googlePlayLead: "Google Play 料金",
    allDiagnostics: "その他のソース",
    usd: "米ドル USD",
    usdEquivalent: "米ドル換算",
    usdSort: "米ドル換算額",
    cnyEstimate: "人民元換算",
    cnySort: "人民元換算額",
    perMonth: "/月",
    rank: "順位",
    region: "地域",
    localPrice: "現地価格",
    vsUs: "米国比",
    taxNote: "税情報",
    source: "ソース",
    statusRisk: "価格帯・リスク",
    sameAsUs: "米国と同額",
    aboveUs: (percent) => `米国より ${percent}% 高い`,
    belowUs: (percent) => `米国より ${percent}% 安い`,
    statusLow: "割安",
    statusHigh: "割高",
    statusAbove: "やや高い",
    statusBase: "基準",
    riskLow: "低",
    riskMedium: "中",
    riskHigh: "高",
    riskNeedsReview: "要確認",
    riskPrefix: (label) => `リスク：${label}`,
    riskFallback:
      "地域をまたぐ契約は、アカウント地域、支払い方法、プラットフォームのリスク管理の影響を受ける場合があります。",
    taxInferred: "プラットフォーム推定",
    taxVerified: "確認済み",
    taxMedium: "中程度の信頼度",
    taxNeedsReview: "要確認",
    taxUnverified: "未確認",
    checkoutApplies: "決済画面を優先",
    taxVerifiedHelp: "国別税務データベースに基づく確認済みの情報です。",
    taxInferredHelp:
      "App Store の決済仕様から推定した情報です。最終的な税額は公式の決済画面で確認してください。",
    taxMediumHelp:
      "国または地域の税務資料に基づく情報で、定期的な再確認が必要です。",
    taxUnverifiedHelp:
      "税務情報は未確認です。最終的な内容は公式の決済画面を優先してください。",
    taxRankingPolicy:
      "GeoSub は税金を重ねて加算しません。順位は App Store の表示価格を米ドル換算して算出します。",
    priceCollected: "料金取得日",
    fxBasis: "為替基準日",
    convertedHelp: "現地価格を共通通貨に換算し、地域間で比較できるようにします。",
    vsUsHelp: "米国価格を基準に、各地域が何%安いか高いかを示します。",
    taxHelp:
      "VAT、GST、消費税、売上税の情報は参考です。順位では税金を再加算せず、最終価格は App Store の決済画面を優先します。",
    riskHelp:
      "価格帯は米国基準との比較です。リスクはアカウント地域、支払い方法、請求情報、プラットフォーム管理を総合した目安です。",
    empty: (source) => `${source} の料金データはまだありません。`,
    showMore: (count) => `さらに ${count} 地域を表示`,
    collapse: "地域一覧を折りたたむ",
    riskNote:
      "注意：GeoSub は地域別の公開料金を比較するためのサービスで、プラットフォーム規約の回避を推奨しません。地域をまたぐ契約は Apple ID の地域、支払い方法、請求情報、税金、リスク管理の影響を受けます。契約可否は公式の決済画面で確認してください。",
    helpAria: (label, help) => `${label}の説明：${help}`,
  },
  ko: {
    eyebrow: "지역별 가격",
    title: (planName) => `${planName} 지역별 가격 상세`,
    description: (source, currency) =>
      `가격 출처: ${source}. ${currency}가 낮은 순으로 정렬했습니다.`,
    regionCount: (count) => `${count}개 지역`,
    allSources: "모든 출처",
    webLead: "공식 웹 가격",
    googlePlayLead: "Google Play 가격",
    allDiagnostics: "기타 출처",
    usd: "미국 달러 USD",
    usdEquivalent: "달러 환산",
    usdSort: "달러 환산가",
    cnyEstimate: "위안화 환산",
    cnySort: "위안화 환산가",
    perMonth: "/월",
    rank: "순위",
    region: "지역",
    localPrice: "현지 가격",
    vsUs: "미국 대비",
    taxNote: "세금 안내",
    source: "출처",
    statusRisk: "가격대·위험",
    sameAsUs: "미국과 동일",
    aboveUs: (percent) => `미국보다 ${percent}% 비쌈`,
    belowUs: (percent) => `미국보다 ${percent}% 저렴`,
    statusLow: "저가",
    statusHigh: "고가",
    statusAbove: "다소 높음",
    statusBase: "기준",
    riskLow: "낮음",
    riskMedium: "보통",
    riskHigh: "높음",
    riskNeedsReview: "확인 필요",
    riskPrefix: (label) => `위험 ${label}`,
    riskFallback:
      "다른 지역에서 구독할 경우 계정 지역, 결제 수단과 플랫폼 위험 관리의 영향을 받을 수 있습니다.",
    taxInferred: "플랫폼 추정",
    taxVerified: "확인됨",
    taxMedium: "중간 신뢰도",
    taxNeedsReview: "확인 필요",
    taxUnverified: "미확인",
    checkoutApplies: "결제 화면 기준",
    taxVerifiedHelp: "국가별 세금 데이터베이스에서 확인된 자료입니다.",
    taxInferredHelp:
      "App Store 결제 방식에 따라 추정한 정보이며 최종 세금은 공식 결제 화면을 기준으로 합니다.",
    taxMediumHelp:
      "국가 또는 지역 세금 자료에 기반하며 정기적인 재확인이 필요합니다.",
    taxUnverifiedHelp:
      "아직 확인되지 않은 세금 정보입니다. 최종 내용은 공식 결제 화면을 기준으로 합니다.",
    taxRankingPolicy:
      "GeoSub는 세금을 다시 더하지 않습니다. 순위는 App Store 표시 가격을 달러로 환산해 계산합니다.",
    priceCollected: "가격 수집일",
    fxBasis: "환율 기준일",
    convertedHelp: "현지 가격을 공통 통화로 환산해 지역 간 비교를 돕습니다.",
    vsUsHelp: "미국 가격을 기준으로 각 지역이 얼마나 저렴하거나 비싼지 보여 줍니다.",
    taxHelp:
      "VAT, GST, 소비세 또는 판매세 안내는 참고용입니다. 순위에는 세금을 다시 더하지 않으며 최종 가격은 App Store 결제 화면을 기준으로 합니다.",
    riskHelp:
      "가격대는 미국 기준과 비교한 결과입니다. 위험은 계정 지역, 결제 수단, 청구 정보와 플랫폼 관리 정책을 종합한 지표입니다.",
    empty: (source) => `${source} 가격 데이터가 아직 없습니다.`,
    showMore: (count) => `${count}개 지역 더 보기`,
    collapse: "지역 목록 접기",
    riskNote:
      "주의: GeoSub는 지역별 공개 구독 가격을 비교하며 플랫폼 규정 우회를 권장하지 않습니다. 다른 지역 구독은 Apple ID 지역, 결제 수단, 청구 정보, 세금과 플랫폼 위험 관리의 영향을 받을 수 있습니다. 실제 구독 가능 여부는 공식 결제 화면을 확인하세요.",
    helpAria: (label, help) => `${label} 설명: ${help}`,
  },
  es: {
    eyebrow: "Precios por región",
    title: (planName) => `Precios regionales de ${planName}`,
    description: (source, currency) =>
      `Fuente: ${source}. Ordenados de menor a mayor por su equivalencia en ${currency}.`,
    regionCount: (count) => `${count} regiones`,
    allSources: "Todas las fuentes",
    webLead: "Precio web oficial",
    googlePlayLead: "Precio de Google Play",
    allDiagnostics: "Otras fuentes",
    usd: "Dólar USD",
    usdEquivalent: "Equivalencia en USD",
    usdSort: "USD",
    cnyEstimate: "Estimación en CNY",
    cnySort: "CNY",
    perMonth: "/mes",
    rank: "Puesto",
    region: "Región",
    localPrice: "Precio local",
    vsUs: "Frente a EE. UU.",
    taxNote: "Impuestos",
    source: "Fuente",
    statusRisk: "Nivel y riesgo",
    sameAsUs: "Igual que EE. UU.",
    aboveUs: (percent) => `${percent}% más caro que EE. UU.`,
    belowUs: (percent) => `${percent}% más barato que EE. UU.`,
    statusLow: "Bajo",
    statusHigh: "Alto",
    statusAbove: "Por encima",
    statusBase: "Referencia",
    riskLow: "bajo",
    riskMedium: "medio",
    riskHigh: "alto",
    riskNeedsReview: "por revisar",
    riskPrefix: (label) => `Riesgo ${label}`,
    riskFallback:
      "Las suscripciones entre regiones pueden verse afectadas por la región de la cuenta, el método de pago y los controles de la plataforma.",
    taxInferred: "Estimado por la plataforma",
    taxVerified: "Verificado",
    taxMedium: "Confianza media",
    taxNeedsReview: "Por revisar",
    taxUnverified: "Sin verificar",
    checkoutApplies: "Rige el pago final",
    taxVerifiedHelp: "El perfil fiscal procede de la base de datos tributaria nacional y está verificado.",
    taxInferredHelp:
      "Información estimada según la facturación de App Store; prevalece siempre el importe mostrado al pagar.",
    taxMediumHelp:
      "El perfil procede de datos fiscales nacionales o regionales y requiere revisiones periódicas.",
    taxUnverifiedHelp:
      "El perfil fiscal aún no está verificado; prevalece siempre el importe mostrado al pagar.",
    taxRankingPolicy:
      "GeoSub no añade de nuevo los impuestos. La clasificación usa el precio publicado en App Store convertido a USD.",
    priceCollected: "Precio recogido",
    fxBasis: "Fecha del tipo de cambio",
    convertedHelp: "Convierte los precios locales a una moneda común para facilitar la comparación.",
    vsUsHelp: "Toma el precio de EE. UU. como referencia y muestra cuánto varía cada región.",
    taxHelp:
      "Las notas sobre IVA, GST, impuestos al consumo o ventas son orientativas. La clasificación no vuelve a sumar impuestos; prevalece el pago final de App Store.",
    riskHelp:
      "El nivel compara cada región con EE. UU. El riesgo considera la región de la cuenta, el método de pago, la facturación y los controles de la plataforma.",
    empty: (source) => `Todavía no hay precios disponibles de ${source}.`,
    showMore: (count) => `Mostrar ${count} regiones más`,
    collapse: "Mostrar menos regiones",
    riskNote:
      "Aviso: GeoSub compara precios públicos por región y no promueve eludir las normas de la plataforma. Las suscripciones entre regiones pueden depender de la región del Apple ID, el método de pago, la facturación, los impuestos y los controles de riesgo. La disponibilidad final se confirma en el pago oficial.",
    helpAria: (label, help) => `${label}: ${help}`,
  },
  tr: {
    eyebrow: "Bölgesel fiyatlar",
    title: (planName) => `${planName} bölgesel fiyat ayrıntıları`,
    description: (source, currency) =>
      `Fiyat kaynağı: ${source}. ${currency} bazında düşükten yükseğe sıralanmıştır.`,
    regionCount: (count) => `${count} bölge`,
    allSources: "Tüm kaynaklar",
    webLead: "Resmî web fiyatı",
    googlePlayLead: "Google Play fiyatı",
    allDiagnostics: "Diğer kaynaklar",
    usd: "ABD doları USD",
    usdEquivalent: "USD karşılığı",
    usdSort: "USD karşılığı",
    cnyEstimate: "CNY tahmini",
    cnySort: "CNY tahmini",
    perMonth: "/ay",
    rank: "Sıra",
    region: "Bölge",
    localPrice: "Yerel fiyat",
    vsUs: "ABD'ye göre",
    taxNote: "Vergi notu",
    source: "Kaynak",
    statusRisk: "Seviye ve risk",
    sameAsUs: "ABD ile aynı",
    aboveUs: (percent) => `ABD'den %${percent} daha pahalı`,
    belowUs: (percent) => `ABD'den %${percent} daha ucuz`,
    statusLow: "Düşük",
    statusHigh: "Yüksek",
    statusAbove: "Yüksekçe",
    statusBase: "Ölçüt",
    riskLow: "düşük",
    riskMedium: "orta",
    riskHigh: "yüksek",
    riskNeedsReview: "inceleme gerekli",
    riskPrefix: (label) => `Risk: ${label}`,
    riskFallback:
      "Bölgeler arası abonelikler hesap bölgesi, ödeme yöntemi ve platform risk kontrollerinden etkilenebilir.",
    taxInferred: "Platform tahmini",
    taxVerified: "Doğrulandı",
    taxMedium: "Orta güven",
    taxNeedsReview: "İnceleme gerekli",
    taxUnverified: "Doğrulanmadı",
    checkoutApplies: "Ödeme ekranı geçerlidir",
    taxVerifiedHelp: "Vergi profili ülke vergi veritabanından gelir ve doğrulanmıştır.",
    taxInferredHelp:
      "App Store faturalandırma varsayımlarından üretilmiştir; son ödeme ekranı esas alınır.",
    taxMediumHelp:
      "Ülke veya bölge vergi verilerine dayanır ve düzenli olarak gözden geçirilmelidir.",
    taxUnverifiedHelp:
      "Vergi profili henüz doğrulanmamıştır; son ödeme ekranı esas alınır.",
    taxRankingPolicy:
      "GeoSub vergiyi yeniden eklemez. Sıralama, App Store liste fiyatının USD karşılığını kullanır.",
    priceCollected: "Fiyat toplama",
    fxBasis: "Kur tarihi",
    convertedHelp: "Karşılaştırma için yerel fiyatları ortak bir para birimine dönüştürür.",
    vsUsHelp: "ABD fiyatını ölçüt alır ve her bölgenin ne kadar ucuz veya pahalı olduğunu gösterir.",
    taxHelp:
      "KDV, GST, tüketim veya satış vergisi notları yalnızca bilgi amaçlıdır. Sıralamada vergi yeniden eklenmez; App Store ödeme ekranı esas alınır.",
    riskHelp:
      "Seviye, bölgeyi ABD ölçütüyle karşılaştırır. Risk; hesap bölgesi, ödeme yöntemi, fatura bilgileri ve platform kontrollerini yansıtır.",
    empty: (source) => `${source} için henüz fiyat yok.`,
    showMore: (count) => `${count} bölge daha göster`,
    collapse: "Daha az bölge göster",
    riskNote:
      "Uyarı: GeoSub bölgesel abonelik maliyetlerini karşılaştırmak için herkese açık fiyatları sunar ve platform kurallarını aşmayı teşvik etmez. Bölgeler arası abonelikler Apple ID bölgesi, ödeme yöntemi, fatura bilgileri, vergiler ve risk kontrollerinden etkilenebilir. Son kullanılabilirlik resmî ödeme ekranına bağlıdır.",
    helpAria: (label, help) => `${label}: ${help}`,
  },
  ar: {
    eyebrow: "الأسعار حسب المنطقة",
    title: (planName) => `تفاصيل أسعار ${planName} حسب المنطقة`,
    description: (source, currency) =>
      `مصدر السعر: ${source}. مرتبة من الأقل إلى الأعلى حسب القيمة المحولة إلى ${currency}.`,
    regionCount: (count) => `${count} منطقة`,
    allSources: "جميع المصادر",
    webLead: "سعر الموقع الرسمي",
    googlePlayLead: "سعر Google Play",
    allDiagnostics: "مصادر أخرى",
    usd: "الدولار الأمريكي USD",
    usdEquivalent: "ما يعادله بالدولار",
    usdSort: "القيمة بالدولار",
    cnyEstimate: "تقدير اليوان CNY",
    cnySort: "القيمة المقدرة باليوان",
    perMonth: "/شهرياً",
    rank: "الترتيب",
    region: "المنطقة",
    localPrice: "السعر المحلي",
    vsUs: "مقارنة بأمريكا",
    taxNote: "ملاحظة ضريبية",
    source: "المصدر",
    statusRisk: "المستوى والمخاطر",
    sameAsUs: "مثل السعر الأمريكي",
    aboveUs: (percent) => `أغلى من أمريكا بنسبة ${percent}%`,
    belowUs: (percent) => `أرخص من أمريكا بنسبة ${percent}%`,
    statusLow: "منخفض",
    statusHigh: "مرتفع",
    statusAbove: "أعلى من المعتاد",
    statusBase: "المعيار",
    riskLow: "منخفضة",
    riskMedium: "متوسطة",
    riskHigh: "مرتفعة",
    riskNeedsReview: "تحتاج مراجعة",
    riskPrefix: (label) => `المخاطر: ${label}`,
    riskFallback:
      "قد تتأثر الاشتراكات عبر المناطق بمنطقة الحساب وطريقة الدفع وضوابط المخاطر لدى المنصة.",
    taxInferred: "تقدير المنصة",
    taxVerified: "موثّق",
    taxMedium: "ثقة متوسطة",
    taxNeedsReview: "تحتاج مراجعة",
    taxUnverified: "غير موثّق",
    checkoutApplies: "السعر عند الدفع هو المعتمد",
    taxVerifiedHelp: "الملف الضريبي موثّق ومأخوذ من قاعدة بيانات الضرائب الخاصة بالدولة.",
    taxInferredHelp:
      "تقدير مبني على آلية فوترة App Store؛ يظل السعر النهائي في صفحة الدفع هو المعتمد.",
    taxMediumHelp:
      "الملف مبني على بيانات ضريبية وطنية أو إقليمية ويحتاج إلى مراجعة دورية.",
    taxUnverifiedHelp:
      "لم يُوثّق الملف الضريبي بعد؛ يظل السعر النهائي في صفحة الدفع هو المعتمد.",
    taxRankingPolicy:
      "لا تضيف GeoSub الضريبة مرة أخرى؛ يعتمد الترتيب على سعر App Store المعلن بعد تحويله إلى الدولار.",
    priceCollected: "تاريخ جمع السعر",
    fxBasis: "تاريخ سعر الصرف",
    convertedHelp: "يحوّل الأسعار المحلية إلى عملة موحدة لتسهيل المقارنة.",
    vsUsHelp: "يستخدم السعر الأمريكي معياراً ويوضح مقدار انخفاض أو ارتفاع كل منطقة.",
    taxHelp:
      "ملاحظات ضريبة القيمة المضافة أو GST أو ضريبة الاستهلاك والمبيعات للإحاطة فقط. لا يضيف الترتيب الضريبة مرة أخرى؛ يظل سعر الدفع في App Store هو المعتمد.",
    riskHelp:
      "يقارن المستوى كل منطقة بالمعيار الأمريكي. وتعكس المخاطر منطقة الحساب وطريقة الدفع وبيانات الفوترة وضوابط المنصة.",
    empty: (source) => `لا تتوفر أسعار ${source} بعد.`,
    showMore: (count) => `عرض ${count} مناطق إضافية`,
    collapse: "عرض مناطق أقل",
    riskNote:
      "تنبيه: تعرض GeoSub فروق الأسعار العامة لمقارنة تكاليف الاشتراكات ولا تشجع على تجاوز قواعد المنصة. قد تتأثر الاشتراكات عبر المناطق بمنطقة Apple ID وطريقة الدفع وبيانات الفوترة والضرائب وضوابط المخاطر. يعتمد التوفر النهائي على صفحة الدفع الرسمية.",
    helpAria: (label, help) => `${label}: ${help}`,
  },
  fr: {
    eyebrow: "Prix par région", title: (plan) => `Prix de ${plan} par région`,
    description: (source, currency) => `Source : ${source}. Classement du moins cher au plus cher selon la valeur convertie en ${currency}.`,
    regionCount: (count) => `${count} régions`, allSources: "Toutes les sources", webLead: "Prix du site officiel",
    googlePlayLead: "Prix Google Play", allDiagnostics: "Autres sources", usd: "Dollar américain USD",
    usdEquivalent: "Équivalent en dollars", usdSort: "Valeur en dollars", cnyEstimate: "Estimation en yuans CNY",
    cnySort: "Valeur estimée en yuans", perMonth: "/mois", rank: "Rang", region: "Région",
    localPrice: "Prix local", vsUs: "Écart avec les États-Unis", taxNote: "Fiscalité", source: "Source",
    statusRisk: "Niveau et risque", sameAsUs: "Même prix qu’aux États-Unis",
    aboveUs: (p) => `${p}% plus cher qu’aux États-Unis`, belowUs: (p) => `${p}% moins cher qu’aux États-Unis`,
    statusLow: "Bas", statusHigh: "Élevé", statusAbove: "Au-dessus de la normale", statusBase: "Référence",
    riskLow: "faible", riskMedium: "modéré", riskHigh: "élevé", riskNeedsReview: "à vérifier",
    riskPrefix: (label) => `Risque : ${label}`,
    riskFallback: "Un abonnement souscrit dans une autre région peut dépendre du pays du compte, du moyen de paiement et des contrôles de la plateforme.",
    taxInferred: "Estimation de la plateforme", taxVerified: "Vérifié", taxMedium: "Confiance moyenne",
    taxNeedsReview: "À vérifier", taxUnverified: "Non vérifié", checkoutApplies: "Le montant au paiement prévaut",
    taxVerifiedHelp: "Le profil fiscal est vérifié à partir de la base fiscale du pays.",
    taxInferredHelp: "Estimation fondée sur la facturation App Store ; le montant final au paiement prévaut.",
    taxMediumHelp: "Le profil repose sur des données fiscales nationales ou régionales et doit être revu périodiquement.",
    taxUnverifiedHelp: "Le profil fiscal n’est pas encore vérifié ; le montant final au paiement prévaut.",
    taxRankingPolicy: "GeoSub ne rajoute pas les taxes. Le classement utilise le prix App Store affiché, converti en dollars.",
    priceCollected: "Prix relevé le", fxBasis: "Taux de change du",
    convertedHelp: "Convertit les prix locaux dans une monnaie commune pour faciliter la comparaison.",
    vsUsHelp: "Prend le prix américain comme référence et indique l’écart de chaque région.",
    taxHelp: "Les indications de TVA, GST et taxes sur les ventes sont informatives. Aucune taxe n’est rajoutée au classement ; le montant App Store au paiement prévaut.",
    riskHelp: "Le niveau compare la région à la référence américaine. Le risque tient compte du pays du compte, du paiement, de la facturation et des contrôles de la plateforme.",
    empty: (source) => `Aucun prix ${source} disponible.`, showMore: (count) => `Afficher ${count} régions supplémentaires`,
    collapse: "Afficher moins de régions",
    riskNote: "Avertissement : GeoSub présente les écarts de prix publics à titre comparatif et n’encourage pas le contournement des règles. La disponibilité finale dépend de la page de paiement officielle.",
    helpAria: (label, help) => `${label} : ${help}`,
  },
  it: {
    eyebrow: "Prezzi per regione", title: (plan) => `Prezzi di ${plan} per regione`,
    description: (source, currency) => `Fonte: ${source}. Ordinati dal meno caro al più caro in base al valore convertito in ${currency}.`,
    regionCount: (count) => `${count} regioni`, allSources: "Tutte le fonti", webLead: "Prezzo del sito ufficiale",
    googlePlayLead: "Prezzo Google Play", allDiagnostics: "Altre fonti", usd: "Dollaro statunitense USD",
    usdEquivalent: "Equivalente in dollari", usdSort: "Valore in dollari", cnyEstimate: "Stima in yuan CNY",
    cnySort: "Valore stimato in yuan", perMonth: "/mese", rank: "Posizione", region: "Regione",
    localPrice: "Prezzo locale", vsUs: "Confronto con gli Stati Uniti", taxNote: "Nota fiscale", source: "Fonte",
    statusRisk: "Livello e rischio", sameAsUs: "Uguale agli Stati Uniti",
    aboveUs: (p) => `${p}% più caro degli Stati Uniti`, belowUs: (p) => `${p}% meno caro degli Stati Uniti`,
    statusLow: "Basso", statusHigh: "Alto", statusAbove: "Sopra la media", statusBase: "Riferimento",
    riskLow: "basso", riskMedium: "medio", riskHigh: "alto", riskNeedsReview: "da verificare",
    riskPrefix: (label) => `Rischio: ${label}`,
    riskFallback: "Gli abbonamenti tra regioni possono dipendere dal paese dell’account, dal metodo di pagamento e dai controlli della piattaforma.",
    taxInferred: "Stima della piattaforma", taxVerified: "Verificato", taxMedium: "Affidabilità media",
    taxNeedsReview: "Da verificare", taxUnverified: "Non verificato", checkoutApplies: "Fa fede il prezzo al pagamento",
    taxVerifiedHelp: "Il profilo fiscale è verificato mediante la banca dati fiscale del paese.",
    taxInferredHelp: "Stima basata sulla fatturazione App Store; fa fede l’importo finale al pagamento.",
    taxMediumHelp: "Il profilo si basa su dati fiscali nazionali o regionali e richiede verifiche periodiche.",
    taxUnverifiedHelp: "Il profilo fiscale non è ancora verificato; fa fede l’importo finale al pagamento.",
    taxRankingPolicy: "GeoSub non aggiunge nuovamente le imposte. La classifica usa il prezzo App Store visualizzato, convertito in dollari.",
    priceCollected: "Prezzo rilevato il", fxBasis: "Cambio del",
    convertedHelp: "Converte i prezzi locali in una valuta comune per agevolare il confronto.",
    vsUsHelp: "Usa il prezzo statunitense come riferimento e mostra la differenza per ogni regione.",
    taxHelp: "Le note su IVA, GST e imposte sulle vendite sono informative. La classifica non aggiunge imposte; fa fede il prezzo App Store al pagamento.",
    riskHelp: "Il livello confronta la regione con il riferimento statunitense. Il rischio considera paese dell’account, pagamento, fatturazione e controlli della piattaforma.",
    empty: (source) => `Nessun prezzo ${source} disponibile.`, showMore: (count) => `Mostra altre ${count} regioni`,
    collapse: "Mostra meno regioni",
    riskNote: "Avvertenza: GeoSub mostra differenze di prezzo pubbliche a scopo comparativo e non incoraggia l’elusione delle regole. La disponibilità finale dipende dalla pagina di pagamento ufficiale.",
    helpAria: (label, help) => `${label}: ${help}`,
  },
  de: {
    eyebrow: "Regionale Preise", title: (plan) => `${plan}: Preise nach Region`,
    description: (source, currency) => `Quelle: ${source}. Nach dem umgerechneten Wert in ${currency} aufsteigend sortiert.`,
    regionCount: (count) => `${count} Regionen`, allSources: "Alle Quellen", webLead: "Preis der offiziellen Website",
    googlePlayLead: "Google-Play-Preis", allDiagnostics: "Weitere Quellen", usd: "US-Dollar USD",
    usdEquivalent: "Dollarwert", usdSort: "Wert in US-Dollar", cnyEstimate: "Geschätzter Yuanwert CNY",
    cnySort: "Geschätzter Yuanwert", perMonth: "/Monat", rank: "Rang", region: "Region",
    localPrice: "Lokaler Preis", vsUs: "Vergleich mit den USA", taxNote: "Steuerhinweis", source: "Quelle",
    statusRisk: "Niveau und Risiko", sameAsUs: "Gleicher Preis wie in den USA",
    aboveUs: (p) => `${p}% teurer als in den USA`, belowUs: (p) => `${p}% günstiger als in den USA`,
    statusLow: "Niedrig", statusHigh: "Hoch", statusAbove: "Über dem Normalwert", statusBase: "Referenz",
    riskLow: "niedrig", riskMedium: "mittel", riskHigh: "hoch", riskNeedsReview: "zu prüfen",
    riskPrefix: (label) => `Risiko: ${label}`,
    riskFallback: "Regionsübergreifende Abonnements können von Kontoland, Zahlungsmethode und Plattformprüfungen abhängen.",
    taxInferred: "Plattformschätzung", taxVerified: "Geprüft", taxMedium: "Mittlere Verlässlichkeit",
    taxNeedsReview: "Prüfung nötig", taxUnverified: "Ungeprüft", checkoutApplies: "Der Betrag beim Bezahlen gilt",
    taxVerifiedHelp: "Das Steuerprofil wurde anhand der Steuerdatenbank des Landes geprüft.",
    taxInferredHelp: "Schätzung auf Basis der App-Store-Abrechnung; maßgeblich ist der Endbetrag beim Bezahlen.",
    taxMediumHelp: "Das Profil beruht auf nationalen oder regionalen Steuerdaten und sollte regelmäßig geprüft werden.",
    taxUnverifiedHelp: "Das Steuerprofil ist noch ungeprüft; maßgeblich ist der Endbetrag beim Bezahlen.",
    taxRankingPolicy: "GeoSub schlägt Steuern nicht erneut auf. Die Rangliste verwendet den angezeigten App-Store-Preis in US-Dollar.",
    priceCollected: "Preiserhebung", fxBasis: "Wechselkursdatum",
    convertedHelp: "Rechnet lokale Preise für einen leichteren Vergleich in eine gemeinsame Währung um.",
    vsUsHelp: "Nutzt den US-Preis als Referenz und zeigt die Abweichung jeder Region.",
    taxHelp: "Hinweise zu MwSt., GST und Verkaufssteuern dienen nur zur Information. Die Rangliste schlägt keine Steuer auf; maßgeblich ist der App-Store-Endpreis.",
    riskHelp: "Das Niveau vergleicht die Region mit der US-Referenz. Das Risiko berücksichtigt Kontoland, Zahlung, Rechnungsdaten und Plattformprüfungen.",
    empty: (source) => `Noch keine ${source}-Preise verfügbar.`, showMore: (count) => `${count} weitere Regionen anzeigen`,
    collapse: "Weniger Regionen anzeigen",
    riskNote: "Hinweis: GeoSub zeigt öffentliche Preisunterschiede zum Vergleich und empfiehlt keine Umgehung von Plattformregeln. Die endgültige Verfügbarkeit richtet sich nach der offiziellen Zahlungsseite.",
    helpAria: (label, help) => `${label}: ${help}`,
  },
  pt: {
    eyebrow: "Preços por região", title: (plan) => `Preços de ${plan} por região`,
    description: (source, currency) => `Fonte: ${source}. Ordenados do mais barato ao mais caro pelo valor convertido em ${currency}.`,
    regionCount: (count) => `${count} regiões`, allSources: "Todas as fontes", webLead: "Preço do site oficial",
    googlePlayLead: "Preço do Google Play", allDiagnostics: "Outras fontes", usd: "Dólar americano USD",
    usdEquivalent: "Equivalente em dólares", usdSort: "Valor em dólares", cnyEstimate: "Estimativa em yuan CNY",
    cnySort: "Valor estimado em yuan", perMonth: "/mês", rank: "Posição", region: "Região",
    localPrice: "Preço local", vsUs: "Comparação com os EUA", taxNote: "Nota fiscal", source: "Fonte",
    statusRisk: "Nível e risco", sameAsUs: "Mesmo preço dos EUA",
    aboveUs: (p) => `${p}% mais caro do que nos EUA`, belowUs: (p) => `${p}% mais barato do que nos EUA`,
    statusLow: "Baixo", statusHigh: "Alto", statusAbove: "Acima do normal", statusBase: "Referência",
    riskLow: "baixo", riskMedium: "médio", riskHigh: "alto", riskNeedsReview: "a verificar",
    riskPrefix: (label) => `Risco: ${label}`,
    riskFallback: "As assinaturas entre regiões podem depender do país da conta, do método de pagamento e dos controlos da plataforma.",
    taxInferred: "Estimativa da plataforma", taxVerified: "Verificado", taxMedium: "Confiança média",
    taxNeedsReview: "A verificar", taxUnverified: "Não verificado", checkoutApplies: "Prevalece o valor no pagamento",
    taxVerifiedHelp: "O perfil fiscal foi verificado com base na base de dados fiscal do país.",
    taxInferredHelp: "Estimativa baseada na faturação da App Store; prevalece o valor final no pagamento.",
    taxMediumHelp: "O perfil baseia-se em dados fiscais nacionais ou regionais e requer revisão periódica.",
    taxUnverifiedHelp: "O perfil fiscal ainda não foi verificado; prevalece o valor final no pagamento.",
    taxRankingPolicy: "O GeoSub não volta a acrescentar impostos. A classificação usa o preço apresentado na App Store, convertido em dólares.",
    priceCollected: "Preço recolhido em", fxBasis: "Câmbio de",
    convertedHelp: "Converte preços locais para uma moeda comum, facilitando a comparação.",
    vsUsHelp: "Usa o preço dos EUA como referência e mostra a diferença de cada região.",
    taxHelp: "As notas sobre IVA, GST e impostos sobre vendas são informativas. A classificação não volta a adicionar impostos; prevalece o preço da App Store no pagamento.",
    riskHelp: "O nível compara a região com a referência dos EUA. O risco considera país da conta, pagamento, faturação e controlos da plataforma.",
    empty: (source) => `Ainda não há preços de ${source}.`, showMore: (count) => `Mostrar mais ${count} regiões`,
    collapse: "Mostrar menos regiões",
    riskNote: "Aviso: o GeoSub apresenta diferenças de preços públicas para comparação e não incentiva o contorno das regras. A disponibilidade final depende da página oficial de pagamento.",
    helpAria: (label, help) => `${label}: ${help}`,
  },
} satisfies Record<
  Exclude<PreparedSiteLocale, "zh" | "zh-tw" | "en">,
  RegionPriceTableCopy
>;

export function getRegionPriceTableCopy(
  locale: PreparedSiteLocale,
): RegionPriceTableCopy {
  if (locale === "zh-tw") {
    return toTraditionalChinese(
      getPublicPricingCopy("zh").table,
    ) as RegionPriceTableCopy;
  }

  if (locale === "zh" || locale === "en") {
    return getPublicPricingCopy(locale).table as RegionPriceTableCopy;
  }

  return preparedRegionPriceTableCopy[locale];
}
