import type { RegionPrice } from "./public-pricing-model.ts";
import type { PreparedSiteLocale } from "./site-locale.ts";

export const REGION_COMPARISON_LIMIT = 3;

type DecisionCopy = {
  compare: string;
  selected: (count: number) => string;
  selectRegion: (country: string) => string;
  removeRegion: (country: string) => string;
  compareLimit: string;
  comparisonTitle: string;
  comparisonIntro: string;
  clearComparison: string;
  evidence: string;
  hideEvidence: string;
  evidenceTitle: (country: string) => string;
  localPrice: string;
  convertedPrice: string;
  referenceDifference: string;
  taxStatus: string;
  source: string;
  sourceUnavailable: string;
  priceDate: string;
  fxDate: string;
  accessConditions: string;
};

const englishCopy: DecisionCopy = {
  compare: "Compare",
  selected: (count) => `${count}/${REGION_COMPARISON_LIMIT} selected`,
  selectRegion: (country) => `Add ${country} to comparison`,
  removeRegion: (country) => `Remove ${country} from comparison`,
  compareLimit: `Compare up to ${REGION_COMPARISON_LIMIT} regions at a time.`,
  comparisonTitle: "Region comparison",
  comparisonIntro: "Compare the listed price and evidence before choosing a region.",
  clearComparison: "Clear comparison",
  evidence: "View evidence",
  hideEvidence: "Hide evidence",
  evidenceTitle: (country) => `${country} price evidence`,
  localPrice: "Local listed price",
  convertedPrice: "Converted price",
  referenceDifference: "Difference from reference",
  taxStatus: "Tax information",
  source: "Official source",
  sourceUnavailable: "No public source link",
  priceDate: "Price collected",
  fxDate: "Exchange-rate basis",
  accessConditions: "Subscription conditions",
};

const copyByLocale = {
  zh: {
    ...englishCopy,
    compare: "比较",
    selected: (count: number) => `已选 ${count}/${REGION_COMPARISON_LIMIT}`,
    selectRegion: (country: string) => `将${country}加入比较`,
    removeRegion: (country: string) => `将${country}移出比较`,
    compareLimit: `每次最多比较 ${REGION_COMPARISON_LIMIT} 个地区。`,
    comparisonTitle: "地区对比",
    comparisonIntro: "先比较公开价格和证据，再判断哪个地区更适合你。",
    clearComparison: "清空比较",
    evidence: "查看证据",
    hideEvidence: "收起证据",
    evidenceTitle: (country: string) => `${country}价格证据`,
    localPrice: "当地标价",
    convertedPrice: "折算价格",
    referenceDifference: "相对基准",
    taxStatus: "税务信息",
    source: "官方来源",
    sourceUnavailable: "暂无公开来源链接",
    priceDate: "价格采集",
    fxDate: "汇率基准",
    accessConditions: "订阅条件",
  },
  "zh-tw": {
    ...englishCopy,
    compare: "比較",
    selected: (count: number) => `已選 ${count}/${REGION_COMPARISON_LIMIT}`,
    selectRegion: (country: string) => `將${country}加入比較`,
    removeRegion: (country: string) => `將${country}移出比較`,
    compareLimit: `每次最多比較 ${REGION_COMPARISON_LIMIT} 個地區。`,
    comparisonTitle: "地區比較",
    comparisonIntro: "先比較公開價格與證據，再判斷哪個地區更適合你。",
    clearComparison: "清除比較",
    evidence: "查看證據",
    hideEvidence: "收起證據",
    evidenceTitle: (country: string) => `${country}價格證據`,
    localPrice: "當地標價",
    convertedPrice: "換算價格",
    referenceDifference: "相對基準",
    taxStatus: "稅務資訊",
    source: "官方來源",
    sourceUnavailable: "暫無公開來源連結",
    priceDate: "價格採集",
    fxDate: "匯率基準",
    accessConditions: "訂閱條件",
  },
  en: englishCopy,
  ja: {
    ...englishCopy,
    compare: "比較",
    selected: (count: number) => `${count}/${REGION_COMPARISON_LIMIT} 件選択`,
    selectRegion: (country: string) => `${country}を比較に追加`,
    removeRegion: (country: string) => `${country}を比較から削除`,
    compareLimit: `一度に比較できるのは最大 ${REGION_COMPARISON_LIMIT} 地域です。`,
    comparisonTitle: "地域比較",
    comparisonIntro: "表示価格と根拠を確認してから地域を比較できます。",
    clearComparison: "比較をクリア",
    evidence: "根拠を表示",
    hideEvidence: "根拠を閉じる",
    evidenceTitle: (country: string) => `${country}の価格根拠`,
    localPrice: "現地表示価格",
    convertedPrice: "換算価格",
    referenceDifference: "基準との差",
    taxStatus: "税情報",
    source: "公式ソース",
    sourceUnavailable: "公開ソースリンクなし",
    priceDate: "価格取得日",
    fxDate: "為替基準日",
    accessConditions: "契約条件",
  },
  ko: {
    ...englishCopy,
    compare: "비교",
    selected: (count: number) => `${count}/${REGION_COMPARISON_LIMIT}개 선택`,
    selectRegion: (country: string) => `${country} 비교에 추가`,
    removeRegion: (country: string) => `${country} 비교에서 제거`,
    compareLimit: `한 번에 최대 ${REGION_COMPARISON_LIMIT}개 지역을 비교할 수 있습니다.`,
    comparisonTitle: "지역 비교",
    comparisonIntro: "표시 가격과 근거를 확인한 뒤 지역을 비교하세요.",
    clearComparison: "비교 지우기",
    evidence: "근거 보기",
    hideEvidence: "근거 닫기",
    evidenceTitle: (country: string) => `${country} 가격 근거`,
    localPrice: "현지 표시 가격",
    convertedPrice: "환산 가격",
    referenceDifference: "기준 대비",
    taxStatus: "세금 정보",
    source: "공식 출처",
    sourceUnavailable: "공개 출처 링크 없음",
    priceDate: "가격 수집일",
    fxDate: "환율 기준일",
    accessConditions: "구독 조건",
  },
  es: {
    ...englishCopy,
    compare: "Comparar",
    selected: (count: number) => `${count}/${REGION_COMPARISON_LIMIT} seleccionadas`,
    selectRegion: (country: string) => `Añadir ${country} a la comparación`,
    removeRegion: (country: string) => `Quitar ${country} de la comparación`,
    compareLimit: `Puedes comparar hasta ${REGION_COMPARISON_LIMIT} regiones a la vez.`,
    comparisonTitle: "Comparación regional",
    comparisonIntro: "Compara el precio publicado y sus pruebas antes de elegir una región.",
    clearComparison: "Borrar comparación",
    evidence: "Ver pruebas",
    hideEvidence: "Ocultar pruebas",
    evidenceTitle: (country: string) => `Pruebas del precio en ${country}`,
    localPrice: "Precio local publicado",
    convertedPrice: "Precio convertido",
    referenceDifference: "Diferencia frente a la referencia",
    taxStatus: "Información fiscal",
    source: "Fuente oficial",
    sourceUnavailable: "Sin enlace público a la fuente",
    priceDate: "Precio recopilado",
    fxDate: "Base del tipo de cambio",
    accessConditions: "Condiciones de suscripción",
  },
  tr: {
    ...englishCopy,
    compare: "Karşılaştır",
    selected: (count: number) => `${count}/${REGION_COMPARISON_LIMIT} seçildi`,
    selectRegion: (country: string) => `${country} bölgesini karşılaştırmaya ekle`,
    removeRegion: (country: string) => `${country} bölgesini karşılaştırmadan çıkar`,
    compareLimit: `Aynı anda en fazla ${REGION_COMPARISON_LIMIT} bölge karşılaştırabilirsiniz.`,
    comparisonTitle: "Bölge karşılaştırması",
    comparisonIntro: "Bir bölge seçmeden önce listelenen fiyatı ve kanıtları karşılaştırın.",
    clearComparison: "Karşılaştırmayı temizle",
    evidence: "Kanıtları göster",
    hideEvidence: "Kanıtları gizle",
    evidenceTitle: (country: string) => `${country} fiyat kanıtları`,
    localPrice: "Yerel liste fiyatı",
    convertedPrice: "Dönüştürülmüş fiyat",
    referenceDifference: "Referansa göre fark",
    taxStatus: "Vergi bilgisi",
    source: "Resmî kaynak",
    sourceUnavailable: "Herkese açık kaynak bağlantısı yok",
    priceDate: "Fiyatın toplandığı tarih",
    fxDate: "Kur baz tarihi",
    accessConditions: "Abonelik koşulları",
  },
  ar: {
    ...englishCopy,
    compare: "مقارنة",
    selected: (count: number) => `تم اختيار ${count}/${REGION_COMPARISON_LIMIT}`,
    selectRegion: (country: string) => `إضافة ${country} إلى المقارنة`,
    removeRegion: (country: string) => `إزالة ${country} من المقارنة`,
    compareLimit: `يمكن مقارنة ${REGION_COMPARISON_LIMIT} مناطق كحد أقصى في المرة الواحدة.`,
    comparisonTitle: "مقارنة المناطق",
    comparisonIntro: "قارن السعر المنشور والأدلة قبل اختيار المنطقة.",
    clearComparison: "مسح المقارنة",
    evidence: "عرض الأدلة",
    hideEvidence: "إخفاء الأدلة",
    evidenceTitle: (country: string) => `أدلة السعر في ${country}`,
    localPrice: "السعر المحلي المعروض",
    convertedPrice: "السعر بعد التحويل",
    referenceDifference: "الفرق عن السعر المرجعي",
    taxStatus: "المعلومات الضريبية",
    source: "المصدر الرسمي",
    sourceUnavailable: "لا يوجد رابط عام للمصدر",
    priceDate: "تاريخ جمع السعر",
    fxDate: "تاريخ أساس سعر الصرف",
    accessConditions: "شروط الاشتراك",
  },
  fr: {
    ...englishCopy,
    compare: "Comparer",
    selected: (count: number) => `${count}/${REGION_COMPARISON_LIMIT} sélectionnées`,
    selectRegion: (country: string) => `Ajouter ${country} à la comparaison`,
    removeRegion: (country: string) => `Retirer ${country} de la comparaison`,
    compareLimit: `Vous pouvez comparer jusqu’à ${REGION_COMPARISON_LIMIT} régions à la fois.`,
    comparisonTitle: "Comparaison des régions",
    comparisonIntro: "Comparez le prix affiché et ses preuves avant de choisir une région.",
    clearComparison: "Effacer la comparaison",
    evidence: "Voir les preuves",
    hideEvidence: "Masquer les preuves",
    evidenceTitle: (country: string) => `Preuves du prix pour ${country}`,
    localPrice: "Prix local affiché",
    convertedPrice: "Prix converti",
    referenceDifference: "Écart par rapport à la référence",
    taxStatus: "Informations fiscales",
    source: "Source officielle",
    sourceUnavailable: "Aucun lien public vers la source",
    priceDate: "Prix relevé le",
    fxDate: "Date de référence du taux",
    accessConditions: "Conditions d’abonnement",
  },
  it: {
    ...englishCopy,
    compare: "Confronta",
    selected: (count: number) => `${count}/${REGION_COMPARISON_LIMIT} selezionate`,
    selectRegion: (country: string) => `Aggiungi ${country} al confronto`,
    removeRegion: (country: string) => `Rimuovi ${country} dal confronto`,
    compareLimit: `Puoi confrontare fino a ${REGION_COMPARISON_LIMIT} regioni alla volta.`,
    comparisonTitle: "Confronto tra regioni",
    comparisonIntro: "Confronta il prezzo indicato e le prove prima di scegliere una regione.",
    clearComparison: "Cancella confronto",
    evidence: "Vedi prove",
    hideEvidence: "Nascondi prove",
    evidenceTitle: (country: string) => `Prove del prezzo per ${country}`,
    localPrice: "Prezzo locale indicato",
    convertedPrice: "Prezzo convertito",
    referenceDifference: "Differenza dal riferimento",
    taxStatus: "Informazioni fiscali",
    source: "Fonte ufficiale",
    sourceUnavailable: "Nessun link pubblico alla fonte",
    priceDate: "Prezzo rilevato",
    fxDate: "Data di riferimento del cambio",
    accessConditions: "Condizioni di abbonamento",
  },
  de: {
    ...englishCopy,
    compare: "Vergleichen",
    selected: (count: number) => `${count}/${REGION_COMPARISON_LIMIT} ausgewählt`,
    selectRegion: (country: string) => `${country} zum Vergleich hinzufügen`,
    removeRegion: (country: string) => `${country} aus dem Vergleich entfernen`,
    compareLimit: `Sie können bis zu ${REGION_COMPARISON_LIMIT} Regionen gleichzeitig vergleichen.`,
    comparisonTitle: "Regionen vergleichen",
    comparisonIntro: "Vergleichen Sie Listenpreis und Belege, bevor Sie eine Region auswählen.",
    clearComparison: "Vergleich leeren",
    evidence: "Belege anzeigen",
    hideEvidence: "Belege ausblenden",
    evidenceTitle: (country: string) => `Preisbelege für ${country}`,
    localPrice: "Lokaler Listenpreis",
    convertedPrice: "Umgerechneter Preis",
    referenceDifference: "Abweichung zur Referenz",
    taxStatus: "Steuerinformationen",
    source: "Offizielle Quelle",
    sourceUnavailable: "Kein öffentlicher Quellenlink",
    priceDate: "Preis erhoben am",
    fxDate: "Wechselkursbasis",
    accessConditions: "Abonnementbedingungen",
  },
  pt: {
    ...englishCopy,
    compare: "Comparar",
    selected: (count: number) => `${count}/${REGION_COMPARISON_LIMIT} selecionadas`,
    selectRegion: (country: string) => `Adicionar ${country} à comparação`,
    removeRegion: (country: string) => `Remover ${country} da comparação`,
    compareLimit: `Você pode comparar até ${REGION_COMPARISON_LIMIT} regiões por vez.`,
    comparisonTitle: "Comparação entre regiões",
    comparisonIntro: "Compare o preço publicado e as evidências antes de escolher uma região.",
    clearComparison: "Limpar comparação",
    evidence: "Ver evidências",
    hideEvidence: "Ocultar evidências",
    evidenceTitle: (country: string) => `Evidências de preço para ${country}`,
    localPrice: "Preço local publicado",
    convertedPrice: "Preço convertido",
    referenceDifference: "Diferença para a referência",
    taxStatus: "Informações fiscais",
    source: "Fonte oficial",
    sourceUnavailable: "Sem link público para a fonte",
    priceDate: "Preço coletado em",
    fxDate: "Data-base do câmbio",
    accessConditions: "Condições da assinatura",
  },
} satisfies Record<PreparedSiteLocale, DecisionCopy>;

export function getRegionComparisonKey(region: RegionPrice) {
  return [
    region.code.toUpperCase(),
    (region.billingPlatform || "unknown").toLowerCase(),
    region.currencyCode || "",
    region.localPrice,
  ].join("::");
}

export function toggleRegionComparison(
  selectedKeys: string[],
  regionKey: string,
  limit = REGION_COMPARISON_LIMIT,
) {
  if (selectedKeys.includes(regionKey)) {
    return selectedKeys.filter((key) => key !== regionKey);
  }

  if (selectedKeys.length >= limit) return selectedKeys;
  return [...selectedKeys, regionKey];
}

export function getRegionPriceDecisionCopy(locale: PreparedSiteLocale) {
  return copyByLocale[locale] || englishCopy;
}
