import type { SiteLocale } from '../lib/site-locale';

export type ShareCopy = {
  button: string;
  dialogLabel: string;
  close: string;
  global: string;
  cardTitle: (productName: string) => string;
  planBadge: (planName: string, referencePrice: string) => string;
  cheapestRegion: string;
  tiedCheapestRegion: (count: number) => string;
  highestRegion: string;
  maxSpread: string;
  coverage: (count: number) => string;
  priceSource: string;
  fxDate: string;
  cheaper: string;
  usBase: string;
  moreExpensive: string;
  cheapestList: string;
  expensiveList: string;
  verifiedAt: (date: string) => string;
  download: string;
  downloading: string;
  copyLink: string;
  copied: string;
  copyFailed: string;
  shareText: (planName: string, low: string, high: string, spread: number) => string;
  mapAria: (planName: string) => string;
  shareTo: (platform: string) => string;
  diffAbove: (percent: number) => string;
  diffBelow: (percent: number) => string;
  diffSame: string;
  comparisonLead: (lowest: string, highest: string) => string;
  comparisonTrail: string;
  monthlySuffix: string;
};

export const shareCopy = {
  zh: {
    button: '分享价格图',
    dialogLabel: '分享价格图',
    close: '关闭弹窗',
    global: '全球',
    cardTitle: (productName) => `${productName} 各地区价格`,
    planBadge: (planName, referencePrice) => `${planName} 套餐 · 美国基准 ${referencePrice}`,
    cheapestRegion: '最低价地区',
    tiedCheapestRegion: (count) => `${count} 个地区并列最低`,
    highestRegion: '最高价地区',
    maxSpread: '全球最高与最低价格跨度',
    coverage: (count) => `已核验 ${count} 个地区`,
    priceSource: '价格来源',
    fxDate: '汇率日期',
    cheaper: '更便宜',
    usBase: '美国基准',
    moreExpensive: '更贵',
    cheapestList: '↓ 最便宜',
    expensiveList: '↑ 最贵',
    verifiedAt: (date) => `GeoSub · 数据校验于 ${date} · geosub.org`,
    download: '下载 PNG',
    downloading: '正在生成...',
    copyLink: '复制链接',
    copied: '已复制',
    copyFailed: '复制失败',
    shareText: (planName, low, high, spread) =>
      `${planName} 全球订阅价格对比：最低 ${low}，最高 ${high}，价差 ${spread}%。`,
    mapAria: (planName) => `${planName} 分享地图`,
    shareTo: (platform) => `分享到 ${platform}`,
    diffAbove: (percent) => `比美国贵 ${percent}%`,
    diffBelow: (percent) => `比美国便宜 ${percent}%`,
    diffSame: '与美国价格相同',
    comparisonLead: (lowest, highest) => `${lowest} 与 ${highest} 的价格差约 `,
    comparisonTrail: '。',
    monthlySuffix: '/月',
  },
  "zh-tw": {
    button: "分享價格圖",
    dialogLabel: "分享價格圖",
    close: "關閉彈窗",
    global: "全球",
    cardTitle: (productName) => `${productName} 各地區價格`,
    planBadge: (planName, referencePrice) => `${planName} 套餐 · 美國基準 ${referencePrice}`,
    cheapestRegion: "最低價地區",
    tiedCheapestRegion: (count) => `${count} 個地區並列最低`,
    highestRegion: "最高價地區",
    maxSpread: "全球最高與最低價格跨度",
    coverage: (count) => `已核驗 ${count} 個地區`,
    priceSource: "價格來源",
    fxDate: "匯率日期",
    cheaper: "更便宜",
    usBase: "美國基準",
    moreExpensive: "更貴",
    cheapestList: "↓ 最便宜",
    expensiveList: "↑ 最貴",
    verifiedAt: (date) => `GeoSub · 資料校驗於 ${date} · geosub.org`,
    download: "下載 PNG",
    downloading: "正在生成...",
    copyLink: "複製連結",
    copied: "已複製",
    copyFailed: "複製失敗",
    shareText: (planName, low, high, spread) => `${planName} 全球訂閱價格對比：最低 ${low}，最高 ${high}，價差 ${spread}%。`,
    mapAria: (planName) => `${planName} 分享地圖`,
    shareTo: (platform) => `分享到 ${platform}`,
    diffAbove: (percent) => `比美國貴 ${percent}%`,
    diffBelow: (percent) => `比美國便宜 ${percent}%`,
    diffSame: "與美國價格相同",
    comparisonLead: (lowest, highest) => `${lowest} 與 ${highest} 的價格差約 `,
    comparisonTrail: "。",
    monthlySuffix: "/月",
},
  en: {
    button: 'Share price card',
    dialogLabel: 'Share price card',
    close: 'Close dialog',
    global: 'Global',
    cardTitle: (productName) => `${productName} regional prices`,
    planBadge: (planName, referencePrice) => `${planName} plan · US base ${referencePrice}`,
    cheapestRegion: 'Lowest-price region',
    tiedCheapestRegion: (count) => `${count} regions tied for lowest`,
    highestRegion: 'Highest-price region',
    maxSpread: 'Global highest-to-lowest price spread',
    coverage: (count) => `${count} verified regions`,
    priceSource: 'Pricing source',
    fxDate: 'FX date',
    cheaper: 'Cheaper',
    usBase: 'US base',
    moreExpensive: 'More expensive',
    cheapestList: '↓ Cheapest',
    expensiveList: '↑ Most expensive',
    verifiedAt: (date) => `GeoSub · Data verified ${date} · geosub.org`,
    download: 'Download PNG',
    downloading: 'Generating...',
    copyLink: 'Copy link',
    copied: 'Copied',
    copyFailed: 'Copy failed',
    shareText: (planName, low, high, spread) =>
      `${planName} global subscription price comparison: lowest ${low}, highest ${high}, spread ${spread}%.`,
    mapAria: (planName) => `${planName} share map`,
    shareTo: (platform) => `Share to ${platform}`,
    diffAbove: (percent) => `${percent}% more than the US`,
    diffBelow: (percent) => `${percent}% cheaper than the US`,
    diffSame: 'Same as the US',
    comparisonLead: (lowest, highest) =>
      `The price gap between ${lowest} and ${highest} is about `,
    comparisonTrail: '.',
    monthlySuffix: '/mo',
  },
  ja: {
    button: '価格カードを共有',
    dialogLabel: '価格カードを共有',
    close: 'ダイアログを閉じる',
    global: '世界',
    cardTitle: (productName) => `${productName} の地域別価格`,
    planBadge: (planName, referencePrice) =>
      `${planName}プラン・米国基準 ${referencePrice}`,
    cheapestRegion: '最安地域',
    tiedCheapestRegion: (count) => `${count}地域が同率最安`,
    highestRegion: '最高価格の地域',
    maxSpread: '世界の最高・最安価格差',
    coverage: (count) => `${count}地域を確認済み`,
    priceSource: '価格情報源',
    fxDate: '為替日',
    cheaper: '米国より安い',
    usBase: '米国基準',
    moreExpensive: '米国より高い',
    cheapestList: '↓ 最安',
    expensiveList: '↑ 最高',
    verifiedAt: (date) => `GeoSub・データ確認日 ${date}・geosub.org`,
    download: 'PNGをダウンロード',
    downloading: '生成中...',
    copyLink: 'リンクをコピー',
    copied: 'コピーしました',
    copyFailed: 'コピーできませんでした',
    shareText: (planName, low, high, spread) =>
      `${planName}の世界価格比較：最安${low}、最高${high}、価格差${spread}%。`,
    mapAria: (planName) => `${planName}の共有用価格地図`,
    shareTo: (platform) => `${platform}で共有`,
    diffAbove: (percent) => `米国より${percent}%高い`,
    diffBelow: (percent) => `米国より${percent}%安い`,
    diffSame: '米国と同価格',
    comparisonLead: (lowest, highest) =>
      `${lowest}と${highest}の価格差は約`,
    comparisonTrail: 'です。',
    monthlySuffix: '/月',
  },
  ko: {
    button: '가격 카드 공유',
    dialogLabel: '가격 카드 공유',
    close: '대화상자 닫기',
    global: '전 세계',
    cardTitle: (productName) => `${productName} 지역별 가격`,
    planBadge: (planName, referencePrice) =>
      `${planName} 요금제 · 미국 기준 ${referencePrice}`,
    cheapestRegion: '최저가 지역',
    tiedCheapestRegion: (count) => `${count}개 지역 공동 최저가`,
    highestRegion: '최고가 지역',
    maxSpread: '전 세계 최고가와 최저가 차이',
    coverage: (count) => `${count}개 지역 검증`,
    priceSource: '가격 출처',
    fxDate: '환율 기준일',
    cheaper: '미국보다 저렴',
    usBase: '미국 기준',
    moreExpensive: '미국보다 비쌈',
    cheapestList: '↓ 가장 저렴',
    expensiveList: '↑ 가장 비쌈',
    verifiedAt: (date) => `GeoSub · 데이터 확인일 ${date} · geosub.org`,
    download: 'PNG 다운로드',
    downloading: '생성 중...',
    copyLink: '링크 복사',
    copied: '복사됨',
    copyFailed: '복사하지 못했습니다',
    shareText: (planName, low, high, spread) =>
      `${planName} 전 세계 구독 가격 비교: 최저 ${low}, 최고 ${high}, 가격 차이 ${spread}%.`,
    mapAria: (planName) => `${planName} 공유용 가격 지도`,
    shareTo: (platform) => `${platform}에 공유`,
    diffAbove: (percent) => `미국보다 ${percent}% 비쌈`,
    diffBelow: (percent) => `미국보다 ${percent}% 저렴`,
    diffSame: '미국과 같은 가격',
    comparisonLead: (lowest, highest) =>
      `${lowest}와 ${highest}의 가격 차이는 약 `,
    comparisonTrail: '입니다.',
    monthlySuffix: '/월',
  },
  es: {
    button: 'Compartir tarjeta de precios',
    dialogLabel: 'Compartir tarjeta de precios',
    close: 'Cerrar diálogo',
    global: 'Mundial',
    cardTitle: (productName) => `Precios regionales de ${productName}`,
    planBadge: (planName, referencePrice) =>
      `Plan ${planName} · referencia de EE. UU. ${referencePrice}`,
    cheapestRegion: 'Región con el precio más bajo',
    tiedCheapestRegion: (count) => `${count} regiones empatan con el precio más bajo`,
    highestRegion: 'Región con el precio más alto',
    maxSpread: 'Diferencia global entre el máximo y el mínimo',
    coverage: (count) => `${count} regiones verificadas`,
    priceSource: 'Fuente de precios',
    fxDate: 'Fecha del tipo de cambio',
    cheaper: 'Más barato que EE. UU.',
    usBase: 'Referencia de EE. UU.',
    moreExpensive: 'Más caro que EE. UU.',
    cheapestList: '↓ Más baratos',
    expensiveList: '↑ Más caros',
    verifiedAt: (date) => `GeoSub · Datos verificados el ${date} · geosub.org`,
    download: 'Descargar PNG',
    downloading: 'Generando...',
    copyLink: 'Copiar enlace',
    copied: 'Copiado',
    copyFailed: 'No se pudo copiar',
    shareText: (planName, low, high, spread) =>
      `Comparación mundial del plan ${planName}: mínimo ${low}, máximo ${high}, diferencia ${spread}%.`,
    mapAria: (planName) => `Mapa de precios para compartir del plan ${planName}`,
    shareTo: (platform) => `Compartir en ${platform}`,
    diffAbove: (percent) => `${percent}% más que en EE. UU.`,
    diffBelow: (percent) => `${percent}% menos que en EE. UU.`,
    diffSame: 'El mismo precio que en EE. UU.',
    comparisonLead: (lowest, highest) =>
      `La diferencia de precio entre ${lowest} y ${highest} es de aproximadamente `,
    comparisonTrail: '.',
    monthlySuffix: '/mes',
  },
  tr: {
    button: 'Fiyat kartını paylaş',
    dialogLabel: 'Fiyat kartını paylaş',
    close: 'Pencereyi kapat',
    global: 'Dünya geneli',
    cardTitle: (productName) => `${productName} bölgesel fiyatları`,
    planBadge: (planName, referencePrice) =>
      `${planName} paketi · ABD referansı ${referencePrice}`,
    cheapestRegion: 'En düşük fiyatlı bölge',
    tiedCheapestRegion: (count) => `${count} bölge en düşük fiyatta eşit`,
    highestRegion: 'En yüksek fiyatlı bölge',
    maxSpread: 'Dünya genelinde en yüksek-en düşük fiyat farkı',
    coverage: (count) => `${count} bölge doğrulandı`,
    priceSource: 'Fiyat kaynağı',
    fxDate: 'Kur tarihi',
    cheaper: "ABD'den daha ucuz",
    usBase: 'ABD referansı',
    moreExpensive: "ABD'den daha pahalı",
    cheapestList: '↓ En ucuz bölgeler',
    expensiveList: '↑ En pahalı bölgeler',
    verifiedAt: (date) =>
      `GeoSub · Veriler ${date} tarihinde doğrulandı · geosub.org`,
    download: 'PNG indir',
    downloading: 'Hazırlanıyor...',
    copyLink: 'Bağlantıyı kopyala',
    copied: 'Kopyalandı',
    copyFailed: 'Kopyalanamadı',
    shareText: (planName, low, high, spread) =>
      `${planName} dünya geneli abonelik fiyatları: en düşük ${low}, en yüksek ${high}, fiyat farkı %${spread}.`,
    mapAria: (planName) => `${planName} paylaşım fiyat haritası`,
    shareTo: (platform) => `${platform} üzerinde paylaş`,
    diffAbove: (percent) => `ABD'den %${percent} daha pahalı`,
    diffBelow: (percent) => `ABD'den %${percent} daha ucuz`,
    diffSame: 'ABD ile aynı fiyat',
    comparisonLead: (lowest, highest) =>
      `${lowest} ile ${highest} arasındaki fiyat farkı yaklaşık `,
    comparisonTrail: '.',
    monthlySuffix: '/ay',
  },
  ar: {
    button: 'مشاركة بطاقة الأسعار',
    dialogLabel: 'مشاركة بطاقة الأسعار',
    close: 'إغلاق النافذة',
    global: 'عالمي',
    cardTitle: (productName) => `أسعار ${productName} حسب المنطقة`,
    planBadge: (planName, referencePrice) =>
      `باقة ${planName} · مرجع الولايات المتحدة ${referencePrice}`,
    cheapestRegion: 'المنطقة الأقل سعراً',
    tiedCheapestRegion: (count) => `${count} مناطق متعادلة عند أقل سعر`,
    highestRegion: 'المنطقة الأعلى سعراً',
    maxSpread: 'الفارق العالمي بين أعلى وأدنى سعر',
    coverage: (count) => `تم التحقق من ${count} منطقة`,
    priceSource: 'مصدر السعر',
    fxDate: 'تاريخ سعر الصرف',
    cheaper: 'أقل من الولايات المتحدة',
    usBase: 'مرجع الولايات المتحدة',
    moreExpensive: 'أعلى من الولايات المتحدة',
    cheapestList: '↓ الأقل سعراً',
    expensiveList: '↑ الأعلى سعراً',
    verifiedAt: (date) =>
      `GeoSub · تم التحقق من البيانات في ${date} · geosub.org`,
    download: 'تنزيل PNG',
    downloading: 'جارٍ الإنشاء...',
    copyLink: 'نسخ الرابط',
    copied: 'تم النسخ',
    copyFailed: 'تعذر النسخ',
    shareText: (planName, low, high, spread) =>
      `مقارنة عالمية لأسعار باقة ${planName}: الأدنى ${low}، الأعلى ${high}، وفارق السعر ${spread}٪.`,
    mapAria: (planName) => `خريطة أسعار قابلة للمشاركة لباقة ${planName}`,
    shareTo: (platform) => `المشاركة عبر ${platform}`,
    diffAbove: (percent) => `أعلى من الولايات المتحدة بنسبة ${percent}٪`,
    diffBelow: (percent) => `أقل من الولايات المتحدة بنسبة ${percent}٪`,
    diffSame: 'السعر مماثل للولايات المتحدة',
    comparisonLead: (lowest, highest) =>
      `يبلغ فارق السعر بين ${lowest} و${highest} نحو `,
    comparisonTrail: '.',
    monthlySuffix: '/شهر',
  },
  fr: {
    button: 'Partager la carte des prix', dialogLabel: 'Partager la carte des prix', close: 'Fermer la fenêtre',
    global: 'Monde', cardTitle: (p) => `Prix de ${p} par région`,
    planBadge: (p,r) => `Offre ${p} · référence américaine ${r}`, cheapestRegion: 'Région la moins chère',
    tiedCheapestRegion: (c) => `${c} régions ex æquo au prix le plus bas`, highestRegion: 'Région la plus chère',
    maxSpread: 'Écart mondial entre le prix le plus haut et le plus bas', coverage: (c) => `${c} régions vérifiées`,
    priceSource: 'Source des prix', fxDate: 'Date de change',
    cheaper: 'Moins cher que les États-Unis', usBase: 'Référence américaine', moreExpensive: 'Plus cher que les États-Unis',
    cheapestList: '↓ Les moins chers', expensiveList: '↑ Les plus chers',
    verifiedAt: (d) => `GeoSub · données vérifiées le ${d} · geosub.org`, download: 'Télécharger le PNG',
    downloading: 'Création en cours...', copyLink: 'Copier le lien', copied: 'Lien copié', copyFailed: 'Échec de la copie',
    shareText: (p,l,h,s) => `${p} dans le monde : de ${l} à ${h}, soit un écart de ${s} %.`,
    mapAria: (p) => `Carte partageable des prix de ${p}`, shareTo: (p) => `Partager sur ${p}`,
    diffAbove: (p) => `${p} % plus cher qu’aux États-Unis`, diffBelow: (p) => `${p} % moins cher qu’aux États-Unis`,
    diffSame: 'Même prix qu’aux États-Unis', comparisonLead: (l,h) => `L’écart entre ${l} et ${h} est d’environ `,
    comparisonTrail: '.', monthlySuffix: '/mois',
  },
  it: {
    button: 'Condividi la scheda prezzi', dialogLabel: 'Condividi la scheda prezzi', close: 'Chiudi la finestra',
    global: 'Mondo', cardTitle: (p) => `Prezzi di ${p} per regione`,
    planBadge: (p,r) => `Piano ${p} · riferimento USA ${r}`, cheapestRegion: 'Regione meno cara',
    tiedCheapestRegion: (c) => `${c} regioni a pari merito per il prezzo minimo`, highestRegion: 'Regione più cara',
    maxSpread: 'Divario globale tra prezzo massimo e minimo', coverage: (c) => `${c} regioni verificate`,
    priceSource: 'Fonte dei prezzi', fxDate: 'Data del cambio',
    cheaper: 'Meno caro degli Stati Uniti', usBase: 'Riferimento USA', moreExpensive: 'Più caro degli Stati Uniti',
    cheapestList: '↓ I meno cari', expensiveList: '↑ I più cari',
    verifiedAt: (d) => `GeoSub · dati verificati il ${d} · geosub.org`, download: 'Scarica PNG',
    downloading: 'Creazione in corso...', copyLink: 'Copia link', copied: 'Copiato', copyFailed: 'Copia non riuscita',
    shareText: (p,l,h,s) => `${p} nel mondo: da ${l} a ${h}, con una differenza del ${s}%.`,
    mapAria: (p) => `Mappa condivisibile dei prezzi di ${p}`, shareTo: (p) => `Condividi su ${p}`,
    diffAbove: (p) => `${p}% più caro degli Stati Uniti`, diffBelow: (p) => `${p}% meno caro degli Stati Uniti`,
    diffSame: 'Stesso prezzo degli Stati Uniti', comparisonLead: (l,h) => `La differenza tra ${l} e ${h} è circa `,
    comparisonTrail: '.', monthlySuffix: '/mese',
  },
  de: {
    button: 'Preiskarte teilen', dialogLabel: 'Preiskarte teilen', close: 'Fenster schließen',
    global: 'Weltweit', cardTitle: (p) => `${p}: Preise nach Region`,
    planBadge: (p,r) => `Tarif ${p} · US-Referenz ${r}`, cheapestRegion: 'Günstigste Region',
    tiedCheapestRegion: (c) => `${c} Regionen teilen sich den niedrigsten Preis`, highestRegion: 'Teuerste Region',
    maxSpread: 'Globale Spanne zwischen Höchst- und Tiefstpreis', coverage: (c) => `${c} Regionen geprüft`,
    priceSource: 'Preisquelle', fxDate: 'Wechselkursdatum',
    cheaper: 'Günstiger als in den USA', usBase: 'US-Referenz', moreExpensive: 'Teurer als in den USA',
    cheapestList: '↓ Am günstigsten', expensiveList: '↑ Am teuersten',
    verifiedAt: (d) => `GeoSub · Daten geprüft am ${d} · geosub.org`, download: 'PNG herunterladen',
    downloading: 'Wird erstellt...', copyLink: 'Link kopieren', copied: 'Kopiert', copyFailed: 'Kopieren fehlgeschlagen',
    shareText: (p,l,h,s) => `${p} weltweit: von ${l} bis ${h}, Preisunterschied ${s} %.`,
    mapAria: (p) => `Teilbare Preiskarte für ${p}`, shareTo: (p) => `Auf ${p} teilen`,
    diffAbove: (p) => `${p} % teurer als in den USA`, diffBelow: (p) => `${p} % günstiger als in den USA`,
    diffSame: 'Gleicher Preis wie in den USA', comparisonLead: (l,h) => `Der Preisunterschied zwischen ${l} und ${h} beträgt etwa `,
    comparisonTrail: '.', monthlySuffix: '/Monat',
  },
  pt: {
    button: 'Partilhar cartão de preços', dialogLabel: 'Partilhar cartão de preços', close: 'Fechar janela',
    global: 'Mundo', cardTitle: (p) => `Preços de ${p} por região`,
    planBadge: (p,r) => `Plano ${p} · referência dos EUA ${r}`, cheapestRegion: 'Região mais barata',
    tiedCheapestRegion: (c) => `${c} regiões empatadas no preço mais baixo`, highestRegion: 'Região mais cara',
    maxSpread: 'Diferença global entre o preço mais alto e o mais baixo', coverage: (c) => `${c} regiões verificadas`,
    priceSource: 'Fonte dos preços', fxDate: 'Data do câmbio',
    cheaper: 'Mais barato do que nos EUA', usBase: 'Referência dos EUA', moreExpensive: 'Mais caro do que nos EUA',
    cheapestList: '↓ Mais baratos', expensiveList: '↑ Mais caros',
    verifiedAt: (d) => `GeoSub · dados verificados em ${d} · geosub.org`, download: 'Transferir PNG',
    downloading: 'A criar...', copyLink: 'Copiar ligação', copied: 'Copiado', copyFailed: 'Não foi possível copiar',
    shareText: (p,l,h,s) => `${p} no mundo: de ${l} a ${h}, com uma diferença de ${s}%.`,
    mapAria: (p) => `Mapa partilhável de preços de ${p}`, shareTo: (p) => `Partilhar no ${p}`,
    diffAbove: (p) => `${p}% mais caro do que nos EUA`, diffBelow: (p) => `${p}% mais barato do que nos EUA`,
    diffSame: 'Mesmo preço dos EUA', comparisonLead: (l,h) => `A diferença entre ${l} e ${h} é de cerca de `,
    comparisonTrail: '.', monthlySuffix: '/mês',
  },
} satisfies Record<SiteLocale, ShareCopy>;
