-- Generated by scripts/generate-catalog-expansion-sql.cjs.
-- Do not edit this file by hand; update data/catalog-expansion-2026-08.json.
-- New products and plans enter review. Existing lifecycle state is preserved.

BEGIN;

CREATE TEMP TABLE geosub_catalog_expansion(payload JSONB) ON COMMIT DROP;
INSERT INTO geosub_catalog_expansion(payload)
VALUES ($catalog$[
  {
    "slug": "kimi",
    "name": "Kimi",
    "category": "ai",
    "provider": "Moonshot AI",
    "description": "Compare Kimi recurring membership tiers across supported App Store regions.",
    "official_url": "https://www.kimi.com/",
    "sort_order": 280,
    "excluded_aliases": [
      "send kimi a flower",
      "give kimi some snacks",
      "get kimi charged",
      "grab a coffee with kimi",
      "treat kimi to a meal",
      "land on the moon with kimi"
    ],
    "app_store": {
      "id": "6474233312",
      "collector_enabled": true
    },
    "plans": [
      {
        "slug": "moderato",
        "name": "Kimi Moderato",
        "billing_cycle": "monthly",
        "aliases": [
          "moderato",
          "kimi moderato"
        ],
        "sort_order": 10,
        "price_selection_strategy": "lowest_in_expected_range",
        "expected_usd_min": 12,
        "expected_usd_max": 35
      },
      {
        "slug": "allegretto",
        "name": "Kimi Allegretto",
        "billing_cycle": "monthly",
        "aliases": [
          "allegretto",
          "kimi allegretto"
        ],
        "sort_order": 20,
        "price_selection_strategy": "lowest_in_expected_range",
        "expected_usd_min": 25,
        "expected_usd_max": 75
      },
      {
        "slug": "allegro",
        "name": "Kimi Allegro",
        "billing_cycle": "monthly",
        "aliases": [
          "allegro",
          "kimi allegro"
        ],
        "sort_order": 30,
        "price_selection_strategy": "lowest_in_expected_range",
        "expected_usd_min": 65,
        "expected_usd_max": 180
      },
      {
        "slug": "vivace",
        "name": "Kimi Vivace",
        "billing_cycle": "monthly",
        "aliases": [
          "vivace",
          "kimi vivace"
        ],
        "sort_order": 40,
        "price_selection_strategy": "lowest_in_expected_range",
        "expected_usd_min": 130,
        "expected_usd_max": 360
      }
    ]
  },
  {
    "slug": "perplexity",
    "name": "Perplexity",
    "category": "ai",
    "provider": "Perplexity AI",
    "description": "Compare Perplexity Pro and Max subscription prices across supported App Store regions.",
    "official_url": "https://www.perplexity.ai/",
    "sort_order": 290,
    "app_store": {
      "id": "1668000334",
      "collector_enabled": true
    },
    "plans": [
      {
        "slug": "pro",
        "name": "Perplexity Pro",
        "billing_cycle": "monthly",
        "aliases": [
          "perplexity pro",
          "pro"
        ],
        "sort_order": 10,
        "price_selection_strategy": "lowest_in_expected_range",
        "expected_usd_min": 8,
        "expected_usd_max": 45
      },
      {
        "slug": "max",
        "name": "Perplexity Max",
        "billing_cycle": "monthly",
        "aliases": [
          "perplexity max",
          "max"
        ],
        "sort_order": 20,
        "price_selection_strategy": "lowest_in_expected_range",
        "expected_usd_min": 80,
        "expected_usd_max": 330
      }
    ]
  },
  {
    "slug": "suno",
    "name": "Suno",
    "category": "ai",
    "provider": "Suno",
    "description": "Compare Suno Pro and Premier creator subscriptions across supported App Store regions.",
    "official_url": "https://suno.com/",
    "sort_order": 300,
    "app_store": {
      "id": "6480136315",
      "collector_enabled": true
    },
    "plans": [
      {
        "slug": "pro",
        "name": "Suno Pro",
        "billing_cycle": "monthly",
        "aliases": [
          "suno pro",
          "pro"
        ],
        "sort_order": 10,
        "price_selection_strategy": "lowest_in_expected_range",
        "expected_usd_min": 5,
        "expected_usd_max": 25
      },
      {
        "slug": "premier",
        "name": "Suno Premier",
        "billing_cycle": "monthly",
        "aliases": [
          "suno premier",
          "premier"
        ],
        "sort_order": 20,
        "price_selection_strategy": "lowest_in_expected_range",
        "expected_usd_min": 20,
        "expected_usd_max": 60
      }
    ]
  }
]$catalog$::jsonb);

WITH catalog AS (
  SELECT item AS product
  FROM geosub_catalog_expansion,
       jsonb_array_elements(payload) AS item
)
INSERT INTO products (
  id, slug, name, category, provider, description, official_url,
  status, featured, sort_order, created_at, updated_at
)
SELECT
  gen_random_uuid(),
  product ->> 'slug',
  product ->> 'name',
  (product ->> 'category')::product_category,
  product ->> 'provider',
  product ->> 'description',
  product ->> 'official_url',
  'review'::publish_status,
  FALSE,
  (product ->> 'sort_order')::integer,
  NOW(),
  NOW()
FROM catalog
ON CONFLICT (slug) DO UPDATE
SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  provider = EXCLUDED.provider,
  description = COALESCE(NULLIF(products.description, ''), EXCLUDED.description),
  official_url = EXCLUDED.official_url,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();

WITH catalog AS (
  SELECT item AS product
  FROM geosub_catalog_expansion,
       jsonb_array_elements(payload) AS item
), canonical_plans AS (
  SELECT
    product ->> 'slug' AS product_slug,
    plan
  FROM catalog,
       jsonb_array_elements(product -> 'plans') AS plan
)
INSERT INTO plans (
  id, product_id, slug, name, billing_cycle, status, sort_order, created_at, updated_at
)
SELECT
  gen_random_uuid(),
  product.id,
  canonical.plan ->> 'slug',
  canonical.plan ->> 'name',
  (canonical.plan ->> 'billing_cycle')::billing_cycle,
  'review'::publish_status,
  (canonical.plan ->> 'sort_order')::integer,
  NOW(),
  NOW()
FROM canonical_plans canonical
JOIN products product ON product.slug = canonical.product_slug
ON CONFLICT (product_id, slug) DO UPDATE
SET
  name = EXCLUDED.name,
  billing_cycle = EXCLUDED.billing_cycle,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();

WITH catalog AS (
  SELECT item AS product
  FROM geosub_catalog_expansion,
       jsonb_array_elements(payload) AS item
)
UPDATE product_source_profiles profile
SET
  product_id = product.id,
  source_name = product.name || ' official pricing',
  source_url = catalog.product ->> 'official_url',
  config = jsonb_build_object(
    'integration_status', COALESCE(catalog.product ->> 'integration_status', 'app_store_ready'),
    'integration_note', catalog.product ->> 'integration_note',
    'catalog_source', 'catalog-expansion-2026-08'
  ),
  is_active = TRUE,
  updated_at = NOW()
FROM catalog
JOIN products product ON product.slug = catalog.product ->> 'slug'
WHERE profile.product_slug = product.slug
  AND profile.platform = 'web'
  AND profile.source_type = 'official_page';

WITH catalog AS (
  SELECT item AS product
  FROM geosub_catalog_expansion,
       jsonb_array_elements(payload) AS item
)
INSERT INTO product_source_profiles (
  id, product_id, product_slug, platform, source_type, source_name,
  source_url, config, is_active, created_at, updated_at
)
SELECT
  gen_random_uuid(),
  product.id,
  product.slug,
  'web',
  'official_page',
  product.name || ' official pricing',
  catalog.product ->> 'official_url',
  jsonb_build_object(
    'integration_status', COALESCE(catalog.product ->> 'integration_status', 'app_store_ready'),
    'integration_note', catalog.product ->> 'integration_note',
    'catalog_source', 'catalog-expansion-2026-08'
  ),
  TRUE,
  NOW(),
  NOW()
FROM catalog
JOIN products product ON product.slug = catalog.product ->> 'slug'
WHERE NOT EXISTS (
  SELECT 1
  FROM product_source_profiles existing
  WHERE existing.product_slug = product.slug
    AND existing.platform = 'web'
    AND existing.source_type = 'official_page'
);

WITH catalog AS (
  SELECT item AS product
  FROM geosub_catalog_expansion,
       jsonb_array_elements(payload) AS item
  WHERE COALESCE((item -> 'app_store' ->> 'collector_enabled')::boolean, FALSE)
)
UPDATE product_source_profiles profile
SET
  product_id = product.id,
  source_name = product.name || ' App Store',
  external_app_id = catalog.product -> 'app_store' ->> 'id',
  bundle_id = catalog.product -> 'app_store' ->> 'bundle_id',
  source_url = 'https://apps.apple.com/us/app/id' || (catalog.product -> 'app_store' ->> 'id'),
  config = jsonb_build_object(
    'collector_kind', 'app_store',
    'catalog_source', 'catalog-expansion-2026-08'
  ),
  is_active = TRUE,
  updated_at = NOW()
FROM catalog
JOIN products product ON product.slug = catalog.product ->> 'slug'
WHERE profile.product_slug = product.slug
  AND profile.platform = 'app_store_ios'
  AND profile.source_type = 'app_store_page'
  AND COALESCE(profile.external_app_id, '') = catalog.product -> 'app_store' ->> 'id';

WITH catalog AS (
  SELECT item AS product
  FROM geosub_catalog_expansion,
       jsonb_array_elements(payload) AS item
  WHERE COALESCE((item -> 'app_store' ->> 'collector_enabled')::boolean, FALSE)
)
INSERT INTO product_source_profiles (
  id, product_id, product_slug, platform, source_type, source_name,
  external_app_id, bundle_id, source_url, config, is_active, created_at, updated_at
)
SELECT
  gen_random_uuid(),
  product.id,
  product.slug,
  'app_store_ios',
  'app_store_page',
  product.name || ' App Store',
  catalog.product -> 'app_store' ->> 'id',
  catalog.product -> 'app_store' ->> 'bundle_id',
  'https://apps.apple.com/us/app/id' || (catalog.product -> 'app_store' ->> 'id'),
  jsonb_build_object(
    'collector_kind', 'app_store',
    'catalog_source', 'catalog-expansion-2026-08'
  ),
  TRUE,
  NOW(),
  NOW()
FROM catalog
JOIN products product ON product.slug = catalog.product ->> 'slug'
WHERE NOT EXISTS (
  SELECT 1
  FROM product_source_profiles existing
  WHERE existing.product_slug = product.slug
    AND existing.platform = 'app_store_ios'
    AND existing.source_type = 'app_store_page'
    AND COALESCE(existing.external_app_id, '') = catalog.product -> 'app_store' ->> 'id'
);

WITH app_store_catalog AS (
  SELECT
    item AS product,
    ROW_NUMBER() OVER (ORDER BY (item ->> 'sort_order')::integer, item ->> 'slug') - 1 AS sequence
  FROM geosub_catalog_expansion,
       jsonb_array_elements(payload) AS item
  WHERE COALESCE((item -> 'app_store' ->> 'collector_enabled')::boolean, FALSE)
), job_variants(schedule, priority, delay_days, country_codes, accuracy_policy) AS (
  VALUES
    ('daily_light', 90, 0, '["US","JP","GB","DE","FR","IN","TR","BR","CA","SG","AU","KR","MX","ID","PH","TH","MY","VN","ZA","AE"]'::jsonb, 'daily_core_regions'),
    ('weekly_full', 55, 3, '["DEFAULT"]'::jsonb, 'weekly_common_regions')
)
INSERT INTO collector_jobs (
  id, product_id, job_type, schedule, status, next_run_at,
  success_count, error_count, last_error, job_config, priority, created_at, updated_at
)
SELECT
  gen_random_uuid(),
  product.id,
  CASE
    WHEN product.category = 'streaming'::product_category THEN 'streaming_pricing'
    ELSE 'ai_pricing'
  END,
  variant.schedule,
  'active',
  NOW() + make_interval(days => variant.delay_days, hours => catalog.sequence::integer),
  0,
  0,
  NULL,
  jsonb_build_object(
    'url', 'https://apps.apple.com/us/app/id' || (catalog.product -> 'app_store' ->> 'id'),
    'product_id', product.id,
    'source_kind', 'app-store',
    'app_store_id', catalog.product -> 'app_store' ->> 'id',
    'collector_kind', 'app_store',
    'schedule_strategy', variant.schedule,
    'country_codes', variant.country_codes,
    'accuracy_policy', variant.accuracy_policy,
    'created_from', 'catalog-expansion-2026-08'
  ),
  variant.priority,
  NOW(),
  NOW()
FROM app_store_catalog catalog
JOIN products product ON product.slug = catalog.product ->> 'slug'
CROSS JOIN job_variants variant
WHERE NOT EXISTS (
  SELECT 1
  FROM collector_jobs existing
  WHERE existing.product_id = product.id
    AND existing.job_config ->> 'collector_kind' = 'app_store'
    AND existing.schedule = variant.schedule
    AND existing.status <> 'archived'
);

COMMIT;
