-- Apple App Store storefront coverage.
-- Source: Apple Support "Availability of Apple Media Services" page, checked 2026-07-01.
-- CN and HK are kept in the country catalog for completeness, but the App Store
-- collector excludes them by default in collect-app-store-prices.ps1.

WITH seed(code, name_en, currency, region, sort_order) AS (
  VALUES
    ('US', 'United States', 'USD', 'North America', 10),
    ('CA', 'Canada', 'CAD', 'North America', 20),
    ('AI', 'Anguilla', 'XCD', 'Latin America', 30),
    ('AG', 'Antigua and Barbuda', 'XCD', 'Latin America', 40),
    ('AR', 'Argentina', 'ARS', 'Latin America', 50),
    ('BS', 'Bahamas', 'BSD', 'Latin America', 60),
    ('BB', 'Barbados', 'BBD', 'Latin America', 70),
    ('BZ', 'Belize', 'BZD', 'Latin America', 80),
    ('BM', 'Bermuda', 'BMD', 'Latin America', 90),
    ('BO', 'Bolivia', 'BOB', 'Latin America', 100),
    ('BR', 'Brazil', 'BRL', 'Latin America', 110),
    ('VG', 'British Virgin Islands', 'USD', 'Latin America', 120),
    ('KY', 'Cayman Islands', 'KYD', 'Latin America', 130),
    ('CL', 'Chile', 'CLP', 'Latin America', 140),
    ('CO', 'Colombia', 'COP', 'Latin America', 150),
    ('CR', 'Costa Rica', 'CRC', 'Latin America', 160),
    ('DM', 'Dominica', 'XCD', 'Latin America', 170),
    ('DO', 'Dominican Republic', 'DOP', 'Latin America', 180),
    ('EC', 'Ecuador', 'USD', 'Latin America', 190),
    ('SV', 'El Salvador', 'USD', 'Latin America', 200),
    ('GD', 'Grenada', 'XCD', 'Latin America', 210),
    ('GT', 'Guatemala', 'GTQ', 'Latin America', 220),
    ('GY', 'Guyana', 'GYD', 'Latin America', 230),
    ('HN', 'Honduras', 'HNL', 'Latin America', 240),
    ('JM', 'Jamaica', 'JMD', 'Latin America', 250),
    ('MX', 'Mexico', 'MXN', 'Latin America', 260),
    ('MS', 'Montserrat', 'XCD', 'Latin America', 270),
    ('NI', 'Nicaragua', 'NIO', 'Latin America', 280),
    ('PA', 'Panama', 'PAB', 'Latin America', 290),
    ('PY', 'Paraguay', 'PYG', 'Latin America', 300),
    ('PE', 'Peru', 'PEN', 'Latin America', 310),
    ('KN', 'St. Kitts and Nevis', 'XCD', 'Latin America', 320),
    ('LC', 'St. Lucia', 'XCD', 'Latin America', 330),
    ('VC', 'St. Vincent and the Grenadines', 'XCD', 'Latin America', 340),
    ('SR', 'Suriname', 'SRD', 'Latin America', 350),
    ('TT', 'Trinidad and Tobago', 'TTD', 'Latin America', 360),
    ('TC', 'Turks and Caicos', 'USD', 'Latin America', 370),
    ('UY', 'Uruguay', 'UYU', 'Latin America', 380),
    ('VE', 'Venezuela', 'VES', 'Latin America', 390),
    ('AL', 'Albania', 'ALL', 'Europe', 400),
    ('AT', 'Austria', 'EUR', 'Europe', 410),
    ('BY', 'Belarus', 'BYN', 'Europe', 420),
    ('BE', 'Belgium', 'EUR', 'Europe', 430),
    ('BA', 'Bosnia and Herzegovina', 'BAM', 'Europe', 440),
    ('BG', 'Bulgaria', 'BGN', 'Europe', 450),
    ('HR', 'Croatia', 'EUR', 'Europe', 460),
    ('CY', 'Cyprus', 'EUR', 'Europe', 470),
    ('CZ', 'Czechia', 'CZK', 'Europe', 480),
    ('DK', 'Denmark', 'DKK', 'Europe', 490),
    ('EE', 'Estonia', 'EUR', 'Europe', 500),
    ('FI', 'Finland', 'EUR', 'Europe', 510),
    ('FR', 'France', 'EUR', 'Europe', 520),
    ('GE', 'Georgia', 'GEL', 'Europe', 530),
    ('DE', 'Germany', 'EUR', 'Europe', 540),
    ('GR', 'Greece', 'EUR', 'Europe', 550),
    ('HU', 'Hungary', 'HUF', 'Europe', 560),
    ('IS', 'Iceland', 'ISK', 'Europe', 570),
    ('IE', 'Ireland', 'EUR', 'Europe', 580),
    ('IT', 'Italy', 'EUR', 'Europe', 590),
    ('KZ', 'Kazakhstan', 'KZT', 'Europe', 600),
    ('XK', 'Kosovo', 'EUR', 'Europe', 610),
    ('KG', 'Kyrgyzstan', 'KGS', 'Europe', 620),
    ('LV', 'Latvia', 'EUR', 'Europe', 630),
    ('LT', 'Lithuania', 'EUR', 'Europe', 640),
    ('LU', 'Luxembourg', 'EUR', 'Europe', 650),
    ('MT', 'Malta', 'EUR', 'Europe', 660),
    ('MD', 'Moldova', 'MDL', 'Europe', 670),
    ('ME', 'Montenegro', 'EUR', 'Europe', 680),
    ('NL', 'Netherlands', 'EUR', 'Europe', 690),
    ('MK', 'North Macedonia', 'MKD', 'Europe', 700),
    ('NO', 'Norway', 'NOK', 'Europe', 710),
    ('PL', 'Poland', 'PLN', 'Europe', 720),
    ('PT', 'Portugal', 'EUR', 'Europe', 730),
    ('RO', 'Romania', 'RON', 'Europe', 740),
    ('RU', 'Russia', 'RUB', 'Europe', 750),
    ('RS', 'Serbia', 'RSD', 'Europe', 760),
    ('SK', 'Slovakia', 'EUR', 'Europe', 770),
    ('SI', 'Slovenia', 'EUR', 'Europe', 780),
    ('ES', 'Spain', 'EUR', 'Europe', 790),
    ('SE', 'Sweden', 'SEK', 'Europe', 800),
    ('CH', 'Switzerland', 'CHF', 'Europe', 810),
    ('TJ', 'Tajikistan', 'TJS', 'Europe', 820),
    ('TM', 'Turkmenistan', 'TMT', 'Europe', 830),
    ('UA', 'Ukraine', 'UAH', 'Europe', 840),
    ('GB', 'United Kingdom', 'GBP', 'Europe', 850),
    ('UZ', 'Uzbekistan', 'UZS', 'Europe', 860),
    ('DZ', 'Algeria', 'DZD', 'Africa', 870),
    ('AO', 'Angola', 'AOA', 'Africa', 880),
    ('BJ', 'Benin', 'XOF', 'Africa', 890),
    ('BW', 'Botswana', 'BWP', 'Africa', 900),
    ('BF', 'Burkina Faso', 'XOF', 'Africa', 910),
    ('CM', 'Cameroon', 'XAF', 'Africa', 920),
    ('CV', 'Cape Verde', 'CVE', 'Africa', 930),
    ('TD', 'Chad', 'XAF', 'Africa', 940),
    ('CD', 'Congo, Democratic Republic of the', 'CDF', 'Africa', 950),
    ('CG', 'Congo, Republic of the', 'XAF', 'Africa', 960),
    ('CI', 'Cote d''Ivoire', 'XOF', 'Africa', 970),
    ('SZ', 'Eswatini', 'SZL', 'Africa', 980),
    ('GA', 'Gabon', 'XAF', 'Africa', 990),
    ('GH', 'Ghana', 'GHS', 'Africa', 1000),
    ('GM', 'The Gambia', 'GMD', 'Africa', 1010),
    ('GW', 'Guinea-Bissau', 'XOF', 'Africa', 1020),
    ('KE', 'Kenya', 'KES', 'Africa', 1030),
    ('LR', 'Liberia', 'LRD', 'Africa', 1040),
    ('MG', 'Madagascar', 'MGA', 'Africa', 1050),
    ('MW', 'Malawi', 'MWK', 'Africa', 1060),
    ('ML', 'Mali', 'XOF', 'Africa', 1070),
    ('MR', 'Mauritania', 'MRU', 'Africa', 1080),
    ('MU', 'Mauritius', 'MUR', 'Africa', 1090),
    ('MA', 'Morocco', 'MAD', 'Africa', 1100),
    ('MZ', 'Mozambique', 'MZN', 'Africa', 1110),
    ('NA', 'Namibia', 'NAD', 'Africa', 1120),
    ('NE', 'Niger', 'XOF', 'Africa', 1130),
    ('NG', 'Nigeria', 'NGN', 'Africa', 1140),
    ('RW', 'Rwanda', 'RWF', 'Africa', 1150),
    ('ST', 'Sao Tome and Principe', 'STN', 'Africa', 1160),
    ('SN', 'Senegal', 'XOF', 'Africa', 1170),
    ('SC', 'Seychelles', 'SCR', 'Africa', 1180),
    ('SL', 'Sierra Leone', 'SLE', 'Africa', 1190),
    ('ZA', 'South Africa', 'ZAR', 'Africa', 1200),
    ('TZ', 'Tanzania', 'TZS', 'Africa', 1210),
    ('TN', 'Tunisia', 'TND', 'Africa', 1220),
    ('UG', 'Uganda', 'UGX', 'Africa', 1230),
    ('ZM', 'Zambia', 'ZMW', 'Africa', 1240),
    ('ZW', 'Zimbabwe', 'USD', 'Africa', 1250),
    ('AU', 'Australia', 'AUD', 'Asia-Pacific', 1260),
    ('BT', 'Bhutan', 'BTN', 'Asia-Pacific', 1270),
    ('BN', 'Brunei', 'BND', 'Asia-Pacific', 1280),
    ('KH', 'Cambodia', 'KHR', 'Asia-Pacific', 1290),
    ('CN', 'China mainland', 'CNY', 'Asia-Pacific', 1300),
    ('FJ', 'Fiji', 'FJD', 'Asia-Pacific', 1310),
    ('HK', 'Hong Kong', 'HKD', 'Asia-Pacific', 1320),
    ('IN', 'India', 'INR', 'Asia-Pacific', 1330),
    ('ID', 'Indonesia', 'IDR', 'Asia-Pacific', 1340),
    ('JP', 'Japan', 'JPY', 'Asia-Pacific', 1350),
    ('LA', 'Laos', 'LAK', 'Asia-Pacific', 1360),
    ('MO', 'Macao', 'MOP', 'Asia-Pacific', 1370),
    ('MY', 'Malaysia', 'MYR', 'Asia-Pacific', 1380),
    ('MV', 'Maldives', 'MVR', 'Asia-Pacific', 1390),
    ('FM', 'Micronesia', 'USD', 'Asia-Pacific', 1400),
    ('MN', 'Mongolia', 'MNT', 'Asia-Pacific', 1410),
    ('MM', 'Myanmar', 'MMK', 'Asia-Pacific', 1420),
    ('NR', 'Nauru', 'AUD', 'Asia-Pacific', 1430),
    ('NP', 'Nepal', 'NPR', 'Asia-Pacific', 1440),
    ('NZ', 'New Zealand', 'NZD', 'Asia-Pacific', 1450),
    ('PK', 'Pakistan', 'PKR', 'Asia-Pacific', 1460),
    ('PW', 'Palau', 'USD', 'Asia-Pacific', 1470),
    ('PG', 'Papua New Guinea', 'PGK', 'Asia-Pacific', 1480),
    ('PH', 'Philippines', 'PHP', 'Asia-Pacific', 1490),
    ('SG', 'Singapore', 'SGD', 'Asia-Pacific', 1500),
    ('SB', 'Solomon Islands', 'SBD', 'Asia-Pacific', 1510),
    ('KR', 'South Korea', 'KRW', 'Asia-Pacific', 1520),
    ('LK', 'Sri Lanka', 'LKR', 'Asia-Pacific', 1530),
    ('TW', 'Taiwan', 'TWD', 'Asia-Pacific', 1540),
    ('TH', 'Thailand', 'THB', 'Asia-Pacific', 1550),
    ('TO', 'Tonga', 'TOP', 'Asia-Pacific', 1560),
    ('VU', 'Vanuatu', 'VUV', 'Asia-Pacific', 1570),
    ('VN', 'Vietnam', 'VND', 'Asia-Pacific', 1580),
    ('AF', 'Afghanistan', 'AFN', 'Middle East', 1590),
    ('AM', 'Armenia', 'AMD', 'Middle East', 1600),
    ('AZ', 'Azerbaijan', 'AZN', 'Middle East', 1610),
    ('BH', 'Bahrain', 'BHD', 'Middle East', 1620),
    ('EG', 'Egypt', 'EGP', 'Middle East', 1630),
    ('IQ', 'Iraq', 'IQD', 'Middle East', 1640),
    ('IL', 'Israel', 'ILS', 'Middle East', 1650),
    ('JO', 'Jordan', 'JOD', 'Middle East', 1660),
    ('KW', 'Kuwait', 'KWD', 'Middle East', 1670),
    ('LB', 'Lebanon', 'LBP', 'Middle East', 1680),
    ('LY', 'Libya', 'LYD', 'Middle East', 1690),
    ('OM', 'Oman', 'OMR', 'Middle East', 1700),
    ('QA', 'Qatar', 'QAR', 'Middle East', 1710),
    ('SA', 'Saudi Arabia', 'SAR', 'Middle East', 1720),
    ('TR', 'Turkiye', 'TRY', 'Middle East', 1730),
    ('AE', 'United Arab Emirates', 'AED', 'Middle East', 1740),
    ('YE', 'Yemen', 'YER', 'Middle East', 1750)
)
INSERT INTO countries (
  id,
  code,
  name_zh,
  name_en,
  currency,
  region,
  is_reference,
  is_supported,
  sort_order,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  seed.code,
  seed.name_en,
  seed.name_en,
  seed.currency,
  seed.region,
  seed.code = 'US',
  TRUE,
  seed.sort_order,
  NOW(),
  NOW()
FROM seed
ON CONFLICT (code) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_zh = CASE
    WHEN countries.name_zh IS NULL OR countries.name_zh = '' OR countries.name_zh LIKE '%?%'
      THEN EXCLUDED.name_zh
    ELSE countries.name_zh
  END,
  currency = EXCLUDED.currency,
  region = EXCLUDED.region,
  is_supported = TRUE,
  is_reference = EXCLUDED.is_reference,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
